promptfoo/promptfoo

- examples/simple-test/output.html
- examples/simple-test/output.json
- examples/simple-test/vars.csv
- src/assertions.ts
- test/evaluator.test.ts
Closes https://github.com/typpo/promptfoo/issues/10
> feat: rename eval: to fn: for custum js fnc tests

- examples/simple-cli/promptfooconfig.js
- package-lock.json
- package.json
- src/assertions.ts
- src/util.ts
- test/util.test.ts
Closes #12 
Allows things like:
- `./prompts` (directory)
- `./prompts/*`
- `**/*.txt`
> Add glob support

- src/assertions.ts
- src/types.ts
- test/assertions.test.ts
This PR adds:
* not-contains
* contains-lower
* not-contains-lower
* contains-all
* contains-any
* regex
* not-regex
* not-similar
> Add many new assertion types

- src/main.ts
- src/util.ts
- src/web/client/package-lock.json
- src/web/client/package.json
- src/web/client/src/App.tsx
- src/web/client/src/ConfigModal.tsx
- src/web/client/src/ResultsView.tsx
- src/web/client/src/ShareModal.tsx
- src/web/client/src/store.ts
- src/web/client/src/types.ts
- src/web/server.ts
Makes it easier to show results & test configs to others you're working with.
> Add support for sharing

- src/index.ts
- src/logger.ts
- src/main.ts
- src/table.ts
Closes https://github.com/typpo/promptfoo/issues/36
The table generated from the CLI is great, let’s export it
> extract and export generateTable()

- README.md
- src/assertions.ts
- src/cache.ts
- src/prompts.ts
- src/util.ts
- test/assertions.test.ts
> Add retries for failed HTTP requests

- src/providers/openai.ts
Added latest gpt-3.5-turbo increased token limits.
> added gpt-3.5-16k and checkpoints

- package-lock.json
- package.json
- src/providers.ts
- src/providers/anthropic.ts
- test/providers.test.ts
Unit tested and manually tested with live calls
> Add Anthropic provider

- src/providers/azureopenai.ts
- src/providers/localai.ts
- src/providers/openai.ts
- src/providers/shared.ts
> Move OpenAI yaml support into shared providers util

- src/providers/azureopenai.ts
- src/providers/openai.ts
Adds frequency_penalty, presence_penalty, top_p, best_of to OpenAI and Azure OpenAI providers
Closes #79
> Additional OpenAI params

- src/evaluator.ts
- src/types.ts
- src/web/client/src/ResultsTable.css
- src/web/client/src/ResultsTable.tsx
- src/web/client/src/types.ts
- test/util.test.ts
Record latency and expose it on the webview and in other outputs
> Record latency in results

- README.md
- src/assertions.ts
- src/evaluator.ts
- src/types.ts
This makes life easier for users who are more comfortable in the python ecosystem.
> Add `python` assertion type that runs python code and returns the output

- .gitignore
- src/providers.ts
- src/providers/llama.ts
- test/providers.test.ts
Adds a provider for the built-in llama.cpp HTTP server https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md
> Add support for llama.cpp server

- examples/simple-test/output.csv
- src/assertions.ts
- src/evaluator.ts
- src/types.ts
- src/web/client/src/EvalOutputPromptDialog.tsx
- src/web/client/src/ResultsTable.tsx
- src/web/client/src/types.ts
- test/assertions.test.ts
1. Include the assert count in table header (closes #98)
2. Show asserts in output "inspect" view
> Add assertions in webview

- src/assertions.ts
- src/evaluator.ts
- src/util.ts
- test/evaluator.test.ts
> Disable nunjucks autoescaping by default

- src/cache.ts
- src/providers.ts
- src/providers/azureopenai.ts
- src/providers/llama.ts
- src/providers/localai.ts
- src/providers/ollama.ts
- src/providers/openai.ts
- test/cache.test.ts
- test/providers.test.ts
Add support for https://github.com/jmorganca/ollama
> Add ollama provider

- src/providers/azureopenai.ts
Returns function_call arguments properly as a string
> function call azure fix

- README.md
- jest.config.ts
- package-lock.json
- package.json
- src/assertions.ts
- src/types.ts
- test/assertions.test.ts
```yaml
assert:
- type: levenshtein
threshold: 5
value: hello world
```
> Add support for Levenshtein distance assert type

- src/web/nextui/package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/ResultsCharts.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
The purpose of these visualizations is to make it a easier to see trends and major takeaways at a glance.
> Add charts to web viewer

- src/index.ts
- src/web/nextui/package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/Eval.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
- src/web/nextui/src/app/eval/[id]/page.tsx
- src/web/nextui/src/app/eval/page.tsx
- src/web/nextui/src/app/setup/ProviderSelector.tsx
- src/web/nextui/src/app/setup/YamlEditor.css
- src/web/nextui/src/app/setup/YamlEditor.tsx
- src/web/nextui/src/app/setup/page.tsx
- src/web/nextui/src/util/store.ts
- src/web/server.ts
- Add YAML editor to "create new eval" page
- Add an "Edit Eval" button to eval viewer
- Add deeplinks to evals stored locally, `/evals/local:<eval name>`
> Add support for editing config in web view

- src/index.ts
- src/main.ts
- src/types.ts
> Add support for disabling cache in evaluate() options

- src/assertions.ts
> Use provider from testcase/assertion for similarity check

- src/main.ts
- src/web/server.ts
> Add a -y/--yes option to `promptfoo view` command to skip confirmation

- package.json
Helps automated tools out (e.g., lets Dependabot know where to find changelogs etc.).
> Specify repo in package.json

- examples/colab-notebook/promptfoo_example.ipynb
This updates the Google Colab notebook example.  Currently, the approach downgrades the version that Google Colab makes available. This approach uses the `n` Node.js version manager for simplicity. You can view my test example at https://colab.research.google.com/drive/1NOzolcu5aH_bMQ6qyxX4DdY4QrRCFk45?usp=sharing.
> Updated node version update of Google Colab notebook example

- src/providers/openai.ts
Makes it easier to report https://github.com/promptfoo/promptfoo/issues/185:
- Including `data` in embeddings packet traversal failure
- Standardizing API debug messages to mention the API
> Better OpenAI embeddings traversal failure

- src/providers.ts
- src/providers/localai.ts
- src/providers/ollama.ts
> Adds embeddings providers for LocalAI and Oolama

- src/providers/localai.ts
- src/providers/ollama.ts
- src/providers/openai.ts
- https://github.com/promptfoo/promptfoo/pull/190, but now for LocalAI and Ollama
- Removed extra `ret` locals
Relates to https://github.com/promptfoo/promptfoo/issues/175.
> Better LocalAI/Ollama embeddings traversal failure

- src/assertions.ts
- src/web/nextui/src/app/eval/EvalOutputPromptDialog.tsx
> Webview details pane improvements

- src/main.ts
- src/util.ts
> Adding TXT and HTML to `--output` help/error message

- src/assertions.ts
- test/assertions.test.ts
> Fix bug in custom function boolean return value score

- README.md
- src/assertions.ts
- src/types.ts
- test/assertions.test.ts
> Add support for icontains-any and icontains-all

- src/assertions.ts
- src/prompts.ts
> Add support for .cjs file extensions

- src/assertions.ts
- src/testCases.ts
> Fix issue with loading google sheets directly.

- src/matchers.ts
- test/matchers.test.ts
> Improve escaping in matchers

- src/evaluator.ts
- src/main.ts
- src/providers/azureopenai.ts
- src/providers/openai.ts
- src/types.ts
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
> Add latency and token metrics per prompt

- src/providers/anthropic.ts
- test/providers.test.ts
I'm not sure why but the anthropic provider had no caching support, possibly because it's the only provider that doesn't use fetch.
This PR provides an implementation to support caching for calls to anthropic, along with tests for the anthropic behaviour, improvements to the tests for caching behaviour of OpenAI (these were not actually testing what they claimed) and the addition of a call to clear the cache after every test to ensure that the cache does not change the behaviour of tests.
> Add caching support to Anthropic provider

- src/assertions.ts
- src/evaluator.ts
- src/main.ts
- src/matchers.ts
- src/suggestions.ts
- src/types.ts
Fixes issues caused when OpenAI outputs are not necessarily strings.
> fix(openai): Improve handling for function call responses

- src/evaluator.ts
- src/types.ts
- src/web/nextui/src/app/eval/Eval.tsx
- src/web/nextui/src/app/eval/ResultsCharts.tsx
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/store.ts
- src/web/nextui/src/app/eval/types.ts
- src/web/nextui/src/app/globals.css
Add "Description" column if test description is set
> feat(webview): Display test descriptions if available

- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
Add button to override individual test scores, and make cell action buttons less prominent
> feat(webview): Ability to set test scores manually

- package-lock.json
- package.json
- src/feedback.ts
- src/fetch.ts
- src/providers.ts
- src/share.ts
- test/assertions.test.ts
- test/providers.test.ts
- test/testCases.test.ts
- test/util.test.ts
Adds support for `HTTP_PROXY`, `HTTPS_PROXY`, and other environment variables.
> feat: Add support for HTTP proxies

- src/web/nextui/src/app/setup/ProviderSelector.tsx
Add bedrock setup in webui #300
> feat: add bedrock in websui setup

- src/web/nextui/src/app/eval/ResultsTable.tsx
> fix: remove use of dangerouslySetInnerHTML in results table

- examples/node-package/index.js
- examples/node-package/output.json
- src/index.ts
- src/types.ts
> feat: support prompt functions via nodejs interface

- src/web/nextui/src/app/eval/ResultsTable.tsx
Avoiding this sort of logic is why we were originally just inserting raw html: https://github.com/promptfoo/promptfoo/issues/308
> fix: webview handling of truncated cell contents with html

- src/web/nextui/src/app/eval/CustomMetrics.css
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
> feat(webview): Show aggregated named metrics at top of column

- src/web/nextui/src/app/eval/CustomMetrics.css
- src/web/nextui/src/app/eval/CustomMetrics.tsx
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/globals.css
- Improve visibility of named metrics
- Improve visibility of top-level pass rate
- Show token/latency usage in each row by default (instead of on hover)
- Minor spacing improvements to make information more compact
Before:
After:
> feat(webview): Layout and styling improvements

- examples/google-vertex/README.md
- examples/google-vertex/promptfooconfig.yaml
- examples/google-vertex/prompts.txt
- site/docs/providers/vertex.md
- src/providers/vertex.ts
- src/providers/vertexUtil.ts
Adds support for `vertex:gemini-pro` and (optimistically) `vertex:gemini-ultra`
> feat: add support for Google Gemini model

- site/docs/providers/ollama.md
- src/providers.ts
- src/providers/ollama.ts
- test/providers.test.ts
> feat: add support for ollama chat API

- site/docs/providers/openai.md
- src/providers/openai.ts
- src/providers/openaiUtil.ts
Add openai tool parameter
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools
> feat: add openai tool parameter

- src/assertions.ts
- test/assertions.test.ts
Related to #352.  Bad indentation in a refactor of python-related code causes python asserts to fail.
Also improves error handling for python script errors
> fix: bad indentation for inline python sript

- README.md
- examples/openai-tools-call/README.md
- examples/openai-tools-call/prompt.txt
- examples/openai-tools-call/promptfooconfig.yaml
- site/docs/configuration/expected-outputs/index.md
- site/docs/providers/openai.md
- site/docs/usage/node-package.md
- src/assertions.ts
- src/providers/openai.ts
- src/types.ts
- src/web/nextui/src/app/setup/AssertsForm.tsx
- test/assertions.test.ts
`functions` are deprecated and `tools` are in
> feat: add `is-valid-openai-tools-call` assertion type

- src/providers/huggingface.ts
- test/providers.test.ts
> fix: handle huggingface text generation returning dict

- src/web/nextui/package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
- src/web/nextui/src/app/globals.css
Adds a search box on top of the webview that matches against LLM and grading outputs
> feat(webview): add regex search

- src/matchers.ts
- src/types.ts
- test/matchers.test.ts
> fix: proper support for multiple types of test providers

- src/providers/openai.ts
> feat(openai): add support for `passthrough` request args

- package-lock.json
- package.json
- site/docs/providers/azure.md
- src/providers/azureopenai.ts
> feat(azure): add support for client id/secret auth

- examples/simple-cli/promptfooconfig.yaml
- src/main.ts
- src/util.ts
- src/web/nextui/src/app/eval/ResultsView.tsx
- src/web/server.ts
Also makes the select menu searchable
Related to #383
> feat(webui): label evals using `description` field

- src/types.ts
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/layout.tsx
> feat(webui): Ability to comment on outputs

- src/providers/azureopenai.ts
> feat(azure): add support for `passthrough` and `apiVersion`

- examples/assistant-cli/prompts.txt
- src/web/nextui/package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsViewSettingsModal.tsx
- src/web/nextui/src/app/eval/store.ts
Adds markdown toggle in table settings
Settings:
Output:
> feat(webui): add markdown support

- src/util.ts
> feat: `PROMPTFOO_DISABLE_TEMPLATING` disables nunjucks templates

- src/providers/openai.ts
> fix: do not require token usage info on openai provider

- src/web/nextui/src/app/eval/Eval.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
Navigating to an eval will update the browser URL, so you can more easily share evals with other people.
> feat(webui): eval deeplinks

- src/tableOutput.html
It fix issue with HTML generated from test results
> Fix html output

- examples/huggingface-similarity/README.md
- examples/huggingface-similarity/promptfooconfig.yaml
- examples/multiple-translations/promptfooconfig.yaml
- site/docs/configuration/expected-outputs/similar.md
- site/docs/providers/huggingface.md
- src/matchers.ts
- src/providers.ts
- src/providers/huggingface.ts
- src/types.ts
- test/matchers.test.ts
For example:
```yaml
assert:
- type: similar
value: 'Hello world'
provider: huggingface:sentence-similarity:sentence-transformers/all-MiniLM-L6-v2
threshold: 0.1
```
> feat(huggingface): Support sentence similarity inference API

- examples/google-aistudio-gemini/README.md
- examples/google-aistudio-gemini/promptfooconfig.yaml
- src/providers/palm.ts
> fix: support for gemini generationConfig and safetySettings

- site/docs/providers/azure.md
- src/providers/azureopenai.ts
- src/types.ts
> feat(azureopenai): add apiBaseUrl config

- examples/cohere/README.md
- examples/cohere/complex_config.yaml
- examples/cohere/prompt.yaml
- examples/cohere/promptfooconfig.yaml
- examples/cohere/simple_config.yaml
- site/docs/providers/cohere.md
- src/providers.ts
- src/providers/cohere.ts
- src/types.ts
Adds support for Cohere's chat API.  https://docs.cohere.com/reference/chat
Related to #453
> feat: cohere api support

- src/evaluator.ts
> chore: include progress output in debug logs

- examples/openai-eval-factuality/promptfooconfig.yaml
- src/matchers.ts
- src/web/nextui/src/app/setup/AssertsForm.tsx
Closes #466 
Also updates `model-graded-factuality` in documentation to just `factuality`
> fix(factuality): make factuality output case-insensitive

- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsViewSettingsModal.tsx
- src/web/nextui/src/app/eval/store.ts
> feat(webview): toggle for prettifying json outputs

- src/assertions.ts
> feat: support for overriding `select-best` provider

- src/providers/ollama.ts
Fixes https://discord.com/channels/1153767083381903389/1207807557951823892/1208364924963790859
> fix: ensure that only valid ollama params are passed

- examples/custom-prompt-function/promptfooconfig.yaml
- src/prompts.ts
> fix: improve escaping for python prompt shell

- src/web/nextui/src/app/eval/ResultsView.css
- src/web/nextui/src/app/eval/ResultsView.tsx
> feat(webui): Display test suite description

- site/docs/providers/huggingface.md
- src/providers/huggingface.ts
> feat(huggingface): support `apiKey` config param

- src/providers/ollama.ts
> fix(ollama): dont send invalid options for `OllamaChatProvider`

- src/providers/huggingface.ts
> fix(huggingface): do not pass through non-hf parameters

- src/evaluator.ts
- test/evaluator.test.ts
> fix: json and yaml vars files

- examples/python-provider/promptfooconfig.yaml
- examples/python-provider/provider.py
- site/docs/providers/python.md
- src/providers/pythonCompletion.ts
- src/python/wrapper.ts
> fix(python): deserialize objects from json

- src/providers/pythonCompletion.ts
> fix: python provider handles relative script paths correctly

- src/util.ts
- src/web/nextui/src/app/eval/ResultsView.css
- src/web/nextui/src/app/eval/ResultsView.tsx
- src/web/server.ts
Users can edit eval name in UI
Closes #514
> feat(webui): ability to change eval name

- src/providers.ts
- src/providers/anthropic.ts
Update Anthropic to have behavior similar to OpenAI. Related to #534
> fix(anthropic): wrap text if prompt supplied as json

- Dockerfile
- site/docs/usage/sharing.md
- src/types.ts
- src/web/nextui/src/app/api/eval/job/[id]/route.ts
- src/web/nextui/src/app/api/eval/job/evalJobsStore.ts
- src/web/nextui/src/app/api/eval/job/route.ts
- src/web/nextui/src/app/setup/RunTestSuiteButton.tsx
- src/web/nextui/src/database.ts
- src/web/server.ts
> feat(self-host): run evals via web ui

- site/docs/providers/anthropic.md
- src/providers/anthropic.ts
This PR adds support for the new Anthropic model Claude 3 Haiku.
- https://www.anthropic.com/news/claude-3-haiku
- https://docs.anthropic.com/claude/reference/messages_post
> Add support for Claude 3 Haiku

- src/providers/azureopenai.ts
add tools and tool_choice config parameters to azure openai provider
Tested and working!
https://github.com/promptfoo/promptfoo/issues/549
> add tools and tool_choice config parameters to azure openai provider

- src/assertions.ts
> fix: validate custom js function return values

- site/docs/configuration/parameters.md
- src/csv.ts
> feat(csv): add support for `__description` field

- src/providers/azureopenai.ts
> fix(azureopenai): add support for `max_tokens` and `seed`

- README.md
- drizzle.config.ts
- drizzle/0001_wide_calypso.sql
- drizzle/meta/0001_snapshot.json
- drizzle/meta/_journal.json
- src/database.ts
- src/util.ts
- src/web/nextui/src/app/datasets/Datasets.tsx
- src/web/nextui/src/app/prompts/Prompts.tsx
Minor cleanup and fixes after #558
> chore: db migration and cleanup

- Dockerfile
- src/migrate.ts
- src/share.ts
- src/web/nextui/next.config.js
- src/web/nextui/package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/api/eval/[id]/route.ts
- src/web/nextui/src/app/api/eval/route.ts
> fix(selfhost): handle sqlite db in docker image and build

- site/docs/usage/command-line.md
- src/assertions.ts
- src/web/nextui/package-lock.json
For now, defaults to 3 and is controlled by envar `PROMPTFOO_ASSERTIONS_MAX_CONCURRENCY`
> feat: run assertions in parallel

- package-lock.json
- package.json
- site/docs/providers/vertex.md
- src/providers/vertex.ts
- src/providers/vertexUtil.ts
> feat(vertexai): use gcloud application default credentials

- examples/standalone-assertions/README.md
- examples/standalone-assertions/outputs-with-tags.json
- site/docs/configuration/expected-outputs/index.md
- src/main.ts
> feat: ability to set tags on standalone assertion llm outputs

- examples/amazon-bedrock/promptfooconfig.claude.yaml
- examples/amazon-bedrock/promptfooconfig.titan-text.yaml
- site/docs/providers/aws-bedrock.md
- src/providers.ts
- src/providers/anthropic.ts
- src/providers/bedrock.ts
> feat: add support for claude3 on bedrock

- src/providers/vertex.ts
> fix: gemini generationConfig and safetySettings

- src/main.ts
CLI will now watch for changes in providers and vars prefixed with `file://`
> feat: cli watch for vars and providers

- src/providers.ts
- src/providers/bedrock.ts
> fix: bedrock model parsing

- src/evaluator.ts
Evals have always run concurrently, let's make it more obvious to the user.
> feat: display progress bar for each parallel execution

- src/web/nextui/src/app/eval/DownloadMenu.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
> feat(webui): download button

- src/web/nextui/src/app/api/datasets/route.ts
- src/web/nextui/src/app/api/prompts/route.ts
> fix(selfhost): add support for prompts and datasets api endpoints

- examples/vars-referencing-vars/README.md
- examples/vars-referencing-vars/promptfooconfig.yaml
- site/docs/configuration/guide.md
- src/evaluator.ts
- test/evaluator.test.ts
This makes it easier to compose variables.  For example:
```yaml
prompts:
- "Write a {{sentence}}"
tests:
- vars:
sentence: 'tweet about {{topic}}'
topic: 'bananas'
```
> feat: ability to reference vars from other vars

- src/assertions.ts
> fix: handling for nonscript assertion files

- src/evaluator.ts
- test/evaluator.test.ts
Also put a max # iterations on var resolution.
> fix: downgrade var resolution failure to warning

- src/web/nextui/src/app/setup/YamlEditor.tsx
- src/web/nextui/src/state/evalConfig.ts
> fix(webui): ability to save defaultTest and evaluateOptions in yaml editor

- src/assertions.ts
- src/cliState.ts
- src/evaluator.ts
- src/main.ts
- src/types.ts
- src/util.ts
- test/assertions.test.ts
> fix: assertion files use relative path

- src/web/nextui/src/app/eval/ResultsTable.tsx
> feat(webui): add pagination

- src/web/nextui/src/app/eval/ResultsTable.tsx
> fix(webui): handle invalid search regexes

- src/assertions.ts
- test/assertions.test.ts
Discussion: https://discord.com/channels/1153767083381903389/1228267218836394015
> fix: support relative filepaths for non-code assert values

- examples/node-package/index.js
- examples/node-package/output.json
- examples/node-package/prompt.txt
- site/docs/configuration/reference.md
- site/docs/usage/node-package.md
- src/index.ts
- src/types.ts
> fix: node library supports prompt files

- src/assertions.ts
- src/external/ragas.ts
- src/matchers.ts
> Fixing bugs in `Answer-relevance` calculation

- src/web/nextui/src/app/eval/ResultsTable.tsx
> chore(webui): allow configuration of results per page

- site/docs/providers/ollama.md
Ollama now supports llama3 - https://ollama.com/blog/llama3
> [Docs] Add llama3 example to ollama docs

- examples/dbrx-benchmark/promptfooconfig.yaml
- site/docs/providers/openrouter.md
- src/providers.ts
- test/providers.test.ts
> feat: first-class support for openrouter

- src/cache.ts
- test/cache.test.ts
This fixes an issue I noticed whereby the cached token counts didn't seem to be right. I tracked it down to concurrent requests to the cache triggering multiple underlying fetches. Swapping over to using the `cache.wrap` method provided by `cache-manager` (for exactly this use case) fixes the issue.
The implementation is a little convoluted due to maintaining the cached value type and existing logging behaviour. My assumption was that this would be the preference but I'm happy to change this if preferred.
> Fix concurrent cache request behaviour

- package-lock.json
- package.json
- site/docs/integrations/langfuse.md
- src/evaluator.ts
- src/integrations/langfuse.ts
- src/prompts.ts
Hi ian, this pull request is for integration with Langfuse. Please help take a look
> feat: Intergration with Langfuse

- src/providers/vertex.ts
Context: https://discord.com/channels/1153767083381903389/1233068000664485968
> fix(vertex/gemini): support nested generationConfig

- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/TableCommentDialog.tsx
Allows for multiline commenting
The LLM output is shown with a text box below for commenting
> feat(webui): improved comment dialog

- src/cache.ts
Context https://discord.com/channels/1153767083381903389/1232403291997081610
> fix: `getCache` should return a memory store when disk caching is disabled

- src/web/nextui/src/app/eval/ResultsTable.tsx
> chore(webui): always show provider in header

- src/python/wrapper.ts
> fix: include python tracebacks in python errors

- src/main.ts
- src/types.ts
> fix: eval --first-n arg

- src/evaluator.ts
- src/types.ts
> chore: include logger and cache utils in javascript provider context

- site/docs/usage/command-line.md
- src/commands/export.ts
- src/commands/import.ts
- src/main.ts
Reads eval records to/from JSON
> feat: `promptfoo import` and `promptfoo export` commands

- src/evaluator.ts
- src/providers/pythonCompletion.ts
- src/providers/scriptCompletion.ts
- src/python/wrapper.ts
- src/util.ts
- test/prompts.test.ts
> fix: do not serialize js objects to non-js providers

- src/assertions.ts
- test/assertions.test.ts
Fix bug when resolving the assertion file path :)
> Resolve JS assertion paths relative to configuration file

- src/assertions.ts
> feat: add comma-delimited string support for array-type assertion values

- src/assertions.ts
- src/types.ts
> fix: improve GradingResult validation

- src/web/nextui/src/app/eval/ResultsTable.tsx
> chore(webui): display prompt and completion tokens

- src/providers/openai.ts
- src/util.ts
Some OpenAI-like providers, such as groq, add additional debugging keys
https://discordapp.com/channels/1153767083381903389/1240324512868995204
> chore: include full error response in openai errors

- src/assertions.ts
> chore: add logprobs to assertion context

- site/docs/configuration/reference.md
- src/evaluator.ts
- src/types.ts
- src/util.ts
- test/commands/eval/filterFailingTests.test.ts
- test/util.test.ts
> chore: add timestamp to EvaluateSummary

- src/web/nextui/src/app/eval/ResultsTable.tsx
Context: https://discordapp.com/channels/1153767083381903389/1204780043436560394/1241137132450615376
> fix: render markdown in variables too

- examples/google-vertex/promptfooconfig.yaml
- src/providers/vertex.ts
Use default application credentials instead
#787
> fix(vertex): remove leftover dependency on apiKey

- src/providers/huggingface.ts
> fix: huggingface api key handling

- README.md
I was building the project locally and noticed a small typo!
> Fix typo in local build command

- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
Lets you click an image to enlarge it.
> feat(webui): Add image viewer

- README.md
- examples/moderation/README.md
- examples/moderation/promptfooconfig.yaml
- site/docs/configuration/expected-outputs/model-graded.md
- site/docs/configuration/expected-outputs/moderation.md
- src/assertions.ts
- src/matchers.ts
- src/providers.ts
- src/providers/defaults.ts
- src/providers/openai.ts
- src/providers/replicate.ts
- src/redteam/getHarmfulTests.ts
- src/redteam/index.ts
- src/types.ts
- src/web/nextui/src/app/setup/AssertsForm.tsx
Adds support for moderation via OpenAI's moderation API and Meta's LlamaGuard via Replicate
> feat: `moderation` assert type

- src/web/nextui/src/app/setup/RunTestSuiteButton.tsx
- src/web/nextui/src/state/evalConfig.ts
> The values of defaultTest and evaluateOptions are not set when editing the eval yaml file.

- src/providers/vertex.ts
> feat(vertex/gemini): add support for toolConfig and systemInstruction

- src/main.ts
Closes https://github.com/promptfoo/promptfoo/issues/835
> Help description of default `--output`

- Dockerfile
- package.json
- src/web/nextui/next.config.js
Related to https://github.com/promptfoo/promptfoo/pull/836
> fix: docker build and prepublish script

- src/providers/pythonCompletion.ts
Adds support for `call_embedding_api` and `call_classification_api` functions in python providers
> feat: add support for python embedding and classification providers

- src/web/nextui/src/app/eval/ResultsTable.tsx
I think this closes: https://github.com/promptfoo/promptfoo/issues/871
I haven't been able to test these changes locally - @typpo do you have any suggestions? Do I write my own custom provider with markdown hardcoded in the response? Where would I need to put the provider file in this project's directory? Any info appreciated, so I can better test these changes without bugging you 😅
> Render multiple result images with markdown, if markdown contains multiple images

- examples/custom-provider/promptfooconfig.yaml
- examples/node-package/full-eval.js
- examples/node-package/output.json
- examples/test-markdown/README.md
- examples/test-markdown/promptfooconfig.yaml
- src/providers.ts
- src/table.ts
- src/types.ts
Also always shows the provider in the CLI table, consistent with webui.
> fix: show labels for custom provider

- src/main.ts
> fix: migrate database before writing results

- src/main.ts
- src/web/server.ts
> feat(webui): Ability to suppress browser open on `promptfoo view`

- site/docs/configuration/parameters.md
- src/csv.ts
Feature requests here: https://discord.com/channels/1153767083381903389/1179011200143597669/1248207303338098712
> feat: ability to set test case metric from csv

- src/web/nextui/src/app/eval/ResultsTable.tsx
Display the number of passes and failures if there are multiple tests
> feat(webui): Show the number of passes and failures

- src/providers/vertex.ts
Also removes the "unknown model" warning.
> chore: add more gemini models

- examples/assistant-cli/output.html
- examples/js-config/output.html
- examples/multishot/output.html
- examples/simple-cli/output.html
- examples/simple-csv/output.html
- package-lock.json
- package.json
- src/assertions.ts
- src/evaluator.ts
- src/main.ts
- src/providers/huggingface.ts
- src/providers/ollama.ts
- src/providers/pythonCompletion.ts
- src/providers/scriptCompletion.ts
- src/tableOutput.html
This PR updates the Prettier dependency to version 3.3.1 and includes minor formatting adjustments for consistency and readability.
> chore: update to prettier 3

- site/docs/providers/vertex.md
- src/providers/vertex.ts
Related to https://github.com/promptfoo/promptfoo/issues/837
> fix(vertex): support var templating in system instruction

- src/types.ts
- src/web/nextui/src/app/eval/ResultsTable.tsx
Shows manual grading results in the assertions view
> feat(webui): show manual grading record in test details view

- .github/workflows/main.yml
- package.json
- src/index.ts
- src/web/nextui/build.sh
- src/web/nextui/src/app/api/eval/[id]/route.ts
- src/web/nextui/src/app/api/eval/job/[id]/route.ts
- src/web/nextui/src/app/api/eval/job/route.ts
- src/web/nextui/src/app/api/results/[filename]/route.ts
after messing around, I think it's this:
https://github.com/nodejs/node/issues/51766
This PR includes some other cleanups that were helpful when debugging and ruling out issues
> fix: windows node 22 flake

- src/providers/bedrock.ts
- test/providers.bedrock.test.ts
> fix(bedrock): default value for configs

- examples/custom-provider/customProvider.js
- site/docs/providers/custom-api.md
- site/docs/providers/http.md
- src/index.ts
> feat: export `promptfoo.cache` to node package

- src/providers/bedrock.ts
> fix(bedrock): support cohere embeddings

- examples/voyage-embeddings/README.md
- examples/voyage-embeddings/promptfooconfig.yaml
- site/docs/providers/voyage.md
- src/providers.ts
- src/providers/voyage.ts
- test/providers.test.ts
This is Anthropic's recommended embeddings provider https://docs.anthropic.com/en/docs/embeddings
> feat: add Voyage AI embeddings provider

- site/docs/installation.md
- site/docs/integrations/github-action.md
Corrects location of github action and spelling of github
> chore(docs): update installation and GitHub Actions guides

- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsViewSettingsModal.tsx
- src/web/nextui/src/app/eval/store.ts
Toggle for hiding pass/fail on each table cell
> feat(webui): show pass/fail toggle

- site/docs/guides/llm-redteaming.md
- src/redteam/getPoliticalStatementsTests.ts
- src/redteam/index.ts
Test whether your LLM app shares political opinions on policies or people
```
promptfoo generate redteam --plugins political
promptfoo eval
```
> feat(redteam): political statements

- src/web/nextui/src/app/report/Report.tsx
- src/web/nextui/src/app/report/TestSuites.css
- src/web/nextui/src/app/report/TestSuites.tsx
- src/web/nextui/src/app/report/constants.ts
> feat(redteam): indicate performance with moderation filter

- src/redteam/getUnintendedContractTests.ts
- src/redteam/index.ts
In my testing, contracts were a bit too close to hallucinations.  Pared down examples to ones with stronger potential consequences for a business.
> fix(redteam): more aggressive contract testing

- eslint.config.mjs
- package-lock.json
- package.json
- src/assertions.ts
- src/database.ts
- src/providers/defaults.ts
- src/providers/openaiUtil.ts
- src/web/nextui/src/app/api/eval/[id]/route.ts
- src/web/nextui/src/app/api/progress/route.ts
- src/web/nextui/src/app/auth/callback/route.ts
- src/web/nextui/src/app/eval/GenerateTestCases.tsx
- src/web/nextui/src/app/eval/ResultsCharts.tsx
- src/web/nextui/src/app/eval/[id]/page.tsx
- src/web/nextui/src/app/eval/types.ts
- src/web/nextui/src/app/setup/RunTestSuiteButton.tsx
- src/web/nextui/src/database.ts
- src/web/nextui/src/supabase-client.tsx
- src/web/server.ts
- test/assertions/AssertionResult.test.ts
- test/commands/eval/filterFailingTests.test.ts
- test/commands/eval/filterTests.test.ts
- test/providers.vertex.test.ts
This PR introduces [`eslint-plugin-unused-imports`](https://www.npmjs.com/package/eslint-plugin-unused-imports) to detect and remove unused imports. Additionally, it removes various unused imports across the project.
- **New Dependency:** Added `eslint-plugin-unused-imports` to the project.
- **ESLint Configuration:** Updated `eslint.config.mjs` to configure the plugin and enforce the `no-unused-imports` rule as an error.
- **Code Cleanup:** Removed unused imports from various files throughout the project.
> feat: add eslint-plugin-unused-imports and remove unused imports

- site/docs/usage/command-line.md
> Add CLI delete command to docs

- src/providers.ts
- test/providers.test.ts
> fix: handle absolute paths for js providers

- src/redteam/eval/excessive-agency/llm_rubric-20240617.json
- src/redteam/eval/excessive-agency/llm_rubric-20240618.json
- src/redteam/eval/excessive-agency/promptfooconfig.yaml
- src/redteam/eval/overreliance/llm_rubric-20240617.json
- src/redteam/eval/overreliance/llm_rubric-20240618.json
- src/redteam/eval/overreliance/promptfooconfig.yaml
- src/redteam/getOverconfidenceTests.ts
- src/redteam/getUnderconfidenceTests.ts
Improves false positive rates and introduces tiny evals
> fix(redteam): reduce overreliance, excessive-agency false positive rates

- README.md
- site/docs/configuration/expected-outputs/deterministic.md
- src/assertions.ts
- src/types.ts
- src/web/nextui/src/app/setup/AssertsForm.tsx
- test/assertions.test.ts
Builds on the recent is-sql addition #926
> feat: contains-sql assert

- jest.config.ts
- jest.setup.js
- package-lock.json
- package.json
- test/providers.anthropic.test.ts
And remove Anthropic tests that were hitting the API
> test: block network calls in tests

- src/onboarding.ts
- src/providers/anthropic.ts
And include it in the default Anthropic onboarding flow
> chore: add Claude 3.5 sonnet pricing

- src/evaluator.ts
> fix: include error text in all cases

- package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/DownloadMenu.tsx
Adds a "Download as CSV" option to the Eval Actions > Download dialog.
> feat(webui): download as CSV

- package-lock.json
- package.json
- src/googleSheets.ts
> chore: switch to smaller googleapis dependency

- src/evaluator.ts
- src/redteam/iterative.ts
- src/types.ts
- src/web/nextui/src/app/eval/EvalOutputCell.tsx
- src/web/nextui/src/app/eval/EvalOutputPromptDialog.tsx
Adds a "modified prompt" section in the detail modal
> feat(redteam): Expose modified prompt for iterative jailbreaks

- src/providers/http.ts
- test/providers.http.test.ts
> fix: http provider returns the correct response format

- src/constants.ts
- src/table.ts
- src/updates.ts
- src/util.ts
> fix: handle when stdout columns are not set

- site/docs/providers/anthropic.md
Removed claude-3.5-haiku - as it's not released yet.
> docs: update anthropic.md

- src/testCases.ts
Yaml test files that are included aren't dereferenced, only the 'main' promptfooconfig.yaml is dereferenced.  
```yaml
prompts: [prompt1.txt]
providers: [openai:gpt-3.5-turbo]
tests:
- tests.yaml
```
tests.yaml:
```yaml
- vars:
input: Hello world
assert:
- $ref: 'asserts.yaml#/assertionTemplates/noAIreference'
- $ref: 'asserts.yaml#/assertionTemplates/startsUpperCase'
```
asserts.yaml:
```yaml
assertionTemplates:
noAIreference:
- type: llm-rubric
value: does not describe self as an AI, model, or chatbot
startsUpperCase:
- type: javascript
value: output[0] === output[0].toUpperCase()
```
Note you can't define yaml snippets that are to be referenced in promptfoo test files, as a test file is expected to define a list of test cases. Therefor the yaml …
> feat: dereference promptfoo test files

- examples/simple-cli/promptfooconfig.yaml
- package-lock.json
- src/web/nextui/package.json
- src/web/nextui/src/app/eval/EvalOutputCell.tsx
- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
> feat(webui): Add support for markdown tables and other extras

- src/testCases.ts
- test/testCases.test.ts
I've seen this come up several times, including in #1040
> fix: handle imported single test case

- examples/amazon-bedrock/promptfooconfig.llama.yaml
- src/providers/bedrock.ts
- test/providers.bedrock.test.ts
Related issue: https://github.com/promptfoo/promptfoo/issues/912
> feat: prompt syntax for llama3

- src/providers.ts
- test/providers.test.ts
> fix: handle replicate ids without version

- src/web/nextui/src/app/setup/RunTestSuiteButton.tsx
- src/web/nextui/src/app/setup/YamlEditor.tsx
- src/web/nextui/src/state/evalConfig.ts
Addresses #1068: This change ensures that scenarios can be configured in the YAML editor in the webui.
> feat(webui): add scenarios to test suite configuration in yaml editor

- src/assertions.ts
> fix: remove test mutation for classifer and select-best assertion types

- package-lock.json
- package.json
- site/docs/providers/openai.md
- src/providers/openai.ts
> feat(openai): support for attachments for openai assistants

- src/redteam/getHarmfulTests.ts
- src/redteam/getUnderconfidenceTests.ts
- src/redteam/index.ts
- src/redteam/iterative.ts
- src/web/nextui/src/app/eval/EvalOutputPromptDialog.tsx
Also modifies the attacker prompt for iterative jailbreaks
> feat(redteam): `extra-jailbreak` plugin that applies jailbreak to all probes

- src/web/nextui/src/app/eval/ResultsTable.css
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
Very small.  Ditches the drop shadow/thick borders and makes use of full width without margin on the sides of the table.
Before
After
> chore(webui): small changes to styling

- src/web/nextui/src/app/eval/ResultsView.tsx
> fix(webui): Ability to toggle visibility of description column

- src/evaluator.ts
> fix: put provider in outer loop to reduce model swap

- src/redteam/constants.ts
- src/redteam/index.ts
- src/redteam/methods/injections.ts
- src/redteam/methods/iterative.ts
- src/redteam/plugins/harmful.ts
- Add new constant LLAMA_GUARD_REPLICATE_PROVIDER
- Refactor addInjections and addIterativeJailbreaks methods into separate files
- Simplify methods by removing unused parameters
> refactor(redteam): refactor and optimize injection and iterative methods

- package-lock.json
- site/package.json
- src/web/nextui/package.json
Updates dependencies used on our docs website and mui dependencies in the webui app. There are no breaking API changes.
> chore: update documentation and mui dependencies

- src/redteam/index.ts
otherwise the message gets mangled by the progress bar
> fix: move multiple variables warning to before progress bar

- src/providers.ts
These files moved during a structural refactor but I did not update the dynamic import paths. This fixes them.
> fix(redteam): fix dynamic import paths

- src/providers/mistral.ts
Changelog:
- Add support for Codestral-mamba
Note: The pricing is not public yet, I'll update it once it's known.
> chore(mistral): add codestral-mamba

- site/docs/providers/manual-input.md
- src/providers.ts
- src/providers/manualInput.ts
Small provider that makes it easy to test some stuff out.  I found it useful to "manually" redteam applications that don't have an accessible API
> feat: manual input provider

- src/redteam/methods/injections.ts
> chore(redteam): another injection

- src/commands/share.ts
> chore: include hostname in share confirmation

- src/web/nextui/src/app/eval/Eval.tsx
- src/web/nextui/src/app/eval/ResultsTable.tsx
- src/web/nextui/src/app/eval/ResultsView.tsx
This resulted in broken behaviors (writing updates/comments, navigating to report) in the default eval view
> fix(webui): eval id not being properly set

- Dockerfile
resolves #1202
The container no longer stays unhealthy.
> fix(Dockerfile): install curl for healthcheck

- package-lock.json
- package.json
- scripts/generateJsonSchema.ts
- site/package.json
- site/src/pages/validator.tsx
- site/static/config-schema.json
- src/types.ts
https://github.com/user-attachments/assets/a7bd3f07-b320-409d-9f84-e3fca7b4e714
> site: yaml/json config validator for promptfoo configs

- src/web/nextui/src/app/components/DarkMode.css
- src/web/nextui/src/app/components/Logo.css
- src/web/nextui/src/app/components/Navigation.css
- src/web/nextui/src/app/components/Navigation.tsx
- src/web/nextui/src/app/components/PageShell.tsx
- src/web/nextui/src/app/datasets/Datasets.tsx
- src/web/nextui/src/app/globals.css
- src/web/nextui/src/app/progress/Progress.tsx
- src/web/nextui/src/app/prompts/Prompts.tsx
- src/web/nextui/src/app/report/Overview.css
- src/web/nextui/src/app/report/Overview.tsx
- src/web/nextui/src/app/report/Report.css
- src/web/nextui/src/app/report/Report.tsx
- src/web/nextui/src/app/report/RiskCard.css
- src/web/nextui/src/app/report/TestSuites.css
- src/web/nextui/src/app/report/TestSuites.tsx
- src/web/nextui/src/app/setup/PromptsSection.tsx
- src/web/nextui/src/app/setup/TestCasesSection.tsx
Bunch of visual bugfixes and improvements, mostly on report view but also on navbar and each of the other pages.
> fix(webui): misc fixes and improvements to webui visuals

- src/testCases.ts
- src/types.ts
- test/__mocks__/tempCustomModule.ts
- test/assertions.test.ts
- test/commands/eval/filterFailingTests.test.ts
- test/config.test.ts
- test/providers.anthropic.test.ts
- test/providers.bedrock.test.ts
- test/providers.pythonCompletion.test.ts
- test/providers.test.ts
- test/providers.vertex.test.ts
- test/pythonWrapper.test.ts
- test/telemetry.test.ts
- test/testCases.test.ts
- test/updates.test.ts
- test/util.test.ts
- tsconfig.json
Resolve TypeScript errors in various test files
> test: improve type safety and resolve TypeScript errors

- src/web/nextui/src/app/report/Report.tsx
- src/web/nextui/src/app/report/ReportSettingsDialogButton.tsx
- src/web/nextui/src/app/report/RiskCard.css
- src/web/nextui/src/app/report/RiskCard.tsx
- src/web/nextui/src/app/report/RiskCategories.tsx
- src/web/nextui/src/app/report/store.ts
Settings button in top right, right now lets you toggle full percentages in risk card
> feat(redteam): settings dialog

- src/providers/vertex.ts
- src/providers/vertexUtil.ts
Improves handling for the safety error that @jamesbraza noticed in #1186
> fix(gemini): improve error handling

- src/redteam/plugins/pii.ts
> fix(redteam): pii false positives

- package-lock.json
- src/redteam/providers/iterativeTree.ts
- src/web/nextui/package.json
- src/web/nextui/src/app/setup/TestCasesSection.tsx
- Improved logging in iterativeTree.ts from warn to debug level
- Refactored TestCasesSection.tsx to ensure type safety when setting test cases
- bump dependencies in nextui
> fix: cleanup logging and fix nextui ts error

- src/web/server.ts
- Add error handling for EADDRINUSE scenario
- Provide informative error message when port is occupied
- Exit process gracefully on server start failure
> chore(webui): handle port already in use error

- src/web/nextui/src/app/setup/ProviderSelector.test.tsx
- src/web/nextui/src/app/setup/ProviderSelector.tsx
- Add comprehensive test suite for ProviderSelector component
- Update list of default providers with latest models
- Remove outdated provider models
> chore(webui): update provider list in ProviderSelector and add tests

- Dockerfile
- src/web/nextui/src/app/api/results/route.ts
- fix setting envars (e.g. `-e OPENAI_API_KEY=xyz`
- fix Eval initial load
- try to play nice with k8s permission restrictions
Related to #1252, #1223
> fix: multiple docker fixes

- src/web/nextui/src/app/eval/CustomMetrics.tsx
Quick and dirty "Show more" button
> feat(webui): hide long metrics lists

- src/web/nextui/src/app/setup/YamlEditor.tsx
This will require absolute paths for the provider, and cannot reference other files (yaml must be self contained)
> feat(webui): add yaml upload button

- site/src/pages/careers.tsx
Add details on including LinkedIn/GitHub profiles and mention preference for contributors
> site(careers): update application instructions and preferences

- src/database/types.ts
- src/types.ts
being consistent with the location of types
```
redteam/types.ts
database/types.ts
types.ts
```
> chore: move types files

- site/docs/configuration/guide.md
- src/providers.ts
- test/providers.test.ts
Supposedly doable back in December https://github.com/promptfoo/promptfoo/issues/349#issuecomment-1862066974
Possibly lost in a refactor 🤔
> fix: support provider json filepath

- src/assertions.ts
- src/evaluator.ts
- src/prompts/constants.ts
- src/prompts/index.ts
- src/util/index.ts
> chore: support ts files for prompts providers and assertions 

- site/docs/providers/custom-api.md
- src/evaluator.ts
- src/evaluatorHelpers.ts
- src/providers.ts
- src/redteam/providers/iterative.ts
- src/redteam/providers/iterativeImage.ts
- src/redteam/providers/iterativeTree.ts
- src/types.ts
- test/evaluator.test.ts
- test/providers.test.ts
- Update CallApiContextParams and CallApiOptionsParams interfaces
- Refactor RedteamIterativeProvider and RedteamImageIterativeProvider
- Add injectVar configuration to RedteamImageIterativeProvider
- Update runRedteamConversation function to use new parameters
- Adjust tests to accommodate changes in provider interfaces
> fix(redteam): improve iterative providers and update provider API interface to pass original prompt (#1293)

- src/web/nextui/src/app/eval/TruncatedText.tsx
> fix(webui): make it easier to select text without toggling cell

- src/redteam/graders/competitors.ts
- src/web/nextui/src/app/report/constants.ts
- Expanded the rubric for CompetitorsGrader with detailed evaluation criteria
> fix(redteam): update CompetitorsGrader rubric

- src/commands/redteam.ts
- Adjust pageSize for plugin and strategy selection to fit screen
- Disable looping in selection menus for better navigation
> fix(redteam): improve plugin and strategy selection UI

- src/web/nextui/src/app/eval/ResultsTable.tsx
in true promptfoo fashion - functional but hideous
> feat(webui): tooltip with provider config on hover

- src/web/nextui/src/app/eval/Eval.tsx
- src/web/nextui/src/app/layout.tsx
- src/web/nextui/src/app/report/Report.tsx
> chore: set page titles

- src/commands/redteam.ts
- Replace single provider selection with multi-select checkbox
- Set openai:gpt-4o-mini as default choice
- Add support for custom provider input
- Update config object to use array of providers
> chore(redteam): allow multiple provider selection

- CITATION.cff
Resolves #1318
In the future we can automate keeping the version and release date current.
> docs: add CITATION.cff file

- src/fetch.ts
- test/assertions.test.ts
Handle standard `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers.
> feat: handle rate limits in generic fetch path

- src/providers/anthropic.ts
- src/providers/azureopenai.ts
- src/providers/bedrock.ts
- src/providers/openai.ts
- src/providers/shared.ts
- test/providers.shared.test.ts
> feat: load provider `tools` and `functions` from external file

- README.md
- site/docs/getting-started.md
- site/docs/installation.md
- Add detailed installation steps to README
- Include npm, Homebrew, and source installation methods
- Add verification step and next steps
- Update installation.md with more comprehensive instructions
- Specify supported operating systems and Node.js version requirement
> docs: expand installation instructions in README and docs

- examples/tool-use/promptfooconfig.yaml
- src/config.ts
- test/config.test.ts
> fix: do not dereference external tool files

- examples/google-sheets/promptfooconfig.yaml
- src/util/index.ts
- test/util.test.ts
> fix: google sheets output

- site/docs/red-team/configuration.md
- src/commands/generate/redteam.ts
- src/redteam/constants.ts
- src/validators/redteam.ts
- src/web/nextui/src/app/report/constants.ts
- test/redteam/validators.test.ts
Now instead of 
```
--add-plugins competitors,rbac
```
You would do
```
--plugins default,competitors,rbac
```
> feat!: add `default` plugin collection and remove --add-plugins

- src/redteam/plugins/base.ts
- src/redteam/plugins/hallucination.ts
- reenable nunjucks strict mode for redteam graders
- fix halluc template
- improve debug/error message
> fix: undefined var in hallucination template

- drizzle.config.ts
- drizzle/0003_lively_naoko.sql
- drizzle/meta/_journal.json
- package.json
- src/database/tables.ts
adds indexes to support all operations in `util`, also fixes some drizzle stuff after drizzle upgrade
> fix: add indexes for sqlite

- src/providers/shared.ts
- test/providers.shared.test.ts
Make it easier to manage more tools (enable/disable them etc).
The heavy lifting work have been done in https://github.com/promptfoo/promptfoo/pull/1342 and this is just adding a feature.
> Support loading tools from multiple files

- src/redteam/constants.ts
- src/redteam/plugins/harmful.ts
- src/redteam/plugins/rbac.ts
- Disable LlamaGuard Privacy 
- Update RBAC grader
- TODO followup: move soft harmful check into grader and ignore AllowedEntities
> fix: reduce rbac and moderation false positives

- src/commands/generate/redteam.ts
- src/redteam/constants.ts
- src/types/redteam.ts
- src/validators/redteam.ts
- test/redteam/validators.test.ts
matches https://github.com/promptfoo/promptfoo/pull/1369
> feat: add `default` strategy and remove `--add-strategies`

- src/providers.ts
> feat: assume unrecognized openai models are chat models

- site/docs/red-team/configuration.md
- site/docs/red-team/llm-vulnerability-types.md
- site/docs/red-team/owasp-llm-top-10.md
- src/redteam/constants.ts
- src/redteam/graders.ts
- src/redteam/plugins/bfla.ts
- src/redteam/plugins/bola.ts
- src/redteam/plugins/index.ts
- src/web/nextui/src/app/report/constants.ts
Add red teaming support for Broken Function Level Authorization and Broken Object Level Authorization - OWASP Top 10 API Security Risks https://owasp.org/API-Security/editions/2023/en/0x11-t10/
> feat: bfla and bofa plugins

- src/providers/promptfoo.ts
- src/redteam/plugins/harmful.ts
Also don't do them in parallel because we are getting rate limited :(
> fix: handle retries for harmful generations

- src/web/nextui/src/app/report/Report.tsx
> feat(webui): ability to choose prompt/provider column in report view

- src/util/index.ts
> fix: dont load all results into memory in `listPreviousResults`

- src/assertions.ts
- test/is-sql-tests/node-sql-parser.test.ts
> fix: databaseType not database

- src/commands/generate/redteam.ts
- test/commands/generate/redteam.test.ts
- Update doGenerateRedteam to set basePath in cliState
- Add test suite for redteam generation command
> feat(redteam): add base path to CLI state for redteam generate 

- src/commands/redteam.ts
- Ensure we have at least one injectable variable in the prompt
- Re-use the same prompt for the promptExtraction plugin and template
> fix: Prompt setup during redteam generation

- src/commands/cache.ts
I was clearing gigabytes of data from my cache and that got me thinking...
> chore: clear cache status messages

- src/commands/redteam.ts
Adds descriptions to generated configs
> chore: add plugin/strategy descriptions

- src/redteam/plugins/pii.ts
PII plugin was full of false positives just reflecting back names from the user input
> fix: reduce pii false positives

- src/redteam/index.ts
- test/redteam/index.test.ts
displays what progress bar is working on, waits until plugin has finished to increment, waits until strategies have finished to stop.
> fix: redteam progress bar

- site/docs/configuration/guide.md
- src/redteam/util.ts
- src/util/templates.ts
- test/util.templates.test.ts
> feat: global `env` var in templates

- site/docs/red-team/plugins/indirect-prompt-injection.md
- src/redteam/plugins/index.ts
- src/redteam/plugins/indirectPromptInjection.ts
the variable isn't used, so i am removing it!
> fix: remove indirect prompt injection `config.systemPrompt` dependency

- src/redteam/index.ts
- src/redteam/plugins/custom.ts
- src/redteam/strategies/index.ts
- src/types/redteam.ts
- test/redteam/validators.test.ts
small DRY types change, this also caught a bug in CustomPlugin
> chore: simplify redteam types

- src/redteam/providers/crescendo/index.ts
- src/redteam/providers/iterative.ts
- src/redteam/providers/iterativeImage.ts
- src/redteam/providers/iterativeTree.ts
- src/util/json.ts
> fix: improve strategy json parsing

- src/commands/eval.ts
- src/config.ts
- src/redteam/strategies/multilingual.ts
- src/types/providers.ts
> fix: multilingual strategy should use redteam provider

- src/assertions.ts
- test/assertions.test.ts
> chore: add info to contains-all and icontains-all error

- site/docs/red-team/configuration.md
- src/redteam/constants.ts
- src/web/nextui/src/app/report/constants.ts
https://atlas.mitre.org/techniques
> feat: add mitre atlas plugin aliases

- README.md
- package-lock.json
- package.json
- site/blog/llm-agent-red-teaming-plugins.md
- site/blog/promptfoo-enterprise.md
- site/docs/getting-started.md
- site/docs/guides/mixtral-vs-gpt.md
- site/docs/guides/qwen-benchmark.md
- site/docs/red-team/agents.md
- site/docs/red-team/llm-vulnerability-types.md
- site/docs/red-team/plugins/prompt-extraction.md
- site/docusaurus.config.js
- site/package.json
- site/src/pages/llm-vulnerability-scanner.tsx
- src/web/nextui/package.json
- Fix broken links in LLM vulnerability documentation
- Update express and related dependencies
- Upgrade prism-react-renderer and typescript
- Add onBrokenAnchors warning in docusaurus config
- Adjust formatting in vulnerability types table
> docs: fix broken anchor links 

- site/docs/usage/self-hosting.md
- src/constants.ts
- src/share.ts
> fix: share link when self-hosting

- examples/function-tools-callback/README.md
- examples/function-tools-callback/promptfooconfig.js
- src/providers/openai.ts
- test/providers.test.ts
- Update OpenAI provider to process tool_calls correctly
- Add tests for functionToolCallbacks feature
- Add support for multiple function calls
- Implement error handling in function callbacks
- Include example configuration for function tool callbacks
> fix(providers): openai function tool callbacks handling

- src/providers/azureopenai.ts
- test/providers.azure.test.ts
Remove duplicate protocol prefixes and trailing slashes. Resolves https://discord.com/channels/1153767083381903389/1284436871409307699/1284436871409307699
> chore(providers): improve API URL formatting for Azure OpenAI provider

- src/util/index.ts
- test/util.test.ts
Context https://github.com/promptfoo/promptfoo/issues/1685
> feat(util): add nunjucks template support for file path

- src/config.ts
- test/config.test.ts
This reverts commit 92ee2bbb04115586c5f1c98161ee4e4ea6a48987.
relates to https://github.com/promptfoo/promptfoo/issues/1720 https://github.com/promptfoo/promptfoo/issues/1717 https://github.com/promptfoo/promptfoo/issues/1716 
CC @albertlieyingadrian
> revert: fix(config): resolve prompt file bug

- src/prompts/index.ts
- test/prompts.test.ts
To handle the bug in this PR https://github.com/promptfoo/promptfoo/pull/1722#issue-2537893705
Context:
relates to https://github.com/promptfoo/promptfoo/issues/1720 https://github.com/promptfoo/promptfoo/issues/1717 https://github.com/promptfoo/promptfoo/issues/1716
> bugfix(prompts): add handling for function prompt

- src/share.ts
Context: https://discord.com/channels/1153767083381903389/1286493461544960134
> fix: catch errors when creating share url

- src/commands/eval.ts
> fix: output path when PROMPTFOO_LIGHTWEIGHT_RESULTS is set

- src/assertions.ts
- src/redteam/plugins/base.ts
- src/redteam/plugins/indirectPromptInjection.ts
- src/types/index.ts
POC for assertions to return suggestions
> feat: suggestions

- src/providers.ts
- test/providers.test.ts
> chore(providers): add templating support for provider URLs

- src/testCases.ts
- src/util/json.ts
- test/assertions.test.ts
- test/util.json.test.ts
This also fixes regular dataset generation
> fix: json parser handling for many braces

- site/docs/usage/command-line.md
- src/commands/eval.ts
- Group eval command options into logical categories
- Add help menu to eval command
> refactor(eval): reorganize and improve eval command options

- site/docs/providers/go.md
- site/docs/providers/index.md
- src/providers.ts
Adds a provider index page instead of the docusaurus-generated one. Also documents the go provider
> docs: provider index

- src/redteam/commands/run.ts
- tsconfig.json
Paths aren't compiling correctly and it's not a priority right now so I'm removing them from tsconfig
> fix: remove paths until compilation works correctly

- .github/workflows/main.yml
- src/python/pythonUtils.ts
- test/python/integration.test.ts
- test/python/pythonUtils.test.ts
- Implements stdout and stderr logging during Python script execution
> feat: add real-time logging for Python script execution

- src/app/src/pages/report/components/constants.ts
- src/redteam/constants.ts
- src/redteam/graders.ts
- src/redteam/plugins/index.ts
- src/redteam/plugins/religion.ts
make sure these AIs aren't riling people up with religious statements
> feat: add religion plugin

- src/providers/fal.ts
This PR adds config per prompt for the fal provider, as described here: https://www.promptfoo.dev/docs/configuration/parameters/#prompt-configs
> feat(provider-fal): allow prompt config overrides

- site/blog/llm-agent-red-teaming-plugins.md
- site/blog/promptfoo-enterprise.md
- site/blog/red-teaming-prompt-airlines.md
- site/src/components/Blog/BlogPostCard.module.css
- site/src/components/Blog/BlogPostCard.tsx
- site/src/components/Blog/BlogPostGrid.module.css
- site/src/components/Blog/BlogPostGrid.tsx
- site/src/components/Blog/FeaturedBlogPost.module.css
- site/src/components/Blog/FeaturedBlogPost.tsx
- site/src/theme/BlogListPage/StructuredData/index.tsx
- site/src/theme/BlogListPage/index.tsx
- site/src/theme/BlogListPage/styles.module.css
- site/static/config-schema.json
> site: custom blog index page

- src/commands/import.ts
- src/database/tables.ts
- src/models/eval.ts
- src/util/index.ts
- test/factories/evalFactory.ts
Just a good practice to name tables tables.
> chore: rename tables

- site/docs/contributing.md
inspired by https://github.com/promptfoo/promptfoo/pull/1830
> docs(contributing): expand guide for adding new providers

- src/app/vite.config.ts
fix for https://github.com/promptfoo/promptfoo/issues/1611
> fix: support relative paths

- src/util/convertEvalResultsToTable.ts
Fix for: https://github.com/promptfoo/promptfoo/issues/1832
> fix: Prompt ordering on tables

- src/share.ts
Add auth for cloud sharing and use new format if available
> chore: Cloud sharing with new format

- site/docs/red-team/configuration.md
- src/redteam/index.ts
- src/redteam/plugins/custom.ts
- test/redteam/plugins/custom.test.ts
- Add CustomPluginDefinitionSchema for validating plugin definitions
- Implement loadCustomPluginDefinition function to load and validate custom plugins
- Update CustomPlugin class to use loadCustomPluginDefinition
- Add error handling for custom plugin generation in synthesize function
- Update custom plugin example in documentation
- Add comprehensive test suite for CustomPlugin and loadCustomPluginDefinition
> chore(redteam): improve custom plugin definition and validation

- src/assertions.ts
- test/assertions.test.ts
Fixes https://github.com/promptfoo/promptfoo/issues/1867 per conversation there
I ran the tests and fixed test failures related to that file (which seemed reasonable since we switched the order of the output)
> fix: equality failure message

- site/static/config-schema.json
- src/commands/eval.ts
- src/types/index.ts
> chore: add `--filter-targets` alias

- src/app/src/pages/report/components/Report.tsx
- src/app/src/pages/report/components/ToolsDialog.tsx
Works well for inline tools - tools referenced by external file show up as 1 tool
> chore: show tools in report view

- src/matchers.ts
- src/remoteGrading.ts
- test/matchers.test.ts
> fix: disable remote grading with rubric prompt override

- src/app/src/pages/redteam/setup/components/Targets.tsx
- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
- src/cache.ts
- src/providers/http.ts
- src/server/routes/providers.ts
- src/server/server.ts
- src/types/providers.ts
- test/providers.http.test.ts
- test/server/providers.test.ts
Takes an HTTP provider config and tests it out. Uses an LLM agent hosted on promptfoo cloud to validate the results.
> feat: Redteam http target tester

- src/util/index.ts
- test/models/eval.test.ts
- test/util.deleteAll.test.ts
Fix for: https://github.com/promptfoo/promptfoo/issues/1862#issuecomment-2414669854
Added tests to make sure we stop breaking delete
> fix: Delete all evals broken

- examples/google-aistudio-gemini/promptfooconfig.yaml
- src/providers/vertexUtil.ts
> fix: gemini chat formatting

- src/models/eval.ts
Eval Results needs prompts to be created before saving
> fix: sharing to hosted

- .github/workflows/docker.yml
- .github/workflows/files/promptfooconfig.yaml
- .github/workflows/main.yml
I keep breaking hosted container shares
https://github.com/promptfoo/promptfoo/actions/runs/11377808334/job/31652565359
> chore: Test eval share for hosted container

- drizzle/0008_broad_boomer.sql
- drizzle/meta/0008_snapshot.json
- drizzle/meta/_journal.json
- src/database/tables.ts
- src/models/provider.ts
Providers will be identified uniquely by their label if it exists or the id if it does not
> chore: update providers to id by id or label

- src/commands/eval.ts
- src/util/config/default.ts
- Clears the config cache
- Reloads default config
Related to #1918 and #1919
> fix: cli properly watches all types of configs

- site/docs/providers/github.md
- src/providers.ts
- test/providers.test.ts
https://discord.com/channels/1153767083381903389/1296228965517885471
https://github.com/marketplace/models
> feat: add support for `github` provider

- src/providers/vertex.ts
- src/providers/vertexUtil.ts
- test/providers.vertex.test.ts
handles case where format does not need to be coerced
> fix(providers): improve Gemini format coercion and add tests

- site/docs/providers/togetherai.md
- src/providers.ts
- src/providers/openai.ts
- src/providers/togetherai.ts
- test/providers.test.ts
- test/providers.togetherai.test.ts
- Revise togetherai.md documentation for clarity and consistency
- Add createTogetherAiProvider function in new togetherai.ts file
- Update providers.ts to use createTogetherAiProvider for TogetherAI
- Adjust openai.ts to handle TogetherAI returning an empty tool_calls array on every invocation
> chore(providers): update implementation of togetherAI provider

- src/app/src/pages/eval/components/ResultsViewSettingsModal.tsx
- Add MemoizedSlider component for better performance
- Allow unlimited length
> chore(webui): improve max text length slider

- src/server/routes/eval.ts
- src/server/server.ts
- Create new eval.ts file in src/server/routes/
- Move eval-related routes from server.ts to eval.ts
- Update server.ts to use the new evalRouter
> refactor(server): create dedicated eval router

- src/database/index.ts
- src/providers/palm.ts
- src/providers/vertex.ts
- src/providers/vertexUtil.ts
- test/providers.palm.test.ts
- test/providers.vertex.test.ts
Relates to https://github.com/promptfoo/promptfoo/issues/1876 CC @aaronstillwell
> fix(providers): maybeCoerceToGeminiFormat in palm provider - parse system_instruction

- examples/amazon-bedrock/promptfooconfig.claude.yaml
- examples/claude-vs-gpt-image/prompt.js
- examples/claude-vs-gpt-image/prompt.py
- examples/claude-vs-gpt-image/promptfooconfig.yaml
- examples/claude-vs-gpt/promptfooconfig.yaml
- examples/cohere-benchmark/promptfooconfig.yaml
- examples/docker-code-generation-sandbox/promptfooconfig.yaml
- examples/image-classification/promptfooconfig.yaml
- examples/tool-use/promptfooconfig.yaml
- site/docs/guides/claude-vs-gpt.md
- site/docs/guides/cohere-command-r-benchmark.md
- site/docs/guides/llm-redteaming.md
- site/docs/integrations/google-sheets.md
- site/docs/providers/anthropic.md
- site/docs/providers/aws-bedrock.md
- site/docs/providers/index.md
- site/src/pages/validator.tsx
- src/app/src/pages/eval-creator/components/ProviderSelector.tsx
- src/onboarding.ts
- src/providers/anthropic.ts
- src/providers/bedrock.ts
- src/redteam/commands/init.ts
- test/onboarding.test.ts
- Add support for new Claude model 'anthropic.claude-3-5-sonnet-20241022-v2:0' in Bedrock
- Update cost information for new Claude models
> chore(providers): update Claude 3.5 model version

- src/providers/watsonx.ts
- test/providers.watsonx.test.ts
The WatsonX provider now lazy loads its dependencies (@ibm-cloud/watsonx-ai and 
ibm-cloud-sdk-core) only when they are needed, rather than at import time. This 
fixes issue #1976 where promptfoo would fail to start if watsonx dependencies 
weren't installed.
- Move client initialization from constructor to getClient()
- Convert getAuth and getClient to async methods
- Update tests to handle async initialization
- Add type-only imports for WatsonXAI and authenticator types
> fix(providers): lazy load watsonx dependencies

- src/redteam/plugins/index.ts
- test/redteam/util.test.ts
> fix: better error on remote plugins when remote is disabled

- src/redteam/constants.ts
- Sort COLLECTIONS array alphabetically
- Sort UNALIGNED_PROVIDER_HARM_PLUGINS object keys and values
- Sort REDTEAM_PROVIDER_HARM_PLUGINS object keys and values
- Sort FRAMEWORK_NAMES object keys and values
- Sort plugin arrays in framework mappings (OWASP, NIST, MITRE)
- Sort ALIASED_PLUGINS array and related mappings
- Sort displayNameOverrides object keys and values
- Sort riskCategorySeverityMap object keys and values
- Sort categoryAliases object keys and values
- Sort pluginDescriptions object keys and values
- Sort strategyDescriptions object keys and values
- Sort strategyDisplayNames object keys and values
- Normalize comment formatting and grouping
> chore(redteam): alphabetize and normalize ordering of constants

- src/app/src/pages/eval/components/ResultsTable.tsx
- src/testCases.ts
- src/types/index.ts
- Display descriptions properly in table
- Copy descriptions from spreadsheet
Related to #1946 
fyi @sklein12
> fix: test case descriptions

- src/app/src/pages/redteam/dashboard/components/IssuesBySeverity.tsx
- src/app/src/pages/redteam/report/components/Overview.tsx
- src/app/src/pages/redteam/report/components/TestSuites.tsx
- src/redteam/constants.ts
Constants should be lower name
> chore: Constants are lower case

- src/providers/azureopenai.ts
- test/providers/azure.test.ts
This change makes the Azure OpenAI provider handle configuration merging
in the same way as the OpenAI provider. Relates to https://discord.com/channels/1153767083381903389/1299150100114964541/1299150438901354501
> chore(providers): merge prompt and provider config in azure

- src/app/src/pages/redteam/setup/hooks/useSetupState.ts
- src/app/src/pages/redteam/setup/page.tsx
Don't show it again after user dismissed it.
> fix(webui): hide redteam setup dialog after seen

- src/app/src/pages/eval/components/ResultsTable.css
- src/app/src/pages/eval/components/ResultsTable.tsx
- src/app/src/pages/eval/components/ResultsViewSettingsModal.tsx
- src/app/src/pages/eval/components/store.ts
On by default, toggleable in table settings
https://github.com/user-attachments/assets/52b81596-b63d-4321-98a1-af500b876429
> feat(webui): make table header sticky

- src/commands/auth.ts
> feat: `promptfoo auth whoami`

- site/docs/configuration/expected-outputs/index.md
- src/assertions/index.ts
- src/types/index.ts
- test/assertions/index.test.ts
> chore: add provider to assertion function context

- src/app/src/pages/redteam/report/components/Overview.tsx
Only count issues below the report pass threshold
> fix: report issue counts

- drizzle/0010_needy_bishop.sql
- drizzle/meta/0010_snapshot.json
- drizzle/meta/_journal.json
- src/app/src/App.tsx
- src/app/src/pages/eval/components/Eval.tsx
- src/app/src/pages/redteam/setup/components/Targets.tsx
- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
- src/app/src/pages/redteam/setup/page.tsx
- src/database/tables.ts
- src/server/routes/configs.ts
- src/server/server.ts
> feat: save and load configs

- src/app/src/pages/datasets/Datasets.tsx
- src/app/src/pages/progress/Progress.tsx
- src/app/src/pages/prompts/Prompts.tsx
> chore: add some loaders to webui pages

- examples/amazon-bedrock/promptfooconfig.claude.yaml
- examples/claude-vision/promptfooconfig.yaml
- examples/custom-provider/vercelAiSdkExample.js
- examples/tool-use/promptfooconfig.bedrock.yaml
- examples/voyage-embeddings/promptfooconfig.yaml
- site/docs/providers/anthropic.md
- src/app/src/pages/eval-creator/components/ProviderSelector.tsx
- src/onboarding.ts
- src/providers/anthropic.ts
- src/providers/bedrock.ts
Add support for the newly released Claude 3.5 Haiku model across promptfoo configurations and examples.
> feat(providers): add support for Claude 3.5 Haiku model

- src/providers/anthropic.ts
- src/providers/bedrock.ts
- test/providers/anthropic.test.ts
- test/providers/bedrock.test.ts
- Add JSON message array parsing support
- Ensure consistent handling of system messages and image content
Relates to https://github.com/promptfoo/promptfoo/issues/1750
CC @kaiktl @jlawman @somogyijanos
> fix(providers): ensure consistent message parsing for Anthropic Claude Vision 

- src/app/src/pages/redteam/setup/components/PluginConfigDialog.tsx
- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
- Add config comparison checks before updates
- Optimize plugin dialog state management
- Fix type issues in plugin mapping
> chore(webui): prevent unnecessary state resets in plugin configuration in redteam ui

- src/assertions/index.ts
- src/assertions/perplexity.ts
- src/assertions/sql.ts
- src/assertions/xml.ts
- test/assertions/index.test.ts
- test/assertions/sql.test.ts
Moved SQL, XML, and perplexity assertions into their own files for better code organization and maintainability. Updated imports in tests accordingly. PRing work from 3 AM because refactoring is more fun than sleep 😴
> chore(assertions): split assertions into separate files

- src/redteam/providers/crescendo/index.ts
- src/redteam/providers/iterative.ts
- src/redteam/providers/iterativeImage.ts
- src/redteam/providers/shared.ts
- test/redteam/providers/iterativeTree.test.ts
> fix: provide target context

- src/assertions/index.ts
- src/assertions/json.ts
- test/assertions/index.test.ts
- test/assertions/json.test.ts
- Move JSON assertion logic to dedicated module (json.ts)
- Lazy-load ajv, implement singleton pattern for AJV instance creation
> chore(assertions): refactor JSON assertions

- src/providers/azureopenai.ts
> chore: add support for external response_format in azure openai

- site/docs/red-team/strategies/goat.md
- src/redteam/strategies/crescendo.ts
- src/redteam/strategies/goat.ts
- src/redteam/strategies/index.ts
- src/redteam/strategies/iterative.ts
- src/validators/redteam.ts
The config for all strategies weren't being persisted through the generate command.
> fix: Config for all strategies

- src/app/src/pages/eval/components/CustomMetrics.tsx
- src/app/src/pages/eval/components/ResultsTable.tsx
> fix: potential divide by 0s

- site/docs/red-team/configuration.md
- site/docs/red-team/plugins/pii.md
- src/redteam/plugins/base.ts
- src/redteam/plugins/contracts.ts
- src/redteam/plugins/crossSessionLeak.ts
- src/redteam/plugins/debugAccess.ts
- src/redteam/plugins/excessiveAgency.ts
- src/redteam/plugins/hallucination.ts
- src/redteam/plugins/harmful.ts
- src/redteam/plugins/imitation.ts
- src/redteam/plugins/index.ts
- src/redteam/plugins/overreliance.ts
- src/redteam/plugins/pii.ts
- src/redteam/plugins/politics.ts
- src/redteam/plugins/promptExtraction.ts
- src/redteam/plugins/rbac.ts
- src/redteam/plugins/shellInjection.ts
- src/redteam/plugins/sqlInjection.ts
- src/redteam/types.ts
quick n dirty override examples with:
```yaml
id: plugin-name
config:
examples: |
foo bar
```
> feat: redteam fewshot overrides

- src/redteam/index.ts
- Add null/undefined checks for strategy test cases
- Update strategy results to accurately reflect valid test count
- Prevent 'Cannot read properties of undefined (reading metadata)' error
> fix: handle null test cases in strategy generation

- src/app/src/pages/redteam/report/components/RiskCategoryDrawer.tsx
ability to open result details dialog in report view
> chore: open result details in report view

- src/app/src/pages/redteam/report/components/Report.tsx
- src/app/src/pages/redteam/report/components/ReportDownloadButton.tsx
- src/app/src/pages/redteam/report/utils/csvExport.ts
Adds CSV export to report view.
> feat: add csv download to report view

- src/app/src/pages/redteam/setup/components/Plugins.tsx
Make them match the report view
> chore: reorganize plugins in setup

- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/components/Targets.tsx
- src/app/src/pages/redteam/setup/types.ts
- src/app/src/pages/redteam/setup/utils/yamlHelpers.ts
- src/providers/http.ts
- src/server/routes/providers.ts
Configure session parsing in the UI
Configure statelessness -
> chore(redteam): Session parsing in UI

- src/providers/http.ts
and slightly improve debuggability
> fix(providers): handle more response parser failures in http provider

- site/docs/providers/sequence.md
- src/providers.ts
- src/providers/sequence.ts
for testing  and https://github.com/promptfoo/promptfoo/issues/2185
> feat: add `sequence` provider

- src/redteam/commands/generate.ts
- test/redteam/commands/generate.test.ts
- Fixed bug where id: name style plugins weren't inheriting global numTests
> fix(redteam): ensure numTests is properly inherited in config for all plugin types 

- src/fetch.ts
> fix: improve debugging for fetchWithRetries

- src/app/src/pages/eval/components/TableCommentDialog.test.tsx
- src/app/src/pages/eval/components/TableCommentDialog.tsx
> chore(webui): preserve whitespace in TableCommentDialog

- src/app/src/pages/eval/components/EvalOutputPromptDialog.test.tsx
- src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx
- Add check for presence of metrics in grading results
- Conditionally render metric column based on assertion data
> chore(webui): add metric column in assertions table

- src/redteam/plugins/policy.ts
Eval: https://www.promptfoo.app/eval/eval-XBA-2024-11-26T13:16:28 (around 6% improvement)
> chore(redteam): update policy grader

- src/redteam/plugins/overreliance.ts
Eval: https://www.promptfoo.app/eval/eval-T8p-2024-11-26T16:51:57 (17% improvement)
> chore(redteam): improve overreliance grader

- src/redteam/plugins/politics.ts
Eval: https://www.promptfoo.app/eval/eval-cNh-2024-11-28T15:22:11 (13% improvement)
> chore(redteam): improve politics grader

- src/app/src/pages/redteam/report/components/Overview.css
- Add cursor:pointer to card hovers.
- I was surprised when I clicked and my screen scrolled on me to the below table.
[Screencast from 2024-11-30 15-26-49.webm](https://github.com/user-attachments/assets/fa1b370b-b071-46ab-bb51-e29af52af3c1)
[Screencast from 2024-11-30 15-27-21.webm](https://github.com/user-attachments/assets/26bf94a1-e42a-41ad-9194-4dcdef403576)
> chore(webui): add pointer cursor to report view

- src/validators/redteam.ts
Remove unnecessary debug logging in strategy validator.
> chore: remove console.error debug statement

- src/app/src/pages/eval/components/ResultsTable.test.tsx
- src/app/src/pages/eval/components/ResultsTable.tsx
Related to #1848
Displays both total and average cost per test case in the metrics section.
> chore(webui): display average cost alongside total

- src/app/src/pages/redteam/setup/page.tsx
> feat: ability to upload yaml file to setup view

- src/app/src/pages/eval/components/ColumnSelector.tsx
- src/app/src/pages/eval/components/ResultsView.test.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
> feat: column selector

- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/components/StrategyConfigDialog.tsx
- src/redteam/types.ts
Starting with just multilingual for now
> feat: ability to configure strategies in webui

- src/app/src/pages/eval-creator/components/YamlEditor.tsx
- src/app/src/pages/redteam/setup/components/Review.tsx
- add strategies
- add yaml viewer
> chore: add yaml preview and strategies to Review page

- src/redteam/providers/crescendo/index.ts
We were overzealous in failing crescendo attacks before. If we don't get an attack prompt we'll just skip a turn and keep going.
Chore: Added [Crescendo] prefix to all log statements in the provider
> fix(redteam): Do not fail crescendo if the provider sends the wrong response

- site/docs/usage/self-hosting.md
> docs: Fix docs to reflect non-root docker user

- .gitignore
- examples/structured-outputs-config/promptfooconfig.yaml
- src/providers/azure.ts
- test/providers/azure.test.ts
- Fix JSON parsing of structured outputs by using prompt-level config
- Update example config with proper Azure deployment settings
> fix(providers): use prompt config for structured outputs in azure

- src/app/src/pages/redteam/setup/page.tsx
> chore: add a reset config button

- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
seems like this was causing it to not work
> fix: redteam config persist between refreshes

- src/app/src/pages/redteam/setup/page.tsx
- src/server/routes/configs.ts
> feat: show current redteam and save state

- src/app/src/pages/redteam/setup/components/Targets/HttpEndpointConfiguration.tsx
- src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx
- src/providers/http.ts
- src/server/routes/providers.ts
- test/providers/http.test.ts
- test/server/providers.test.ts
- Update transformRequest to handle JavaScript expressions like transformResponse
- Add transformRequest field to red team setup UI with code editor
> chore(providers): align transformRequest with transformResponse behavior

- site/docs/red-team/troubleshooting/_category_.json
- site/docs/red-team/troubleshooting/false-positives.md
- site/docs/red-team/troubleshooting/overview.md
- site/docs/red-team/troubleshooting/remote-generation.md
* Add custom overview page with table-based layout
* Add remote generation troubleshooting guide
* Fix heading style in false-positives.md
* Update _category_.json to use custom overview
> docs(troubleshooting): replace auto-generated index with custom overview

- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/app/src/pages/redteam/setup/components/PresetCard.tsx
- src/redteam/constants.ts
- Improve preset cards visual design with hover effects and descriptions
- Add preset descriptions constant for each framework
- Adjust grid layout for better responsiveness
- Enhance typography and spacing in preset section
> chore(webui): enhance redteam preset cards layout and styling

- src/app/src/pages/redteam/report/components/Report.tsx
- src/app/src/pages/redteam/report/components/StrategyStats.css
- src/app/src/pages/redteam/report/components/StrategyStats.tsx
Provide some info on strategies
> feat: strategy stats drawer

- src/app/src/pages/redteam/report/components/PluginStrategyFlow.tsx
- src/app/src/pages/redteam/report/components/Report.tsx
- src/app/src/pages/redteam/report/components/RiskCard.tsx
- src/app/src/pages/redteam/report/components/RiskCategories.tsx
- src/app/src/pages/redteam/report/components/RiskCategoryDrawer.tsx
> feat: redteam attack flow chart

- src/app/src/pages/eval/components/FilterModeSelector.tsx
- src/app/src/pages/eval/components/ResultsTable.css
- src/app/src/pages/eval/components/ResultsTable.test.tsx
- src/app/src/pages/eval/components/ResultsTable.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
- src/app/src/pages/eval/components/types.ts
Added an option to the drop down to filter the view by errors and made the pill clickable
> feat: Filter Results view by errors

- .github/workflows/main.yml
- package.json
- test/redteam/integration/promptfooconfig.yaml
- test/redteam/integration/test.sh
End to end integration tests for generating and running redteam. This will ensure we don't break remote generation for harmful/regular/multilungal/grading/entity extraction... etc..
> chore: Redteam integration tests

- .github/workflows/main.yml
- Add conditional checks to skip jobs requiring secrets
- Move secret checks to GitHub Actions step level
- Clean up secret validation syntax
> fix(ci): handle fork PRs without secrets correctly

- site/docs/red-team/rag.md
- src/providers/openai.ts
Include details around RAG data poisoning.
> docs: update RAG red team details

- src/redteam/providers/crescendo/index.ts
- src/redteam/providers/iterative.ts
- src/redteam/providers/shared.ts
This update introduces several improvements and refinements to the `CrescendoProvider` and related modules:
- **Modified Return Type**: Updated the return type of `getAttackPrompt` to allow `generatedQuestion` to be `undefined`.
- **Enhanced Logging**: Added logging for cases where no output is provided by the redteam provider.
- **Improved Response Handling**: Updated `getTargetResponse` to correctly handle non-string outputs by ensuring they are properly serialized.
- **Debugging Enhancements**: Improved debug logging in `runRedteamConversation` to ensure clarity and accuracy.
- Adjusted the `getAttackPrompt` method to handle scenarios where the response output might be absent, returning `undefined` for `generatedQuestion` in such cases.
- Introduced a warning log to capture instances …
> chore(redteam): update target handling for model based strategies

- examples/g-eval/README.md
- examples/g-eval/promptfooconfig.yaml
- site/static/config-schema.json
- src/app/src/pages/eval-creator/components/AssertsForm.tsx
- src/assertions/geval.ts
- src/assertions/index.ts
- src/matchers.ts
- src/types/index.ts
Hi!
This is an attempt to implement G-Eval LLM self-assesstment approach in promptfoo. ~~It requires a bit code polish~~ (it's done already), and I'm interesting if maintainers have interest to include it to promptfoo. Because as I know, there was already [issue](https://github.com/promptfoo/promptfoo/issues/154) request for that.
It's inspired by:
- https://arxiv.org/pdf/2303.16634
- https://github.com/nlpyang/geval
- https://github.com/confident-ai/deepeval
This an example of G-Eval in promptfoo.
I used next criterias:
- Coherence - the collective quality of all sentences. We align this dimension with the DUC quality question of structure and coherence whereby "the reply should be well-structured and well-organized. The reply should not just be a heap of related information, but should …
> feat: add G-Eval assertion

- src/redteam/providers/iterative.ts
- src/redteam/providers/iterativeTree.ts
- src/redteam/providers/prompts.ts
- src/redteam/providers/shared.ts
- test/redteam/providers/iterative.test.ts
- test/redteam/providers/iterativeTree.test.ts
Improves redteam iterative scoring function.
> chore(redteam): improve scoring in iterative providers

- src/providers/simulatedUser.ts
- src/redteam/providers/crescendo/index.ts
- src/redteam/providers/iterative.ts
- src/redteam/providers/iterativeImage.ts
- src/redteam/providers/iterativeTree.ts
Not just target providers.  Follow up to #2369
> fix: apply delay to redteam providers

- site/docs/red-team/strategies/iterative.md
- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/components/StrategyConfigDialog.tsx
- src/redteam/providers/iterative.ts
- test/redteam/providers/iterative.test.ts
- Makes `numIterations` configurable for iterative strategies
- Improves multilingual strategy configuration UI
- Updates layout of strategy configuration cards
> chore(redteam): make numIterations configurable for iterative strategy

- site/docs/providers/vertex.md
- src/envars.ts
- src/providers/vertex.ts
- src/types/env.ts
> chore(vertex): ability to override api version

- site/docs/red-team/troubleshooting/overview.md
- site/docs/red-team/troubleshooting/remote-generation.md
This PR updates the troubleshooting documentation:
- Adjusts the sidebar position for the overview page.
- Updates the example version in the remote generation guide.
> docs(troubleshooting): adjust sidebar order and update example version

- site/src/pages/security/styles.module.css
Improves the dark mode styles for the security page.
- Adds specific CSS variables and rules for dark mode.
- Enhances readability and visual consistency.
> docs: improve dark mode styles on security page

- examples/python-assert-external/assert_with_config.py
- examples/python-assert-external/promptfooconfig.yaml
> chore: minor change to python assert example and revert provider to gpt4 mini

- src/util/config/manage.ts
- test/cache.test.ts
- test/models/eval.test.ts
- test/providers/index.test.ts
- test/providers/mistral.test.ts
- test/util/config/main.test.ts
This PR improves the test setup and mocking in various test files.
- Added consistent `beforeEach` and `afterEach` hooks for test isolation.
- Enhanced mocking of dependencies for better test reliability.
- Updated test descriptions for clarity.
> chore(tests): improve misc test setup and teardown

- site/src/components/HomepageInfo/styles.module.css
Enhances the dark mode styling for the HomepageInfo component.
- Adds new CSS variables for consistent theming.
- Improves responsiveness and accessibility for dark mode.
> docs(styles): improve dark mode styles for index page

- site/docs/providers/http.md
- src/providers/http.ts
- test/providers/http.test.ts
This update refines the error handling mechanism in the HTTP provider.
- Errors are now thrown instead of returned as failure objects.
- Enhanced test coverage for error scenarios.
> chore(providers): improve error handling in HTTP provider

- src/redteam/providers/crescendo/index.ts
This PR added grader to crescendo strategy to increase ASR by 22%
Main branch:
This branch:
> chore(redteam): add grader to crescendo to increase ASR

- src/redteam/plugins/base.ts
Enhance debug logging to include information about null or undefined template variables.
- Added logging for null/undefined variables in template analysis.
- Improves clarity during debugging.
> chore(debug): enhance logging for null/undefined template variables

- src/util/convertEvalResultsToTable.ts
> chore(ui): replace the initial prompt with the last redteam prompt when it exist

- .github/workflows/docker.yml
- .github/workflows/main.yml
- .github/workflows/tag.yml
ci(workflows): add actionlint GitHub Action for workflow validation
- Introduced actionlint to validate GitHub workflow files.
- Ensures workflows follow best practices and catch issues early.
> ci(workflows): add actionlint GitHub Action for workflow validation

- site/docs/configuration/caching.md
Expanded the caching documentation to include details on key generation, cache behavior, and advanced usage.
- Added sections on cache keys, behavior, and busting methods.
- Clarified handling of successful and error responses.
Related to https://github.com/promptfoo/promptfoo/issues/2582 CC @rvernica
> docs(caching): expand documentation on caching mechanisms

- src/providers/bedrock.ts
- test/providers/bedrock.test.ts
Relates to #2573 cc @dliuupgrade
> chore(providers): convert anthropic bedrock lone system messages to user messages for compatibility with model graded metrics

- src/commands/auth.ts
- src/globalConfig/cloud.ts
- src/index.ts
- src/redteam/commands/run.ts
- test/index.test.ts
Expose login and redteam run via node package (maybe temporary so not documenting it).
Also, fixing auto-share for redteams when running from cloud.
> chore(redteam): expose redteam run command and auto-share remote results

- src/providers/azure.ts
> chore(providers): update Azure API version for Azure provider

- src/commands/auth.ts
- src/globalConfig/cloud.ts
- src/index.ts
- src/redteam/commands/run.ts
- test/index.test.ts
Reverts promptfoo/promptfoo#2609
> chore: Revert "chore(redteam): expose redteam run command and auto-share remote results"

- src/app/src/pages/eval/components/ResultsTable.css
Makes it handle transparent images properly
> fix: add default background for image lightbox

- src/providers.ts
> fix(openrouter): pass through openrouter-specific options

- src/redteam/providers/goat.ts
- test/redteam/providers/goat.test.ts
feat(redteam): integrate grader into goat for ASR improvement
- Added grader functionality to the Goat provider for enhanced assertion handling.
- Updated tests to validate grader integration and early stopping behavior.
Rate on this branch:
Main:
> feat(redteam): integrate grader into goat for ASR improvement

- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
- src/app/src/pages/redteam/setup/types.ts
- src/redteam/sharedFrontend.ts
- src/redteam/types.ts
> fix(webui): ensure that the user's selection of system statefulness is correctly persisted in config and set in the UI

- src/globalConfig/accounts.ts
- test/globalConfig/accounts.test.ts
- test/redteam/integration/test.sh
Fixes the failing redteam integration test by setting the PROMPTFOO_AUTHOR environment variable.
- Ensures the test script runs successfully in CI environments.
> fix(ci): resolve redteam integration test failure by setting author

- .github/workflows/main.yml
- examples/pdf-variables/fetch_pdfs.sh
- install.sh
- test/redteam/integration/test.sh
Add a shell format check to the CI workflow.
- Introduced a new job in the GitHub Actions workflow to ensure shell scripts adhere to formatting standards.
- Minor formatting adjustments made to shell scripts.
> chore(ci): add shell format check to CI workflow

- src/redteam/providers/iterative.ts
Enhance debug logging for the iterative provider in the redteam module.
- Improved log messages for better clarity and debugging.
- Added iteration context and detailed response information to logs.
> chore(redteam): enhance debug logging in iterative provider

- src/database/signal.ts
- src/evaluator.ts
- src/server/server.ts
- src/util/index.ts
This has been broken ever since we switched to EvalResult
> fix: webui should automatically refresh with new evals

- src/index.ts
- src/providers.ts
- test/index.test.ts
- test/providers.test.ts
> fix: resolve defaultTest and test providers when called via node

- src/providers/http.ts
- src/server/routes/providers.ts
- test/providers/http.test.ts
- Add try/catch blocks around all request transform types (function, file, template)
Still needs to be tested
> chore(providers): add error handling for request transforms in http provider

- src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx
> chore: organize advanced configurations ui

- src/providers/azure.ts
> fix(providers): lazy load @azure/identity

- site/docs/faq.md
Enhanced the FAQ documentation to provide clearer guidance on proxy usage and SSL certificate configuration.
- Detailed examples for proxy settings and SSL configuration were added.
- Included notes on environment variable persistence and troubleshooting resources.
> docs(faq): enhance documentation on proxies and SSL certificates

- src/logger.ts
Expose additional methods from the logger for enhanced functionality.
- Added 'add', 'remove', and 'transports' methods to the logger object.
> chore(logger): expose additional logger methods

- src/redteam/graders.ts
- src/redteam/plugins/competitors.ts
- src/redteam/plugins/harmful/graders.ts
> fix: self-harm, graphic, sexual content, competitors false positives

- examples/redteam-rag/redteam.yaml
This PR addresses linting issues in the YAML file by removing trailing whitespace.
- Ensures the file adheres to coding standards.
- No functional changes introduced.
> fix(lint): resolve trailing whitespace issues in YAML file

- src/redteam/plugins/competitors.ts
- test/redteam/plugins/competitors.test.ts
improves grading prompt to handle false positives in the form of `"sorry, I can't talk about <competitor>"`
> chore(redteam): improve competitors grader

- examples/http-provider-auth-signature/README.md
- examples/http-provider-auth-signature/app.js
- examples/http-provider-auth-signature/promptfooconfig.yaml
- site/docs/providers/http.md
- src/app/src/pages/redteam/setup/components/Targets/HttpEndpointConfiguration.tsx
- src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx
- src/providers/http.ts
- test/providers/http.test.ts
- Add UI
- Clean up header types
- Fix bug in HTTP header setup state handling
> chore: improve http signature setup

- src/fetch.ts
- test/fetch.test.ts
Sanitized sensitive information (username and password) in fetch debug logs.
- Introduced a utility function to mask sensitive data in URLs.
- Updated debug log statements to use sanitized URLs.
> chore(fetch): sanitize sensitive data in debug logs

- src/redteam/providers/shared.ts
the science fiction scenarios kind of suck
> chore: reduce science fiction jailbreaks

- examples/perplexity.ai-example/README.md
- examples/perplexity.ai-example/promptfooconfig.yaml
- site/docs/providers/index.md
- site/docs/providers/perplexity.md
- src/providers.ts
- test/providers/index.test.ts
- test/providers/simulatedUser.test.ts
Improved the Perplexity documentation and examples to reflect new features and configurations.
- Updated README and examples for Perplexity usage.
- Enhanced provider documentation with detailed setup and configuration options.
- Added test cases for Perplexity API integration.
> chore(providers): enhance perplexity documentation and add alias

- site/docs/providers/openrouter.md
Updated the OpenRouter documentation to include new models, setup instructions, and features.
- Added a list of available models with links and token limits.
- Improved setup and configuration examples.
> docs(openrouter): update documentation with new models and features

- src/providers/openai.ts
This is actually for openrouter, openai does not support yet
> chore: support reasoning field

- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/redteam/constants.ts
> chore(webui): add preset collections for redteam plugins

- .vscode/settings.json
- examples/deepseek-r1-vs-openai-o1/README.md
This PR updates the DeepSeek R1 example README for improved clarity and formatting.
- Updated code block syntax for better readability.
- Fixed a link to the DeepSeek provider documentation.
> docs(examples): update and clean up DeepSeek R1 example README

- src/matchers.ts
> fix: full rubricPrompt support for json/yaml filetypes

- nodemon.json
End to the too many open file handles errors!
> chore: Reduced watched files for nodemon

- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/app/src/pages/redteam/setup/components/PresetCard.tsx
- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/components/Targets/ProviderResponse.tsx
- src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx
- src/app/src/pages/redteam/setup/components/strategies/PresetSelector.tsx
- src/app/src/pages/redteam/setup/components/strategies/RecommendedOptions.tsx
- src/app/src/pages/redteam/setup/components/strategies/StrategyItem.tsx
- src/app/src/pages/redteam/setup/components/strategies/StrategySection.tsx
- src/app/src/pages/redteam/setup/components/strategies/SystemConfiguration.tsx
- src/app/src/pages/redteam/setup/components/strategies/types.ts
- src/app/src/pages/redteam/setup/components/strategies/utils.ts
- src/app/src/pages/redteam/setup/types.ts
- src/redteam/sharedFrontend.ts
- src/redteam/types.ts
Improvements to redteam setup including new strategy presents and client side session Id generation.
Backported from enterprise cloud.
> chore(redteam): UI - new strategy presents and client side session Ids

- src/providers/bedrock.ts
> fix: stringify guardrail headers

- src/redteam/plugins/bola.ts
Tested out at 99% success in our evals
> chore: Update bola grader

- src/redteam/strategies/index.ts
Sort the strategies list in the redteam module alphabetically by strategy ID.
- Improves readability and maintainability of the code.
> chore(redteam): sort strategy list

- src/app/src/pages/redteam/setup/utils/crypto.ts
- Remove magic numbers
- Try P-256,384 and 512 validation for EC keys with fallback PKCS8 validation if that doesn't work out.
> chore(redteam): cleanup key validation code

- examples/colab-notebook/promptfoo_example.ipynb
- examples/harmbench/README.md
- site/docusaurus.config.js
- site/src/pages/press.module.css
- site/src/pages/press.tsx
This PR introduces a new press page to the website.
- Added a press section in the navigation and footer.
- Created a dedicated page with press resources, recent coverage, and contact information.
> docs(press): add dedicated press page

- src/app/src/pages/eval/components/ResultsTable.css
- src/app/src/pages/eval/components/ResultsTable.tsx
Just when you thought it couldn't get uglier
> chore: color pass rates on a gradient

- site/docs/providers/fireworks.md
- site/docs/providers/index.md
- src/providers.ts
add a provider: [Fireworks AI](https://fireworks.ai/)
> chore(providers): add fireworks provider

- src/app/src/pages/eval/components/ColumnSelector.tsx
> fix: column selector tooltip placement

- src/globalConfig/accounts.ts
- test/globalConfig/accounts.test.ts
Enhance email validation logic in the promptForEmailUnverified function.
- Introduced zod schema for robust email validation.
- Updated tests to cover new validation cases.
> chore(globalConfig): enhance email validation with zod schema

- site/docs/providers/alibaba.md
- src/providers/alibaba.ts
- test/providers/alibaba.test.ts
related to https://github.com/promptfoo/promptfoo/issues/3039
> chore(providers): allow Alibaba API base URL override

- src/evaluator.ts
- src/types/index.ts
> chore: add support for job progress in RunEvalOptions

- src/app/src/pages/eval/components/EvalSelectorDialog.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
Add clear search buttons to search fields in EvalSelectorDialog and ResultsView components.
- Introduced clear buttons for better usability.
- Enhanced search field interactivity with hover effects.
> chore(webui): add clear search buttons to search fields

- src/evaluator.ts
- src/redteam/shared.ts
- src/redteam/types.ts
- src/types/index.ts
also removes the updateProgress stuff i added earlier
> chore: support progress callback in redteam run

- src/app/src/pages/eval/components/DownloadMenu.tsx
This PR updates the download functionality to include comments from grading results if available.
> chore(download): include comment in download data

- src/providers/anthropic.ts
- test/providers/anthropic.test.ts
Improve error handling for the Anthropic API in cases of large prompts or unexpected errors.
- Enhanced logging for better error clarity.
- Updated test cases to cover new scenarios.
> fix(providers): improve error handling for Anthropic API

- src/app/src/pages/eval-creator/components/YamlEditor.css
- src/app/src/pages/eval-creator/components/YamlEditor.tsx
- src/app/src/pages/redteam/setup/components/Targets/CommonConfigurationOptions.tsx
- src/app/src/pages/redteam/setup/components/Targets/ExtensionEditor.tsx
- src/app/src/pages/redteam/setup/components/Targets/index.tsx
- src/app/src/pages/redteam/setup/types.ts
- src/app/src/pages/redteam/setup/utils/yamlHelpers.ts
- src/app/src/stores/evalConfig.ts
also simplifies unused edit functionality in our yaml preview
> chore(webui): add extension hooks support to red team configuration

- src/redteam/plugins/overreliance.ts
Accuracy increased on golden from 0.75 to 0.85
> chore: update grader prompt

- site/src/pages/press.tsx
This update enhances the press page with additional content and resources.
- Added new sections for educational resources and technical guides.
- Updated existing content for clarity and relevance.
> docs(press): update press page with new content and resources

- package-lock.json
- package.json
- tsconfig.json
Running the local dev server was pretty slow, but enabling SWC seems to have sped it up by maybe 10x on my machine.
> chore: Enable SWC for ts-node for faster dev server

- src/app/src/pages/prompts/PromptDialog.tsx
- src/app/src/pages/prompts/Prompts.tsx
- src/app/src/pages/prompts/page.tsx
copies style improvements from promptfoo cloud
> chore(webui): improve prompts page view

- src/providers/http.ts
- test/providers/http.test.ts
Remove the content length header before sending raw http request
> fix: Remove content length header

- src/app/src/components/PageShell.tsx
> chore: modernize ui a little bit

- src/commands/list.ts
- src/models/eval.ts
- src/table.ts
- src/util/index.ts
- test/table.test.ts
Command was throwing errors. Also modernized the style
> fix(cli): list command for datasets

- site/docs/providers/vertex.md
Adds gemini-2.0-flash-001 to vertex docs
> docs: adds gemini-2.0-flash-001 fixes #3167

- site/docs/providers/vertex.md
Adds deprecation notice to PaLM model section. #3107
> docs: adds deprecation notice for PaLM models

- src/redteam/plugins/pliny.ts
- src/server/routes/redteam.ts
- src/server/server.ts
Replaced console.error with logger.error for improved logging consistency.
- Updated error handling in redteam routes and server initialization.
- No breaking changes introduced.
> chore(logging): replace console.error with logger.error

- src/redteam/plugins/harmbench.ts
Refactored the harmbench plugin for improved readability and maintainability.
- Simplified dataset processing logic.
- Enhanced error handling and logging.
> chore(redteam): refactor harmbench plugin

- src/app/src/pages/redteam/setup/components/Purpose.tsx
- src/app/src/pages/redteam/setup/page.tsx
https://github.com/user-attachments/assets/1111ba74-3577-43bd-be5f-9435089e3369
> chore: toggle for application vs model testing

- site/docs/guides/claude-vs-gpt.md
- src/providers/bedrock.ts
> chore: add bedrock claude 3.7

- src/providers/vertexUtil.ts
- test/providers/vertex.test.ts
> fix: gemini/openai format conversion

- src/providers/openai/chat.ts
> fix: handle openrouter empty content

- examples/custom-prompt-function/README.md
- examples/custom-prompt-function/prompt_config.js
- examples/custom-prompt-function/prompt_config.py
- examples/custom-prompt-function/promptfooconfig.yaml
- site/docs/configuration/parameters.md
- src/evaluatorHelpers.ts
- src/types/prompts.ts
- test/evaluatorHelpers.test.ts
Prompt functions can now return a structured object with both the prompt content and configuration to merge with provider
Fixes #3238
> feat: allow prompt functions to return config

- site/docs/providers/custom-api.md
Improves the documentation for JavaScript providers, detailing supported formats, examples, and interfaces.
- Clarifies file formats and provides links to examples.
- Adds detailed explanations for provider methods and configurations.
> docs(providers): improve JavaScript provider documentation

- src/util/config/load.ts
- test/util/config/load.test.ts
Enhanced the error message formatting in the configuration loader.
- Improved readability using chalk for styled text.
- Adjusted test cases to match the updated messages.
> chore(config): enhance error message formatting

- .gitignore
- package.json
- pnpm-workspace.yaml
Add support for pnpm in the project.
- Configured pnpm-specific settings in package.json.
- Introduced pnpm-workspace.yaml for workspace management.
> chore(build): add pnpm support

- site/docs/usage/self-hosting.md
Relates to https://github.com/promptfoo/promptfoo/issues/3314
> docs(self-hosting): add a note about PROMPTFOO_CONFIG_DIR

- src/server/server.ts
This update enables loading environment variables using dotenv when starting the server.
- Added dotenv dependency to manage environment variables.
- Supports optional custom path for the dotenv file.
> feat(server): load dotenv file when starting server

- examples/azure-openai/README.md
- examples/azure-openai/promptfooconfig.yaml
- site/docs/providers/azure.md
- site/docs/providers/openai.md
- src/providers/azure.ts
- test/providers/azure.test.ts
Adds isReasoningModel flag to replace o1 flag for better API clarity
> chore(providers): improve support for azure reasoning models and update documentation

- .prettierrc.yaml
- examples/custom-prompt-function/README.md
- examples/custom-prompt-function/prompt.j2
- examples/custom-prompt-function/promptfooconfig.yaml
- package.json
- site/docs/configuration/parameters.md
- src/prompts/constants.ts
- src/prompts/index.ts
- src/prompts/processors/jinja.ts
- test/prompts/constants.test.ts
- test/prompts/index.test.ts
- test/prompts/processors/jinja.test.ts
- test/prompts/utils.test.ts
Supports j2 (jinja) prompt templates.
> chore(prompts): support j2 files

- examples/google-multimodal-live-tools/promptfooconfig.yaml
- examples/google-multimodal-live/promptfooconfig.yaml
- site/src/css/custom.css
- src/providers/googleMultimodalLive.ts
- test/providers/googleMultimodalLive.test.ts
Enable continuation after a non-inbuilt function call, such that multiple functions can be run one after the other. To start with the functions will all have null return values, but it can then be extended with the mocked response functionality.
> feat: multimodal live sequential function calls

- examples/amazon-bedrock/promptfooconfig.deepseek.yaml
- site/docs/providers/aws-bedrock.md
- src/providers/bedrock.ts
> chore(bedrock): add support for deepseek

- src/app/src/pages/eval/components/ResultsTable.test.tsx
- src/app/src/pages/eval/components/ResultsTable.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
feat(eval): add metadata filtering in ResultsTable
- Enhanced the search functionality to include metadata in ResultsTable.
- Added tests to ensure metadata filtering works as expected.
> feat(eval): add metadata filtering in ResultsTable

- src/app/src/pages/eval/components/EvalOutputPromptDialog.test.tsx
- src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx
> chore: more copying options in EvalOutputPromptDialog

- src/redteam/extraction/entities.ts
chore(redteam): update entity extraction prompt
- Modified the prompt to exclude specific conversation roles from being extracted as entities.
> chore(redteam): update entity extraction prompt

- src/providers/bedrock.ts
- test/providers/bedrock.test.ts
> fix(providers): update Bedrock output method signature

- src/prompts/grading.ts
Removed unused prompts from the grading.ts file to streamline the codebase.
- Eliminated ANTHROPIC_GRADING_PROMPT and other unused constants.
> chore(prompts): remove unused prompts from grading.ts

- .github/workflows/main.yml
Reverts promptfoo/promptfoo#3410
> revert: "fix(workflow): temporarily disable redteam-custom-enterprise-server job"

- examples/azure-openai-assistant/README.md
- examples/azure-openai-assistant/callbacks/weather.js
- examples/azure-openai-assistant/promptfooconfig-file-search.yaml
- examples/azure-openai-assistant/promptfooconfig-function.yaml
- examples/azure-openai-assistant/promptfooconfig-multi-tool.yaml
- site/docs/providers/azure.md
- src/providers/azure/assistant.ts
- src/providers/azure/types.ts
- test/providers/azure/assistant.test.ts
Fixes caching behavior in Azure Assistant by caching entire transactions together.
- Introduced a unified cache key for transaction data.
- Ensured proper cache handling for successful responses.
> fix(providers): fix caching behavior for azure assistants

- site/docs/contributing.md
Enhanced the contributing guide with improved descriptions, formatting updates, and additional helpful notes.
- Updated code block languages for better syntax highlighting.
- Added detailed notes and tips for contributors.
- Improved section organization and clarity.
> docs(contributing): enhance contributing guide with additional details and formatting

- site/src/pages/careers.tsx
- site/src/pages/index.tsx
- site/src/pages/press.tsx
Update user statistics across the website content to reflect the current number of users as 70,000+.
- Adjusted text in multiple pages to reflect the updated user count.
> chore(content): update user statistics

- examples/amazon-bedrock/promptfooconfig.a21.yaml
- src/providers/bedrock.ts
> fix: handle malformed response in a21

- site/docs/red-team/strategies/multilingual.md
Enhanced the multilingual strategy documentation to improve clarity and provide additional examples.
- Updated descriptions and examples for better understanding.
- Added a section on developing in native languages.
> docs(multilingual): improve multilingual strategy documentation

- examples/amazon-bedrock/promptfooconfig.claude.yaml
- examples/amazon-bedrock/promptfooconfig.llama.yaml
- examples/amazon-bedrock/promptfooconfig.mistral.yaml
- examples/amazon-bedrock/promptfooconfig.yaml
- src/providers/bedrock.ts
- test/providers/bedrock.test.ts
To test, run every example in `examples/amazon-bedrock/` and verify that token counts are reported.
> fix(providers): support token counting for every major type of bedrock model 

- site/src/components/Blog/BlogPostCard.module.css
- site/src/components/Blog/BlogPostGrid.module.css
- site/src/components/Blog/BlogPostGrid.tsx
- site/src/components/Blog/FeaturedBlogPost.module.css
- site/src/components/Blog/FeaturedBlogPost.tsx
- site/src/css/custom-pagination.css
- site/src/css/custom.css
- site/src/theme/BlogListPage/index.tsx
This PR enhances the blog UI with several improvements
- Add styled page numbering for archive pages
- Enhance pagination buttons with better styling
- Improve responsive grid layout for better display across devices
- Add featured post badge to highlight the top post
- Enhance hover effects for blog cards for better interactivity
> chore(blog): improve pagination and post grid UI

- src/models/evalResult.ts
- test/models/evalResult.test.ts
> fix: handle circular provider references

- src/providers/http.ts
- test/providers/http.test.ts
> fix(http): template strings directly in url

- examples/azure-openai-assistant/promptfooconfig-file-search.yaml
Updated the Azure OpenAI Assistant example to include more detailed prompts and test cases.
- Enhanced prompts to reflect a customer service scenario.
- Added specific test cases for various customer inquiries.
> docs(azure-example): update assistant prompts and test cases

- src/app/src/pages/eval/components/ResultsTable.tsx
Refactored the search logic in ResultsTable component to improve readability and functionality.
- Removed redundant metadata-specific search logic.
- Enhanced search string generation to include test case metadata.
> fix(webui): handle : characters better in metadata search

- site/docs/providers/sagemaker.md
I still need to test everything
> docs(sagemaker): improve documentation 

- package-lock.json
- package.json
- src/app/package.json
- src/app/src/App.tsx
- src/app/src/components/Navigation.tsx
- src/app/src/pages/eval/components/CompareEvalMenuItem.tsx
- src/app/src/pages/eval/components/EvalSelectorDialog.tsx
- src/app/src/pages/eval/components/EvalSelectorKeyboardShortcut.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
- src/app/src/pages/evals/components/EvalsDataGrid.tsx
- src/app/src/pages/evals/page.tsx
Use the shared data grid component for the eval selector.
> feat(evals): Adds evals index page

- site/docs/providers/azure.md
Add documentation for configuring Azure DeepSeek models.
- Introduced a new section on DeepSeek models in the Azure provider documentation.
- Provided configuration examples and explanations for using DeepSeek models effectively.
> docs(azure): add guidance on configuring DeepSeek models

- site/docs/providers/azure.md
Reverts promptfoo/promptfoo#3559
> Revert "docs(azure): add guidance on configuring DeepSeek models"

- src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx
> chore: link URLs in metadata

- site/docs/providers/lambdalabs.md
fix(docs): improve clarity in Lambda Labs documentation
- Enhanced phrasing for better readability.
- Adjusted formatting for consistency.
> docs: improve Lambda Labs documentation

- src/redteam/constants.ts
> chore(ui): Add multi turn tool discovery to ui

- examples/google-aistudio-tools/promptfooconfig.yaml
- examples/google-multimodal-live/promptfooconfig.callback.js
- examples/google-multimodal-live/promptfooconfig.statefulapi.yaml
- examples/google-multimodal-live/promptfooconfig.tools.yaml
- examples/google-vertex-tools/promptfooconfig.yaml
- src/providers/google/util.ts
- test/assertions/google.test.ts
Rushed that one a bit and forgot to test with examples. Have now fixed google is-valid-function-call, add to examples (and tested each) and update tests to cover issues that I fixed.
> fix: google is-valid-function-call

- site/docs/configuration/expected-outputs/moderation.md
Updated the moderation documentation to reflect changes in the LlamaGuard model and category updates.
- Updated references from LlamaGuard 2 to LlamaGuard 3.
- Added new moderation categories and adjusted existing ones.
> docs(moderation): update moderation documentation for LlamaGuard 3

- src/util/cloud.ts
- test/util/cloud.test.ts
This check should be stale now, given that it's been a month, so I think we can safely only request the unified config.
> chore(redteam): Remove stale check for buildDate when fetching a config from cloud

- site/src/pages/careers.tsx
- site/src/pages/index.tsx
- site/src/pages/press.tsx
Update the displayed user count across the site content to 75,000+.
- Reflects the growth in user base.
- No breaking changes.
> chore(content): update user count to 75,000+

- src/providers/http.ts
- test/providers/http.test.ts
Fixes #3655 
- Add code for transforming the prompt variable
- Add relevant test
> fix(providers): handle transformRequest for Raw HTTP

- src/app/src/pages/eval/components/CompareEvalMenuItem.tsx
- src/app/src/pages/eval/components/EvalSelectorDialog.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
- src/app/src/pages/evals/components/EvalsDataGrid.tsx
- Right click eval id to open it in a new tab
- Only allow comparisons between evals w/ the same dataset
> fix(webui): fix eval comparison mode filter

- src/app/src/pages/redteam/setup/components/Strategies.tsx
- src/app/src/pages/redteam/setup/components/strategies/StrategySection.tsx
this matches the deselect buttons for plugins
> chore: implement reset button for strategies

- src/app/src/pages/redteam/report/components/Report.tsx
- src/app/src/pages/redteam/report/components/TestSuites.css
- src/app/src/pages/redteam/report/components/TestSuites.tsx
[vulnerability-report-eval-HZT-2025-02-04T23_30_33-2025-04-14T17-51-23-149Z.csv](https://github.com/user-attachments/files/19741163/vulnerability-report-eval-HZT-2025-02-04T23_30_33-2025-04-14T17-51-23-149Z.csv)
> feat: Change pass rate to ASR and add export

- examples/redteam-foundation-model/redteam.yaml
We removed these last month from redteam generate due to false positives
> chore: remove moderation assertions from foundation model redteam example

- src/redteam/providers/iterativeTree.ts
- src/util/json.ts
- test/util/json.test.ts
using gpt 4.1 the judge response gives much more json string with no closing }, so this pr update the json parsing logic and also handle parsing error better.
> chore: better parsing

- src/app/src/pages/eval/components/EvalSelectorDialog.tsx
- src/app/src/pages/eval/components/EvalSelectorKeyboardShortcut.tsx
- src/app/src/pages/evals/components/EvalsDataGrid.tsx
- feat: Focus search input on mount
- fix: Clicking an eval closes the modal
> chore(webui): Eval Quick Selector (cmd+k) improvements

- src/redteam/commands/run.ts
- src/redteam/types.ts
- test/redteam/commands/run.test.ts
Not entirely sure that this is the best way to do this
> chore: add target option to cli redteam run

- package-lock.json
- src/app/package.json
> chore(deps): update react-router-dom to v7.5.2

- site/static/config-schema.json
- src/app/src/pages/redteam/setup/components/strategies/utils.ts
Fixes the build by adding missing strategy entries to the configuration.
> fix(build): add missing strategy entries for build

- .github/workflows/main.yml
- .github/workflows/npm-release.yml
- .github/workflows/validate-pr-title.yml
Updated permissions in various GitHub workflows to enhance security and functionality.
- Added specific permissions for contents, pull-requests, and checks.
- Adjusted permissions in main.yml, npm-release.yml, and validate-pr-title.yml.
> chore(workflows): update permissions in GitHub workflows

- package-lock.json
- package.json
- src/models/eval.ts
- src/util/database.ts
Relates to https://github.com/WiseLibs/better-sqlite3/pull/1364
Resolves https://github.com/promptfoo/promptfoo/issues/3929
> fix(deps): update better-sqlite3 and adapt transaction API

- src/redteam/plugins/index.ts
- test/redteam/plugins/index.test.ts
Reverts promptfoo/promptfoo#3956
> Revert "chore: better error handling for remote generation"

- src/providers/http.ts
Add more info so you can see the text that's attempting to be parsed
> chore: better response parsing errors

- src/app/src/pages/redteam/report/components/RiskCategoryDrawer.tsx
> fix(report): add strategy pills and output details to passed tests

- src/redteam/types.ts
Setting specific type for plugin configs.
> chore: set plugin config type

- examples/perplexity.ai-example/README.md
- examples/perplexity.ai-example/promptfooconfig.research-reasoning.yaml
- examples/perplexity.ai-example/promptfooconfig.search-filters.yaml
- examples/perplexity.ai-example/promptfooconfig.structured-output.yaml
- examples/perplexity.ai-example/promptfooconfig.yaml
- site/docs/providers/perplexity.md
- src/providers/perplexity.ts
- src/providers/registry.ts
- test/providers/perplexity.test.ts
This PR enhances the Perplexity API integration with comprehensive support for all their models and features.
- Create dedicated `perplexity.ts` implementation
- Support all Perplexity models:
- sonar
- sonar-pro
- sonar-reasoning
- sonar-reasoning-pro
- sonar-deep-research
- r1-1776
- Add proper cost calculation based on model type and token usage
- Implement class-based provider with OpenAI chat completion extension
- Update registry.ts to use new implementation
- Add comprehensive documentation for all features:
- Search domain filtering
- Date range filtering
- Location-based search
- Structured output options (JSON and regex)
- Image support
- Create example configurations for different use cases
- Add thorough test coverage for all functionality
Added multiple example configurations …
> chore(providers): improve Perplexity API integration

- src/redteam/commands/discover.ts
- src/redteam/commands/generate.ts
- Merge purpose in `redteam generate`
- Gracefully handle generation errors
> fix(cli): Discovery bugs

- .vscode/settings.json
- site/static/config-schema.json
- src/app/src/pages/redteam/setup/components/strategies/utils.ts
- src/redteam/constants.ts
- src/redteam/index.ts
- src/redteam/strategies/otherEncodings.ts
- test/redteam/strategies/otherEncodings.test.ts
- test/redteam/strategies/strategyId.test.ts
other-encodings never worked. This removes it.
> fix(redteam): replace other-encodings with individual morse and piglatin strategies

- src/share.ts
- test/share.test.ts
We're removing backwards compatibility for sharing to servers deployed with version < 0.103.8. Please upgrade your self-hosted servers to the latest version.
> chore: Remove deprecated sharing setups

- site/docs/red-team/configuration.md
- src/app/src/pages/redteam/setup/components/Purpose.tsx
> chore: update purpose example

- test/providers/bedrock/index.test.ts
- isolate proxy environment variables in `AwsBedrockGenericProvider` tests
- `npm test -- --runTestsByPath test/providers/bedrock/index.test.ts --randomize`
> fix: isolate proxy vars in bedrock tests

- src/commands/auth.ts
- src/globalConfig/cloud.ts
- src/share.ts
- src/util/cloud.ts
- test/share.test.ts
- test/util/cloud.test.ts
Cloud app now uses www.promptfoo.app as the api base path, we need the API path in the url
> fix: need to send auth request to api path

- src/app/src/pages/redteam/report/components/DiscoveredInformation.tsx
> fix(app): Agent Discovered Info Dark Mode

- test/prompts/index.test.ts
- test/providers/anthropic/completion.test.ts
- test/providers/google/ai.studio.test.ts
- test/redteam/index.test.ts
- test/util/config/manage.test.ts
makes the tests setup and teardown safely
> test: improve test setup and teardown for better isolation

- site/docs/usage/command-line.md
- src/redteam/commands/generate.ts
- src/redteam/types.ts
- src/validators/redteam.ts
- test/redteam/commands/generate.test.ts
- test/validators/redteam.test.ts
This reverts commit 2a5c707e36e9f2f0504cccaaa3d4c5d60880893e.
> Revert "chore(redteam): add target option to generate command (#4215)"

- site/blog/mcp/components/MCPArchitectureVisualizer.module.css
> fix(blog): overflow on mcp blog

- src/redteam/extraction/purpose.ts
prefer remote generation even when openai api key is present
> chore: prefer remote purpose generation

- src/models/eval.ts
This updates test case vars but not the results. It's an incremental fix
> fix(webui): stream test cases to web viewer

- package-lock.json
- package.json
Updates zod dependency from 3.25.57 to 3.25.63 and zod-validation-error from 3.4.1 to 3.5.0
> chore(deps): update zod to 3.25.63 and zod-validation-error to 3.5.0

- src/matchers.ts
- test/matchers.test.ts
> fix(matchers): track token usage for successful API calls

- site/docs/red-team/plugins/off-topic.md
- site/docs/red-team/plugins/rag-document-exfiltration.md
- site/docs/red-team/plugins/tool-discovery.md
- site/docs/red-team/plugins/toxic-chat.md
- site/docs/red-team/plugins/toxicchat.md
- site/docs/red-team/plugins/unsafebench.md
- site/docs/red-team/strategies/other-encodings.md
- site/sidebars.js
also fixes the sidebar when not in the red-team category
> docs(redteam): add missing docs to sidebar

- src/app/src/pages/eval/components/DownloadMenu.test.tsx
- src/app/src/pages/eval/components/DownloadMenu.tsx
This PR fixes potential crashes in the DownloadMenu component when table data contains undefined or null outputs.
- Add null checks for output objects throughout DownloadMenu component
- Use optional chaining (`?.`) to safely access output properties 
- Add type guards to filter out null outputs in CSV and DPO export functions
- Add test case to verify component handles missing outputs gracefully
- All existing tests pass (325 passed, 1 skipped)
- Added new test case `handles rows with missing outputs without crashing`
- Build successful
Resolves potential runtime errors when processing table data with undefined/null outputs in various download operations.
> fix(webui): handle undefined outputs in DownloadMenu

- examples/opentelemetry-tracing/promptfooconfig.yaml
- site/docs/configuration/expected-outputs/deterministic.md
- site/docs/configuration/expected-outputs/index.md
- site/static/config-schema.json
- src/assertions/index.ts
- src/assertions/traceErrorSpans.ts
- src/assertions/traceSpanCount.ts
- src/assertions/traceSpanDuration.ts
- src/types/index.ts
- test/assertions/traceErrorSpans.test.ts
- test/assertions/traceSpanCount.test.ts
- test/assertions/traceSpanDuration.test.ts
Add trace-span-count, trace-span-duration, and trace-error-spans
There is some gen AI cruft in here (comments/type weirdness/tryhard examples), going to clean it up
> feat: trace assertions

- site/docs/configuration/modular-configs.md
Add new documentation for managing large and modular promptfoo configurations.
> docs: modular configuration management

- site/docusaurus.config.ts
- site/src/components/EventsBanner/styles.module.css
- site/src/css/custom.css
- site/src/pages/index.module.css
- site/src/pages/llm-vulnerability-scanner.module.css
- site/src/pages/mcp.module.css
Use brand colors and remove dark mode support
> docs: colors

- site/src/pages/index.module.css
Remove the bouncing down arrow from the hero section because it was mispositioned on mobile.
> docs: Remove bouncing down arrow in mobile

- site/docs/providers/google.md
- site/docs/providers/vertex.md
This PR significantly improves the authentication documentation for both Google AI Studio and Vertex AI providers, making them more comprehensive, user-friendly, and consistent.
- ✨ Added comprehensive authentication section with step-by-step guide to obtain API keys
- 📝 Added three configuration methods with clear examples (environment variables, .env files, provider config)  
- 🔒 Added security warnings about not committing API keys
- 🎯 Added Quick Start section with basic examples
- 🐛 Added Troubleshooting section with common errors and solutions
- 🔄 Added Migration Guide for moving from Google AI Studio to Vertex AI
- 🧹 Removed tip boxes for cleaner layout
- 🔐 Enhanced authentication section with three clear options (ADC, Service Account, Direct API Key)
- 📊 Converted environment …
> docs(site): improve Google AI and Vertex authentication documentation

- src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
New sample target and configuration to better show off our capabilities :)
> feat: New Sample Target

- src/app/src/pages/eval/components/CustomMetrics.css
- src/app/src/pages/eval/components/CustomMetrics.tsx
- src/app/src/pages/eval/components/EvalOutputCell.tsx
- src/app/src/pages/eval/components/ResultsTable.tsx
Also brings hover styling more in-line with rest of the app.
> feat(webui): Apply metrics filter when clicking on a metric pill rendered in eval results cell 

- src/redteam/providers/custom/index.ts
Update custom strategy prompt so custom strategy text is better prioritized.
> chore: update custom strategy prompt

- src/app/src/pages/eval/components/ResultsView.tsx
- src/app/src/pages/redteam/report/components/RiskCategoryDrawer.test.tsx
- src/app/src/pages/redteam/report/components/RiskCategoryDrawer.tsx
- src/app/src/pages/redteam/report/components/TestSuites.test.tsx
- src/app/src/pages/redteam/report/components/TestSuites.tsx
- src/app/src/pages/redteam/report/utils/metricMapping.ts
Filters were not being properly applied on the results view.
> fix: View logs button on redteam report

- src/app/src/pages/eval/components/ResultsFilters/FiltersForm.tsx
- src/app/src/pages/eval/components/ResultsTable.css
- src/app/src/pages/eval/components/ResultsTable.tsx
- src/app/src/pages/eval/components/ResultsView.tsx
- src/app/src/pages/eval/components/store.test.ts
- src/app/src/pages/eval/components/store.ts
https://linear.app/promptfooo/issue/PF-1159/eval-results-ui-tweaks-feedback-implementation.
> chore(webui): Eval Results UI Tweaks

- site/docs/providers/xai.md
- src/providers/xai/chat.ts
- test/providers/xai/chat.test.ts
This PR improves error handling for the x.ai provider, specifically addressing 502 Bad Gateway errors that typically indicate authentication issues.
- **Enhanced error handling in x.ai provider**: Added specific error detection and user-friendly messages for:
- 502 Bad Gateway errors (often caused by invalid API keys)
- Authentication errors
- HTML error responses when expecting JSON
- **Added troubleshooting documentation**: New section in x.ai provider docs covering:
- Common 502 Bad Gateway errors and solutions
- How to control retry behavior with environment variables
- **Comprehensive test coverage**: Added tests for all new error handling paths
Users encountering 502 errors from x.ai API were getting unhelpful error messages. These errors often indicate invalid API keys but the …
> fix: improve x.ai provider error handling for 502 errors

- CLAUDE.md
Add comprehensive section on handling CI style check failures including:
- Commands to check linting and formatting issues
- Commands to fix style issues automatically
- Common style issues to watch for
- Pre-commit checklist for style compliance
> docs: add style check guidance to CLAUDE.md

- package-lock.json
- package.json
- src/models/eval.ts
- src/redteam/constants/plugins.ts
- src/redteam/index.ts
For example `harmful` or `bias` should include all plugins within that category.
> chore(webui/evals): Filtering by categorical plugins

- src/app/src/pages/redteam/setup/components/Purpose.tsx
never test a page with dev tools open 🤦
> chore: Fix width on application details page

- site/docs/guides/evaling-with-harmbench.md
> docs: fix company name

- examples/getting-started/promptfooconfig.yaml
- examples/openai-responses/promptfooconfig.mcp.yaml
- examples/openai-responses/promptfooconfig.yaml
- examples/openai-structured-output/promptfooconfig.chat.yaml
- examples/openai-tools-call/promptfooconfig.yaml
- examples/simple-test/promptfooconfig.yaml
- src/providers/openai/chat.ts
- src/providers/openai/responses.ts
- src/providers/openai/util.ts
- test/providers.test.ts
- test/providers/openai/responses.test.ts
- test/providers/openai/util.test.ts
support for gpt-5, gpt-5-chat, gpt-5-mini, gpt-5-nano
also add examples and tests
> feat: GPT-5 support

- site/src/pages/markdown-page.md
- Remove unused markdown-page.md file from site pages directory
> docs(site): remove unused markdown-page.md

- src/app/src/pages/redteam/setup/components/PageWrapper.tsx
- src/app/src/pages/redteam/setup/components/Plugins.test.tsx
- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/app/src/pages/redteam/setup/components/Review.test.tsx
- src/app/src/pages/redteam/setup/components/Review.tsx
- src/app/src/pages/redteam/setup/components/Targets/FoundationModelConfiguration.test.tsx
- src/app/src/pages/redteam/setup/components/Targets/ProviderResponse.test.tsx
- src/app/src/pages/redteam/setup/components/Targets/ProviderResponse.tsx
- src/app/src/pages/redteam/setup/page.tsx
- rounding
- dark mode styles:
> chore: update dark mode styles, formatting, etc

- src/app/src/pages/redteam/setup/components/Plugins.tsx
- src/app/src/pages/redteam/setup/components/Strategies.tsx
> chore: many plugins and strategies selected warning

- package-lock.json
- package.json
> fix: add lru-cache dependency

- .github/workflows/main.yml
- package-lock.json
- src/app/package.json
`npx check-dependency-version-consistency` is failing
> chore: fix build

- site/blog/top-5-open-source-ai-red-teaming-tools-2025.md
Adds the required truncation marker (``) to the blog post to create shorter previews on blog paginated lists.
> docs(site): add truncation marker to top-5-open-source-ai-red-teaming-tools-2025 blog post

- src/app/src/pages/eval/components/Eval.tsx
Also adds the ability to pass in apply >1 plugin filters via search params.
> fix(webui): Apply metric filters to eval results via url search params

- site/docs/providers/google.md
- src/providers/google/ai.studio.ts
- src/providers/google/live.ts
- src/providers/google/types.ts
- src/providers/google/util.ts
- src/providers/google/vertex.ts
- test/providers/google/ai.studio.test.ts
- test/providers/google/util.test.ts
> fix: use `model` role for gemini ai studio models

- site/src/plugins/docusaurus-plugin-og-image/index.js
This PR cleans up OG image generation logs in `site/src/plugins/docusaurus-plugin-og-image/index.js` to avoid printing image paths or base64 content.\n\n- Log booleans only (image provided/loaded/valid)\n- Keep build behavior unchanged (no caching)\n\nThis reduces noisy logs and avoids leaking large base64 strings in CI.
> docs(og-image): avoid logging full image/base64; use boolean presence only

- site/src/plugins/docusaurus-plugin-og-image/index.js
- Add asset caching for logo and font files to avoid repeated file I/O
- Implement image caching with size-specific keys to prevent reprocessing
- Add conservative parallel processing (batch size 2) for CPU-intensive SVG rendering
- Reduce logging verbosity during builds
- Improve error messages with specific file paths
- Remove unused functions to clean up codebase
- **7.3% faster** OG image generation verified in CI (14.5s improvement: 3m 18s → 3m 3s)
- **40.9% faster** generation verified on test subset locally
- Eliminates redundant file reads for shared assets (logo/font loaded once vs 400+ times)
- Conservative batch processing prevents overwhelming CPU with parallel SVG rendering
- Intelligent caching reduces memory pressure
The main bottlenecks were:
1. **File I/O**: Reading the …
> docs(site): optimize OG image generation performance

- src/commands/eval.ts
- src/share.ts
- test/commands/eval.test.ts
We want to default sharing to on if the user is connected to cloud
> feat: Auto-share if connected to cloud

- src/providers/google/util.ts
- test/providers/google/util.test.ts
> fix(provider): prioritize explicit projectId config over google-auth-library

- src/onboarding.ts
- test/commands/view.test.ts
- test/onboarding.test.ts
This addresses usability issues like #5534 since the "spacebar to select" behavior is non-intuitive.  People are hitting enter, which just goes with the default (OpenAI)
> chore(onboarding): make provider menu single select

- src/app/src/pages/evals/components/EvalsDataGrid.tsx
> chore(webui): improve delete confirmation dialog styling

- site/docs/releases.md
Added comprehensive August 2025 release notes covering:
- GPT-5 and Claude Opus 4.1 model support
- Google AI Studio default provider configurations  
- xAI Grok Code Fast model integration
- Cloud sharing for team collaboration
- Path management for scan history
- Enhanced authentication (certificates, signatures)
- Medical off-label use detection plugin
- Unverifiable claims detection plugin
- MCP Agent testing example for tool calls
- HuggingFace dataset fetching improvements
- AI-powered HTTP configuration auto-fill
- Credential sanitization for security
All content is factually grounded based on August 2025 git commits.
> docs(site): add August 2025 release highlights

- src/app/src/pages/eval/components/DownloadMenu.test.tsx
- src/app/src/pages/eval/components/DownloadMenu.tsx
still not the most beautiful but way better
> chore: improve design of eval download dialog

- src/app/src/pages/redteam/report/components/FrameworkCard.test.tsx
- src/app/src/pages/redteam/report/components/FrameworkCard.tsx
- src/app/src/pages/redteam/report/components/FrameworkCompliance.test.tsx
- src/app/src/pages/redteam/report/components/FrameworkCompliance.tsx
- src/app/src/pages/redteam/report/components/Report.tsx
sort by plugin performance and deeplink to table with plugin filter
> chore: improvements to framework compliance cards

- examples/amazon-bedrock/promptfooconfig.qwen.yaml
- site/docs/providers/aws-bedrock.md
- src/providers/bedrock/index.ts
- test/providers/bedrock/index.test.ts
This PR adds comprehensive support for Alibaba's Qwen models to the AWS Bedrock provider, enabling users to leverage these powerful coding and reasoning models through promptfoo.
- **Complete Qwen Model Support**: All 4 model variants with proper TypeScript types
- `qwen.qwen3-coder-480b-a35b-v1:0` (480B MoE coding specialist)  
- `qwen.qwen3-coder-30b-a3b-v1:0` (30B MoE efficient coding)
- `qwen.qwen3-235b-a22b-2507-v1:0` (235B MoE general purpose)
- `qwen.qwen3-32b-v1:0` (32B dense model)
- **Advanced Capabilities**:
- 🔧 **Tool Calling**: OpenAI-compatible function calling support
- 🧠 **Hybrid Thinking**: `showThinking` parameter for reasoning transparency  
- 📝 **Chat Formatting**: Proper message parsing and response handling
- 🏷️ **Inference Profiles**: Application inference profile …
> feat: add support for Qwen models in AWS Bedrock provider

- examples/e2b-code-eval/metrics.py
- examples/e2b-code-eval/promptfooconfig.yaml
- examples/e2b-code-eval/swe_runner.py
docs: refine and extend the e2b sandbox evaluation guide with improved examples and fixes
- Added more comprehensive test cases, including unsafe code detection and failing scenarios, to demonstrate sandbox protections and validation.
- Improved documentation structure and readability in `evaluate-e2b.md` with clearer summaries and headings.
- Replaced placeholder `model_call_patch()` with a minimal working example in `swe_runner.py`.
- Updated `metrics.py` to handle non-serializable errors (e.g., ExecutionError) by safely converting them for JSON output.
- Enhanced safety detection and clarified example workflows for patch generation, key management, and automation.
- Aligned all headings and sections for consistency and better guide navigation.
> docs: refine and extend e2b sandbox evaluation guide with improved examples and fixes

- src/assertions/index.ts
Tidying while working on https://github.com/promptfoo/promptfoo/pull/5785.
> chore(internals): make `runAssertion` easier to read by moving const outside function scope

- site/docusaurus.config.ts
- site/src/components/GitHubStars/index.tsx
- site/src/components/GitHubStars/styles.module.css
- site/src/theme/NavbarItem/ComponentTypes.tsx
> chore: show # github stars on site
