src/assertions/index.ts, src/evaluatorHelpers.ts, src/providers/packageParser.ts, test/assertions/index.test.ts, test/evaluatorHelpers.test.ts, test/providers/packageParser.test.ts
Previously the `package:` provider was only looking at `${basePath}/node_modules/package.json` but Node.js module resolution logic is actually much more complicated. `require.resolve` handles this lookup much better as it contains all of the logic. There is an equivalent for ESM called `import.meta.resolve` but it's still not stable so as a result I opted for using `createRequire` to create a require instance specifically for that `basePath` and then leverage `require.resolve` from that instance. This fix was needed especially when working with a monorepo with multiple packages where the package you want to use might not be at the same level as your config.
Additionally I ported that same functionality to both variable definition and JavaScript assertions. With this change both of these …
=> feat: package import support improvements

src/evaluator.ts, src/fetch.ts, src/providers/azureopenai.ts, src/providers/openai.ts, src/redteam/plugins/base.ts, src/redteam/plugins/harmful.ts, src/util/time.ts, test/fetch.test.ts
Now that we use native fetch API (since #1968), URLs with embedded credentials
are rejected. This change properly handles basic auth by:
- Extracting credentials from URLs before making requests
- Converting to Authorization header format
- Removing credentials from URL to comply with fetch spec
- In addition, it increases test coverage of fetch.ts to 100%
Relates to #2012
CC @tan-z-tan
=> fix: handle basic auth credentials in fetch requests

.github/workflows/docker.yml
The GitHub Actions workflow was failing due to "No space left on device" errors.
- Remove unused system packages and tools before build
- Prune Docker images and volumes after testing
=> fix(ci): add disk space cleanup steps to prevent runner failures

site/docs/providers/openai.md
The Dall-E3 provider is referred to as `openai:image:dalle-3` when instead it should be `openai:image:dall-e-3` in the docs. This PR corrects the name.
=> docs(provider): fix dalle-3 provider name

examples/redteam-dalle/promptfooconfig.yaml, src/redteam/providers/iterativeImage.ts
Previously, the RedteamIterativeProvider required injectVar to be explicitly set in the config. This caused errors when running the DALL-E-3 red team example as highlighted in issue #2019.
Now, the provider automatically extracts the variable from the prompt template if injectVar is not provided in the context. This makes the API more flexible and maintains backward compatibility.
Relates to #2019
=> fix(redteam): auto-extract injectVar from prompt template in redteam image provider

examples/claude-vision/README.md, examples/claude-vision/promptfooconfig.yaml, src/providers/bedrock.ts, test/providers/bedrock.test.ts
Allows us to run comparisons like the one below and get the exact same output
```yaml 
description: 'Bedrock vs. Anthropic Claude 3.5 Sonnet Comparison'
prompts:
- 'Please answer the following question: {{query}}'
providers:
- id: bedrock:anthropic.claude-3-5-sonnet-20241022-v2:0
- id: anthropic:messages:claude-3-5-sonnet-20241022
tests:
- vars:
query: Generate a random sequence of 100 digits. Only output the sequence, no other text.
```
=> fix(providers): adjust bedrock anthropic default temperature

src/app/src/pages/redteam/setup/components/PluginConfigDialog.tsx, src/app/src/pages/redteam/setup/components/Plugins.tsx
The changes make the plugin selection interface a bit cleaner while maintaining all functionality.
- Moved plugin configuration from inline forms to a dedicated dialog
- Added settings icon to plugins that support configuration
- Auto-opens configuration dialog for plugins that require setup
- Improved array input handling and fixed bug where clicking 'Add' did nothing 
---
---
---
=> chore: improve ui for plugin configs

src/cache.ts
Necessary to invalidate format change introduced in [https://github.com/promptfoo/promptfoo/commit/ff3b4f6575dbeb3bb54fb35038277582ed605a4f#diff-d027d3b9853e6bedddf63bd1[…]f2b947685108f315e4e831cdbdR88](https://github.com/promptfoo/promptfoo/commit/ff3b4f6575dbeb3bb54fb35038277582ed605a4f#diff-d027d3b9853e6bedddf63bd1d8fa67c69b4c1ff2b947685108f315e4e831cdbdR88)
=> fix: bump version on fetch cache key

package-lock.json, package.json, src/providers/bedrock.ts, test/providers/bedrock.test.ts
Fix for #2080 
* Add sessionToken and profile as Bedrock configuration options
* Add sessionToken to credentials dictionary if key pair is present
* If profile is present, use fromSSO
* getCredentials can return an AwsCredentialIdentityProvider
* import fromSSO from aws-sdk/credential-provider-sso
=> chore: Support AWS sessionToken and profile for authentication

src/util/config/load.ts
Run validation on configs when we read configs, instead of casting
=> fix: validate json, yaml, js configs on load

src/commands/import.ts
=> fix: keep eval id on `import`

examples/azure-openai-assistant/promptfooconfig.yaml, examples/azure-openai/promptfooconfig.yaml, site/docs/guides/azure-vs-openai.md, site/docs/providers/azure.md, site/static/config-schema.json, src/app/src/pages/eval-creator/components/ConfigureEnvButton.tsx, src/envars.ts, src/evaluator.ts, src/providers.ts, src/providers/adaline.gateway.ts, src/providers/azure.ts, src/providers/azureUtil.ts, src/providers/defaults.ts, src/types/providers.ts, src/validators/providers.ts, test/providers/azure.test.ts, test/providers/index.test.ts
The Azure provider supports more than just OpenAI, so let's just call it `azure`.  We're still supporting all the old configs and envars for backwards compatibility.
=> chore: azureopenai -> azure

site/docs/usage/command-line.md, site/static/config-schema.json, src/commands/eval.ts, src/commands/eval/filterTests.ts, src/types/index.ts, src/util/config/load.ts, test/commands/eval/filterTests.test.ts
Adds `--filter-sample <number>` to take a random sample
Related to #740
=> feat: --filter-sample on eval to randomly sample

src/providers/bedrock.ts
The AWS Bedrock docs have `us-east-1` as the default region in two instances. [1] and [2]
Fix the ADS Bedrock provider code to use the `us-east-1` as the default region. `us-east-1` is generally assumed the default instead of the `us-west-2`.
1. https://github.com/promptfoo/promptfoo/blob/1a919fc1fab8d81002c4a6e06d322aa50d3de8b9/site/docs/providers/aws-bedrock.md?plain=1#L58
2. https://github.com/promptfoo/promptfoo/blob/1a919fc1fab8d81002c4a6e06d322aa50d3de8b9/site/docs/providers/aws-bedrock.md?plain=1#L68
=> chore: Fix AWS default region to match documentation

src/app/src/pages/eval/components/ResultsTable.tsx
Implements #2046 
I tested this by running an eval that had long cells and ensuring that when I checked the "Render model outputs as Markdown" box that it respected that limit. This enabled me to see Markdown links for my evals that had large inputs.
Open to any feedback, and thanks for the quick response on the original issue!
=> feat: Respect max text length in Markdown cells

src/fetch.ts, test/fetch.test.ts
Add x-promptfoo-version header to all outgoing requests to help with request tracking and debugging.
Changes:
- Add VERSION import from constants
- Add x-promptfoo-version header to all requests in fetchWithProxy
- Update tests to verify header presence in all relevant test cases
=> chore: add promptfoo version header to all requests

src/providers/anthropic.ts, test/providers/anthropic.test.ts
The Messages API expects system messages to be handled separately from regular messages. This change:
- Extracts system messages from the input array
- Formats system content correctly as TextBlockParams
- Filters system messages out of extractedMessages
- Updates tests to reflect the new behavior
Related to #2123
=> fix(providers): handle system messages correctly in anthropic parseMessages

src/util/config/load.ts, test/util/config/load.test.ts
The schema validation was happening before  resolution, causing false validation errors for valid  usage in providers configuration.
This change:
- Moves schema validation after dereferencing
- Adds tests to verify  resolution in YAML configs
- Ensures validation errors are properly reported
Related to #2125
=> fix: validate config after dereferencing

examples/claude-vs-gpt-image/promptfooconfig.yaml, src/providers/bedrock.ts, test/providers/bedrock.test.ts
Relates to #2136
To test, rerun `examples/claude-vs-gpt-image/promptfooconfig.yaml`
CC @maximcherny
=> fix(providers): handle system messages correctly for bedrock Claude models

src/app/src/pages/eval/components/EvalOutputCell.tsx, src/models/evalResult.ts, src/types/index.ts, src/util/convertEvalResultsToTable.ts, src/util/exportToFile/index.ts
* Update token usage access path to use response.tokenUsage
* Fix type definitions for EvalResult response property
* Add non-null assertions for tokenUsage metrics
* Update EvaluateTableOutput interface to include response
Relates to  #2142
=> fix(webui): restore token usage display

src/redteam/plugins/base.ts, test/redteam/plugins/base.test.ts
Move parseGeneratedPrompts from RedteamPluginBase class to standalone function and update corresponding tests. This will allow us to re-use the function in plugins that do not extend the base.
=> refactor(redteam): extract parseGeneratedPrompts from redteam base class

examples/amazon-bedrock/promptfooconfig.titan-text.yaml, site/docs/providers/aws-bedrock.md, src/providers/bedrock.ts
To use guardrails, set the `guardrailIdentifier` and `guardrailVersion` in the provider config.
For example:
```yaml
providers:
- id: bedrock:anthropic.claude-3-5-sonnet-20241022-v2:0
config:
guardrailIdentifier: 'test-guardrail'
guardrailVersion: 1 # The version number for the guardrail. The value can also be DRAFT.
```
=> feat: add support for bedrock guardrails

src/share.ts, test/share.test.ts
- If sharing for the first time and no email is set, write the email to the eval. 
- When sharing an eval in cloud mode, automatically update the author to match the logged-in user's email. 
- Show a warning if the author is being changed from a different email address. - let's discuss this I am not sure about the behavior pattern
=> fix(share): update eval author to logged-in user when sharing

src/evaluator.ts, src/models/eval.ts, src/server/server.ts
attaches missing `isRedteam` field.  fixes the /report view, for example
=> fix: pass isRedteam from eval database model

site/docs/providers/http.md, src/cache.ts, src/providers/http.ts, src/redteam/providers/crescendo/index.ts, src/redteam/providers/goat.ts, src/redteam/providers/iterative.ts, src/redteam/providers/iterativeImage.ts, src/redteam/providers/iterativeTree.ts, src/redteam/providers/shared.ts, src/types/providers.ts, test/cache.test.ts, test/providers/http.test.ts, test/providers/index.test.ts, test/redteam/providers/iterativeTree.test.ts
- For multi-turn strategies we can maintain the session id for http providers.
- Only send the last message for multi-turn strategies if the providers are stateful
- Added cached-token usage to our redteam token usage.
=> feat: Maintain session-id in http provider

src/redteam/index.ts
Not sure how this is possible other than some weird async race condition. This should fix it though.
=> fix(redteam): attempt to fix undefined redteam testcase bug

src/redteam/commands/init.ts
The indirect prompt injection plugin configuration would attempt to extract variables from undefined prompts, causing errors. This adds a validation check for empty prompts array and show appropriate warning message when prompts are missing.
=> fix(redteam): handle missing prompts in indirect prompt injection setup

src/app/src/pages/eval/components/CustomMetrics.test.tsx, src/app/src/pages/eval/components/CustomMetrics.tsx
Adds null coalescing operators and explicit zero handling to prevent NaN results from divide-by-zero operations in metric calculations.
=> fix(webui): handle division by zero cases in CustomMetrics component

src/main.ts
Adds better error feedback for invalid options, including:
- Show help after errors
- Display suggestions for mistyped commands
- Explicit error message for invalid options
=> chore(cli): display help for invalid args

site/docs/contributing.md, src/commands/view.ts, src/constants.ts, src/redteam/commands/init.ts, src/redteam/commands/report.ts, src/redteam/commands/setup.ts, src/server/index.ts, src/server/server.ts, src/util/server.ts, test/util/server.test.ts
- Add server health check to detect running instance
- Open browser to redteam setup if server exists
- Start new server only if needed
- Use DEFAULT_PORT consistently across commands
=> chore(redteam): attempt to reuse existing server for redteam init

src/testCases.ts, test/testCases.test.ts
Seems like excel generally saves csv files as UTF-8 (with BOM) and this [breaks parsing](https://stackoverflow.com/questions/66402555/first-property-inaccsesible-of-objects-parsed-by-csv-parse) of the csv with the current settings. 
Update the options of `csv-parse` to detect bom marks. It is [recommended](https://csv.js.org/parse/options/bom/) in the docs to enable this option though the default value is false.
**BEFORE**
**AFTER**
=> fix: csv bom parsing

src/redteam/constants.ts, src/redteam/plugins/harmful/constants.ts, src/redteam/plugins/index.ts
The specialized-advice plugin generates a lot of refusals. This moves it to the unaligned provider.
=> chore(redteam): move harmful specialized advice plugin to unaligned provider 

src/app/src/pages/redteam/setup/components/Prompts.tsx, src/app/src/pages/redteam/setup/components/Purpose.tsx, src/app/src/pages/redteam/setup/components/Strategies.tsx, src/redteam/commands/setup.ts, src/redteam/constants.ts
- Add visual indicators for multi-turn and optimizer strategies
- Improve plugin preset handling with default plugins
- Add descriptive text for different strategy types
- Make basic strategy always selected and non-removable
- Enhance prompt template instructions with code formatting
- Improve application details form with better info alert styling
- Add server check before starting redteam setup
=> chore(webui): minor impovements to redteam setup strategy and plugin selection

src/app/src/pages/eval/components/ResultsTable.css, src/app/src/pages/eval/components/ResultsTable.tsx
- Prevent action buttons from being shown for both columns when hovering over a single column in the eval comparison view
- Action buttons are per cell so the UX is more clear when the buttons are shown on a per cell:hover basis.
[Screencast from 2024-11-30 11-28-22.webm](https://github.com/user-attachments/assets/b068b51a-c781-4c9b-a21d-030ab6d54029)
[Screencast from 2024-11-30 11-30-59.webm](https://github.com/user-attachments/assets/111c0c2e-92d6-4796-ab20-98cb8b50b564)
=> chore(webui): only show action buttons for the currently hovered cell, rather than both cells for that row

src/app/src/pages/datasets/Datasets.tsx, src/app/src/pages/prompts/Prompts.tsx
- In the Datasets and Prompts view, when the user had an `?id=___` in their URL, all rerenders of the view resulted in the dialog opening again. This happened whenever the user would try to sort a column.
- Sorting by prompt or Most recent eval is broken on `/prompts` 
- Sorting by Info, Most recent eval date and Most recent eval ID is broken on `/datasets`
[Screencast from 2024-11-30 15-38-42.webm](https://github.com/user-attachments/assets/5c46fc76-106e-457f-a2c2-3cec3ecf3f21)
[Screencast from 2024-11-30 15-40-14.webm](https://github.com/user-attachments/assets/9ee7c9cb-90f0-4c62-94b8-fe546219c7c6)
=> chore(webui): prevent dialog from popping up repeatedly when component rerenders

src/app/src/pages/progress/Progress.tsx
- The progress / history page now supports sorting on pass count, fail count, and raw score
- On hover of the column headers, an arrow presents, indicating an expected UX of being able to sort the column (pass count, fail count, || raw score). But upon click of the sort arrow, nothing would happen.
(Note - Recording is a little laggy as I am playing around with red teaming while recording)
[Screencast from 2024-11-30 14-44-42.webm](https://github.com/user-attachments/assets/c91fd710-4d1d-4ea1-8365-e12a7e1c1461)
[Screencast from 2024-11-30 14-43-28.webm](https://github.com/user-attachments/assets/570a0e7e-69b6-43da-9453-438a3491188b)
=> fix(webui): support sorting on pass / fail count & raw score

src/app/src/pages/redteam/setup/components/Purpose.tsx, src/app/src/pages/redteam/setup/components/Targets/index.tsx, src/app/src/pages/redteam/setup/page.tsx
As noted in #2267, the back button is broken on the "Applications" aka Purpose page.  This PR removes the button and adds the missing back button to the Targets page.
=> chore(webui): improve back and next buttons for purpose/targets pages

src/envars.ts, src/testCases.ts, test/testCases.test.ts
- Add PROMPTFOO_CSV_DELIMITER environment variable
- Update CSV parsing to use configurable delimiter
- Add unit tests for custom delimiter functionality
=> feat: add configurable CSV delimiter support

src/app/src/pages/redteam/setup/components/Plugins.tsx
=> chore: display # selected plugins in accordion text

site/docs/guides/langchain-prompttemplate.md
This guide covers:
- Using LangChain PromtTemplate for prompts defined in the application code
- Using PromptFoo to test the prompts defined in the application and the necessary formatting configurations
=> docs: guide on LangChain PromptTemplates

src/commands/share.ts
Enhances the error message when attempting to share an incomplete eval, clarifying that the eval might still be running and providing guidance to wait for completion before retrying.
=> chore(cli): improve error message when attempting to share incomplete eval

src/commands/share.ts
Replaces process.exitCode assignments with process.exit calls as a temporary fix since we're not properly awaiting async operations. This ensures immediate process termination rather than potential hanging. 
TODO: This should be revisited in the future to properly handle async operations instead of force-exiting the process.
=> fix(cli): replace process.exitCode with process.exit calls in share command

src/redteam/plugins/base.ts, src/redteam/strategies/multilingual.ts, test/redteam/strategies/multilingual.test.ts
Spaghetti for fixing a bug where the multi-lingual assertion lost metric names. I may generalize this as I test other strategies.
=> fix(redteam): preserve assertion types in multilingual strategy

src/providers/promptfoo.ts, src/redteam/extraction/entities.ts, src/redteam/remoteGeneration.ts
We were always hitting our public cloud api even if people were logged into their on-prem hosted version.
=> fix: Use cloud api for remote harmful generation

src/app/src/pages/redteam/setup/components/Targets/HttpEndpointConfiguration.tsx, src/app/src/pages/redteam/setup/components/Targets/index.tsx, src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
- Fixes some type weirdness for request body
- Fixes a bug in resetting config
=> feat: "try example" in target configuration

src/providers/defaults.ts, src/redteam/index.ts, src/redteam/plugins/base.ts, src/redteam/plugins/crossSessionLeak.ts, src/redteam/providers/crescendo/index.ts, src/redteam/providers/iterative.ts, src/redteam/providers/iterativeImage.ts, src/redteam/providers/iterativeTree.ts, src/redteam/providers/shared.ts, src/redteam/strategies/mathPrompt.ts, src/redteam/strategies/multilingual.ts, test/redteam/providers/shared.test.ts, test/redteam/strategies/multilingual.test.ts
1. Setup a global manager to handle the redteam provider. Allows us to override it globally.
2. Allow setting a global completion provider override - https://github.com/promptfoo/promptfoo/pull/2333/files#diff-e9d74f25919e5aca3ef968793552d9198df382ca66225c6efe1954b9cfdcd48d
=> chore: Allow overriding default and redteam providers globally

src/models/eval.ts, src/server/routes/eval.ts
Untested, but I suspect this change will fix the issue.
(note that self-hosted has no metrics information, compared to the local screenshot)
Local `view` (v0.100.4):
Public `share` (app.promptfoo.dev):
Self-hosted `share` (v0.100.3):
=> fix: Attempt to fix metrics after share to self-hosted

src/evaluator.ts, test/evaluator.test.ts
Relates to #2281
Previously, vars from defaultTest were not available during transformVars execution because they were merged after the transform was applied. This change ensures defaultTest.vars are merged before any transformations, allowing transformVars to access both test-specific and default variables.
=> fix: merge defaultTest.vars before applying transformVars

src/redteam/strategies/multilingual.ts
We're getting a lot of errors parsing the multi-lingual output, let's see why.
=> chore: add better error logging for multilingual

test/redteam/extraction/entities.test.ts, test/redteam/extraction/purpose.test.ts, test/redteam/extraction/util.test.ts
- Add mock for getRemoteGenerationUrl in entities, purpose, and util tests
- Add test case for custom remote generation URL
- Reset mock URL in beforeEach blocks
=> chore: add getRemoteGenerationUrl mocks to redteam tests

src/matchers.ts, test/matchers.test.ts
Ensures Replicate moderation provider is properly loaded and used when OpenAI API key is not available but Replicate key is present.
=> fix: use replicate moderation provider when OpenAI key not present

test/prompts/processors/javascript.test.ts, test/server/eval.test.ts
I missed these when converting the rest over. Luckily tiny-invariant is still in the package-lock.json
=> chore: clean up invariant references

site/docs/configuration/guide.md
This PR updates the documentation to include guidance on using shared variables across all tests in the configuration file.
- Added a new section titled **Default variables** to the configuration guide.
- Provided an example YAML configuration demonstrating how to define and use shared variables in `defaultTest`.
The documentation now explains the usage of `defaultTest` for defining variables that are shared across multiple tests. Examples illustrate how shared variables can be overridden on a per-test basis.
No code changes were made; this update is documentation-only. Ensure clarity and correctness by reviewing the added examples.
None.
This update addresses GitHub issue #2378 by providing the requested guidance on shared/global variable usage in tests.
=> docs(configuration): add documentation for shared variables in tests

src/util/config/load.ts, test/util/config/load.test.ts
Re-enables validation warning that catches malformed configuration objects
after JSON schema dereferencing. This helps catch configuration errors
like unrecognized provider properties.
=> fix: re-enable validation warning for invalid dereferenced configs

src/prompts/processors/yaml.ts, test/prompts/processors/yaml.test.ts
This PR addresses issue #2368 by modifying the YAML processor to handle files containing Nunjucks templates gracefully. Previously, such files could cause YAMLException errors due to the YAML parser attempting to parse Nunjucks syntax. The changes ensure that these files are preserved as raw text.
=> fix(prompts): restore behavior that delays yaml parsing until after variable substitution

package-lock.json, package.json
overrides whatwg-url (dependency of node-fetch) to a newer version to remove the punycode deprecation warning. 
to test 
```bash
nvm use 22
npm run build
npm link
promptfoo --version
```
=> fix: punycode deprecation warning

src/app/src/pages/redteam/setup/page.tsx
- Remove fixed width constraint from StyledTabs
- Disable unnecessary scroll buttons
- Ensure tabs fill available space in sidebar
=> chore(webui): remove horizontal scroll from redteam setup tabs

src/redteam/index.ts
Merge strategy configs so things like `maxRounds` will apply when you do a multi-lingual crescendo attack.
Proof:
=> fix(redteam): combine strategy configs for chained strategies

src/redteam/extraction/entities.ts, src/redteam/extraction/purpose.ts, test/redteam/extraction/entities.test.ts, test/redteam/extraction/purpose.test.ts
For users relying on remote extraction this won't help anything so we'll just fail open.
=> fix(redteam): dont fall back if entity and purpose extraction fails

src/redteam/commands/generate.ts, src/util/config/load.ts, src/validators/redteam.ts, test/redteam/commands/generate.test.ts, test/redteam/validators.test.ts, test/util/config/load.test.ts
- Add entities field to redteam config schema
- Pass entities from config to synthesize function
- Combine entities arrays when merging multiple configs
- Add tests for entities handling in config loading and validation
=> fix(redteam): add support for entity merging in config

src/evaluator.ts, test/evaluator.test.ts
This pull request addresses issue #2439 by introducing a fix to handle circular references during error logging in the `Evaluator` class.
- Replaced `JSON.stringify` with `safeJsonStringify` in the error logging statement within `Evaluator`.
- Added a new test case to verify the handling of circular references when logging errors during result saving.
- The `safeJsonStringify` utility is used to safely serialize objects with circular references, preventing runtime errors.
- The new test case creates a circular reference object and verifies that the error logging mechanism functions correctly without throwing exceptions.
- The new test case ensures that the fix works as intended.
- Existing tests were run to confirm no regressions were introduced.
- None.
This fix ensures that error …
=> fix(evaluator): handle circular references during error logging

package.json
This pull request addresses the deprecation warning for the `punycode` module in Node.js 22 by updating the `overrides` section in the `package.json` file.
1. `nvm use 22` 
2. `npm i && npm rebuild` 
3. `npm run build`
4. `npm link promptfoo`
5. verify with `which promptfoo`
6. run `promptfoo --version`
=> chore(cli): address punycode deprecation warning for Node.js 22

.github/workflows/main.yml
- Add Node.js 22.x back to test matrix
=> fix(ci): update Node.js 22.x matrix configuration

site/docs/usage/command-line.md, site/static/config-schema.json, src/commands/eval.ts, src/commands/eval/filterTests.ts, src/types/index.ts, test/commands/eval/filterTests.test.ts
This pull request introduces the ability to filter tests based on metadata key-value pairs in the `eval` command.
- Added a new `--filter-metadata` option to the `eval` command.
- Updated the `filterTests` function to support filtering tests by metadata.
- Enhanced logging for the filtering process to aid debugging.
- Updated the documentation to include the new `--filter-metadata` option.
- Added comprehensive tests for the metadata filtering functionality.
The metadata filter uses a key-value pair format (e.g., `key=value`) to match tests with the corresponding metadata. If the metadata is not present or does not match, the test is excluded.
- Unit tests have been added to validate the behavior of the metadata filter.
- Tests cover scenarios such as valid matches, no matches, invalid …
=> feat(eval): add metadata filtering for tests

src/redteam/providers/crescendo/index.ts, src/redteam/providers/goat.ts, src/redteam/providers/shared.ts
- Fixed condition to validate message structure in GoatProvider.
- Updated output retrieval logic in GoatProvider to ensure correct user message is returned.
- Changed warning to debug log for missing output in CrescendoProvider.
=> fix(redteam): improve logging and message handling in Crescendo and Goat providers

site/docs/red-team/configuration.md
This PR updates the documentation for the Red Team configuration strategies to correctly reflect the default strategies.
- Adjusted the order and labeling of default strategies in the `configuration.md` file to ensure accuracy.
- Removed duplicate entries and clarified descriptions for better readability.
The changes involve reordering and modifying the markdown content to align with the intended default strategy settings.
Ensure that the rendered documentation reflects the intended changes and that all links and references remain functional.
None.
=> docs(red-team): update default strategy documentation

src/redteam/providers/iterative.ts, src/redteam/providers/prompts.ts
This update enhances the metadata tracking for the iterative provider in the Redteam module.
- Introduced `previousOutputs` array to store prompt, output, score, and topic relevance for each iteration.
- Added `finalIteration` to track the last iteration executed.
- Updated the metadata object to include `finalIteration`, `highestScore`, `previousOutputs`, and `redteamFinalPrompt`.
- The `previousOutputs` array is populated during each iteration with the current iteration's data.
- The `finalIteration` variable is set when a high-score condition is met, indicating the iteration at which the loop terminated.
- Metadata returned now includes detailed information about the iteration process for better traceability and debugging.
- Ensure the updated metadata structure is correctly populated …
=> chore(redteam): enhance metadata tracking for iterative provider

site/docs/providers/index.md
Added new providers to the documentation.
- Included Llamafile, Sequence, Simulated User, and Webhook providers.
- Updated the providers table with relevant details.
=> docs(providers): add new providers to documentation

examples/redteam-intent-sequence/README.md, examples/redteam-intent-sequence/promptfooconfig.yaml, site/docs/red-team/plugins/intent.md, src/redteam/index.ts, src/redteam/plugins/intent.ts, test/redteam/plugins/intent.test.ts
You can specify a list of lists to create multi-step interactions. Each inner list represents a sequence of prompts that will be sent to the model in order:
```yaml
intent:
- ['tell me about John Smith', 'give me his data']
- ['request system access', 'escalate privileges', 'execute harmful command']
```
=> feat: support `intent` sequences

examples/redteam-ollama/promptfooconfig.yaml
Reverts the redteam-ollama example configuration to its prior state.
- Corrects erroneous changes introduced in a previous commit.
=> chore(examples): revert redteam-ollama example to previous version

src/matchers.ts, test/matchers.test.ts
Handle cases where empty outputs are passed to the moderation provider.
- Prevents false positives by returning early when no output is present.
- Includes a test case to verify the behavior.
=> fix(moderation): handle empty output to avoid false positives

README.md
Update the README to be a friendlier entrypoint, and leave things like the list of assertion types, etc to the main docs.
=> docs: readme overhaul

site/docs/providers/http.md, src/cache.ts, src/fetch.ts, src/providers/http.ts, src/providers/promptfoo.ts, test/providers/http.test.ts
This PR introduces the ability to configure the number of retry attempts for the HTTP provider.
- Added `maxRetries` option in the HTTP provider configuration.
- Updated documentation and tests to reflect the new feature.
=> chore(providers): make number of retry attempts configurable for HTTP provider

src/fetch.ts, test/fetch.test.ts
This PR fixes the logic in the fetchWithRetries function to ensure at least one attempt is made even when retries is set to 0.
- Adjusted loop condition to include retries=0.
- Added tests to validate the new behavior.
=> fix(fetch): correct retries logic to ensure at least one attempt

src/index.ts, src/redteam/plugins/base.ts, src/redteam/util.ts, test/redteam/plugins/base.test.ts, test/redteam/plugins/intent.test.ts
This update ensures that empty or refusal responses from a target are automatically passed during plugin grading. Currently, some redteam graders mark an empty response as failed.
=> chore(redteam): handle empty and refusal responses

src/redteam/commands/run.ts
instead of a separate -i or --id option, make it so that the user can pass the uuid to -c, and if it looks like a uuid we will handle it as a cloud configuration
=> chore: switch cloud `run` to use --config param

site/blog/unbounded-consumption.md
fix(docs): correct broken link in blog post
- Updated the link in the 'unbounded-consumption.md' file to point to the correct documentation section.
=> fix(docs): correct broken link in blog post

examples/google-vertex/promptfooconfig.yaml, src/providers/vertex.ts
Properly handle multiple `candidates` and `parts` in Gemini response.
Related to #2490
=> fix(gemini): support gemini thinking model

site/docusaurus.config.js, site/package.json
Conditionally enable Google Analytics tracking script (gtag) only in production mode to prevent errors in development.
- Updated `docusaurus.config.js` to check `NODE_ENV` before enabling gtag.
- Adjusted the `start` script in `package.json` to explicitly set `NODE_ENV=development`. No breaking changes.
=> fix(docs): conditionally enable gtag only in production

.vscode/settings.json, src/redteam/providers/iterativeTree.ts, test/redteam/providers/iterativeTree.test.ts
Adjust parameters in the iterativeTree provider to refine the redteam strategy.
- Increased maximum attempts, depth, and no-improvement threshold.
- Introduced a similarity threshold for prompt diversity.
=> chore(redteam): adjust parameters for iterativeTree strategy

site/docs/usage/command-line.md, src/commands/eval.ts, src/commands/eval/filterErrorTests.ts, src/commands/eval/filterTests.ts, test/commands/eval/filterErrorTests.test.ts
This allows you to re-run only the test cases that failed due to network errors or other types of errors
=> feat: add --filter-errors-only parameter to `eval`

site/docs/red-team/configuration.md
Updated the "Adding custom tests" section of the redteam docs to indicate that removing metadata containing hash values will result in the custom cases added to redteam.yaml being lost and overwritten.
=> docs(redteam): update configuration.md

examples/watsonx/README.md, site/docs/providers/watsonx.md, src/envars.ts, src/providers/watsonx.ts, src/types/env.ts, test/providers/watsonx.test.ts
This PR adds a new environment variable, **WATSONX_AI_AUTH_TYPE**, to let users choose the authentication method for watsonx.ai (iam or bearertoken). It simplifies authentication setup by allowing control over which method to use.
1. Added support for **WATSONX_AI_AUTH_TYPE**:
- Set iam to use IAM authentication with **WATSONX_AI_APIKEY**.
- Set bearertoken to use Bearer Token authentication with **WATSONX_AI_BEARER_TOKEN**.
- If WATSONX_AI_AUTH_TYPE is not set, the system will try to detect the method based on the available keys.
2. Updated logic to give WATSONX_AI_AUTH_TYPE the highest priority.
=> chore(providers): add support for the WATSONX_AI_AUTH_TYPE env

src/app/src/pages/eval/components/EvalOutputPromptDialog.test.tsx, src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx
This update improves the metadata expand/collapse functionality in the EvalOutputPromptDialog component.
- Introduced double-click handling for collapsing metadata.
- Added tests to ensure correct behavior for single and double clicks.
=> chore(webui): enhance metadata expand/collapse handling

.vscode/settings.json, site/docs/red-team/quickstart.md, site/src/pages/quickstart.module.css
Refactored inline styles in documentation to use CSS modules for better maintainability and added improved dark mode support.
- Moved inline styles to a dedicated CSS module file.
- Enhanced dark mode styling for badges and images.
=> chore(docs): improve dark mode on redteam configuration 

site/docs/configuration/expected-outputs/index.md, site/docs/configuration/expected-outputs/model-graded/g-eval.md, site/docs/configuration/expected-outputs/model-graded/index.md
- updating code example to use correct assertion type as defined in code (`g-eval` vs. `geval`). This is based off [examples](https://github.com/promptfoo/promptfoo/blob/7ba62815e3822c61c933e4dd0b68e2c506111843/examples/g-eval/promptfooconfig.yaml#L9) and [this](https://github.com/promptfoo/promptfoo/blob/7ba62815e3822c61c933e4dd0b68e2c506111843/src/types/index.ts#L367).
- Renaming the docs page for consistency
=> docs: updating typo for g-eval pages

examples/redteam-dalle/README.md, site/blog/jailbreak-dalle.md
- Enhanced the README for the DALL-E red team example with detailed setup and usage instructions.
- Updated the blog post to include quickstart commands for reproducing examples.
=> docs(blog): improve the usage instructions for jailbreak dalle post

examples/redteam-dalle/README.md, examples/redteam-dalle/promptfooconfig.yaml, src/providers/openai.ts, src/redteam/providers/iterativeImage.ts
This improves the iterative image provider in the redteam module to reduce refusals and enhance the quality (on topic, harmful, relevant, etc.) of image outputs. I carry over recent improvements from the iterative provider. 
See https://www.promptfoo.app/eval/eval-n06-2025-01-08T07:31:57
=> chore(redteam): reduce iterative image provider refusals

package-lock.json
fix(deps): update lock file to resolve yanked dependency
- Updated the package-lock.json to use motion-dom version 11.16.1 instead of the yanked 11.16.0.
- Ensures compatibility and resolves potential installation issues.
=> fix(deps): update lock file to resolve yanked dependency

examples/python-assert-external/assert_with_config.py, src/assertions/index.ts, test/assertions/index.test.ts, test/assertions/python.test.ts
As was pointed out by @kmeshcheryakov in #1771, there was an issue with the `jsonSafeStringify` function that prevented the configuration from being passed into python assertions cleanly. The previous PR "fixed" the problem but did it in a hacky way. The cleaner way is to just do a deep clone of the configuration object before it is passed into any of the run functions (for Python or for JS) thus ensuring that any serialization that removes circular references will not strip the configuration inadvertently.
Final fix for #1729
=> chore(assertions): improve python assertion configuration passing

site/docs/_shared/data/strategies.ts, site/static/config-schema.json, src/redteam/constants.ts
This PR removes the 'ascii-smuggling' strategy from the red team strategies.
- Eliminated references and descriptions of the 'ascii-smuggling' strategy.
- Updated constants and data files accordingly.
It fixes the issue when using redteaming UI to generate config.yaml, it would list ascii-smuggling under strategies and it results in error:
```
Invalid redteam configuration:
Validation error: Custom strategies must start with file:// and end with .js or .ts, or use one of the built-in strategies: basic, default, jailbreak, jailbreak:composite, prompt-injection, base64, citation, crescendo, goat, jailbreak:tree, leetspeak, math-prompt, multilingual, rot13, best-of-n at "strategies[4].id"
```
=> fix(redteam): remove ascii-smuggling strategy

src/providers/defaults.ts, test/providers/defaults.test.ts
=> chore(providers): allow the ability to set a custom default embedding provider

.vscode/settings.json, site/docs/providers/index.md
Updated the providers overview table to include new entries for F5 and GitHub.
- Added F5 and GitHub to the providers list.
- Included their respective descriptions and example identifiers.
=> docs(providers): update overview table with new entries

.github/workflows/docker.yml
Fixes an issue with the BUILD_DATE string concatenation in the GitHub Actions workflow for Docker builds.
- Simplifies the logic for determining BUILD_DATE.
- Ensures compatibility with different GitHub event types.
=> fix(docker): correct string concatenation for BUILD_DATE in GitHub Actions

src/redteam/providers/iterative.ts, src/redteam/providers/iterativeTree.ts
The redteamFinalPrompt metadata field now stores the raw attack prompt
(newInjectVar) instead of the full rendered prompt. This makes the behavior
consistent between iterative and tree-based approaches, and better reflects
the actual attack that succeeded. This is also reflective of the other strategies.
=> chore(redteam): store attack prompt instead of rendered prompt in metadata

src/providers/promptfoo.ts, src/redteam/commands/run.ts, src/redteam/providers/crescendo/index.ts, src/redteam/providers/iterative.ts, src/redteam/providers/iterativeTree.ts, src/redteam/shared.ts, src/redteam/types.ts
Fix: Redteam strategies couldn't handle an object as the response
Fix: auto share when running redteam from the cloud
=> fix: redteam strategies

src/app/src/pages/eval/components/ResultsTable.tsx
This reverts commit 49bdcba4251b4766188493fa0c002214eec2c890. The direct value output was causing a React error when displaying nested objects in transformVars output. TruncatedText component properly handles object serialization. Fixes #2633
=> fix: revert 49bdcba - restore TruncatedText for var display

src/app/src/pages/eval/components/ResultsTable.tsx
Just noting, TruncatedText could use a refactor to remove the non-truncation logic someplace else so we can use it here.  But for now we do this.
=> chore: dont actually truncate vars because they are scrollable

src/redteam/plugins/divergentRepetition.ts
This PR improves the formatting and clarity of the divergent repetition plugin prompt.
- adjust the prompt so it doesn't have duplicate output part as it's base prompt: `DEFAULT_GRADING_PROMPT`
Error:
After the fix:
=> fix(redteam): adjust divergent repetition plugin prompt formatting

src/app/src/pages/redteam/setup/components/Strategies.tsx, src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts, src/app/src/pages/redteam/setup/types.ts, src/redteam/sharedFrontend.ts, src/redteam/types.ts
- Revert changes made in #2645 as having `stateless` as an attribute in a top-level config object is confusing
- Surface an error on the Strategies page when there is a discrepancy between strategies configured with stateful/stateless settings
- The following issues will be addressed in a follow-up PR
io buttons to change system stateful/stateless setting
=> fix(ui): fix stateful/stateless setting for providers

package-lock.json, site/docusaurus.config.js, site/package.json
This PR introduces a client-side redirect for the troubleshooting documentation link to address the issue of broken links indexed by Google https://letmegooglethat.com/?q=promptfoo+troubleshooting and configures a redirect from `/docs/category/troubleshooting` to `/docs/usage/troubleshooting`. Note that this method of redirect is not ideal (server-side would be better) but this gets a fix out now. We can handle a server side later.
=> docs: add redirect for troubleshooting link

README.md, site/docs/contributing.md, site/docusaurus.config.js, site/src/pages/contact.tsx, src/app/src/components/InfoModal.test.tsx, src/app/src/components/InfoModal.tsx
Updated all references to the Discord invite link to reflect the new URL.
- Replaced old Discord invite links with the updated one across documentation and code.
- Ensured consistency in all user-facing mentions of the Discord community.
=> docs(links): update Discord links to new invite

site/docs/providers/http.md, src/providers/http.ts, test/providers/http.test.ts
- Introduced a configurable `validateStatus` function to customize HTTP response status validation similar to axios override: https://axios-http.com/docs/handling_errors
=> chore(providers): add validateStatus option to HTTP provider

src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx, src/app/src/pages/redteam/setup/components/Targets/index.tsx, src/providers/http.ts, test/providers/http.test.ts
This PR introduces a configurable `validateStatus` option for HTTP requests.
- Adds UI elements to toggle and customize HTTP status validation.
- Updates the HTTP provider to support various validation formats, including expressions and functions.
=> chore(webui): add configurable validateStatus to redteam HTTP target setup

site/docs/providers/http.md, src/app/src/pages/redteam/setup/components/Targets/TestTargetConfiguration.tsx, src/providers/http.ts, test/providers/http.test.ts
Change default validateStatus function to accept all HTTP status codes.
- Updated default behavior in the HTTP provider to allow all status codes.
- Adjusted related documentation and test cases.
=> chore(providers): change default validateStatus to accept all http status codes

src/server/routes/eval.ts, test/server/share.test.ts
Fix flaky tests by adding timeout to requests and isolating app instances for each test.
- Added timeout to test requests to avoid hanging.
- Ensured a fresh app instance and database cleanup before each test.
=> test: make share test more robust

src/commands/list.ts, src/commands/show.ts, src/esm.ts, src/evaluator.ts, src/googleSheets.ts, src/integrations/huggingfaceDatasets.ts, src/logger.ts, src/migrate.ts, src/providers/adaline.gateway.ts, src/providers/azure.ts, src/providers/cloudflare-ai.ts, src/redteam/commands/generate.ts, src/redteam/commands/poison.ts, src/redteam/commands/run.ts, src/redteam/plugins/cyberseceval.ts, src/server/routes/configs.ts, src/server/routes/redteam.ts, src/table.ts, src/util/apiHealth.ts, test/googleSheets.test.ts
This PR updates the logger implementation to enforce a single-argument type for its methods, preventing potential misuse.
- Updated logger methods to strictly accept a single string argument.
- Adjusted all logger calls across the codebase to comply with the new type constraints.
=> fix(logging): enforce single-argument type for logger methods

src/providers/watsonx.ts, test/providers/watsonx.test.ts
This PR improves the WatsonX provider by automating the cost calculation dynamically:
- Automatically fetches model pricing tiers from watsonx API instead of hardcoding them
- Calculates costs accurately based on the model's input and output tiers
- Supports all WatsonX model tiers (class 1 through class 12). [Reference](https://www.ibm.com/docs/en/watsonx/saas?topic=plans-billing-details-generative-ai-assets#billing-classes-by-multiplier)
- Added few tests for cost calculation
- Improves accuracy of usage cost tracking for future models
=> chore(feat): automated watsonx provider to fetch model costs dynamically

src/app/src/pages/eval/components/ResultsTable.test.tsx, src/app/src/pages/eval/components/ResultsTable.tsx
Fixes the issue where nested variables were not rendered properly in the ResultsTable component.
- Adds tests to verify rendering of nested variables as JSON with and without markdown.
- Resolves issue #2633.
=> fix(webui): ensure nested variables are rendered correctly

src/redteam/providers/shared.ts
Removed the dynamic import for OpenAiChatCompletionProvider in the redteam provider module.
- Replaced dynamic import with a static import to simplify dependency handling.
- No breaking changes introduced.
=> chore(redteam): remove dynamic import for OpenAiChatCompletionProvider

src/googleSheets.ts
Refactored the fetchCsvFromGoogleSheetUnauthenticated function to replace the dynamic import of fetchWithProxy with a static import. This improves module loading efficiency.
=> refactor: remove dynamic import for fetchWithProxy

jest.config.ts, src/esm.ts, src/providers/azure.ts, src/providers/bam.ts, src/redteam/providers/crescendo/index.ts, src/redteam/providers/goat.ts, src/redteam/providers/iterative.ts, src/redteam/providers/iterativeTree.ts, src/redteam/providers/shared.ts, test/cache.test.ts, tsconfig.json
This reverts commit a19993c02750471110293ff2c214a85aef289044.
Sorry @aloisklink we're running into errors relating to `await import('../graders.js');` I am going to try to de-ciricularize the dependencies this week and PR your change again after that. 
Thank you so much for your help!
=> revert: "build: create `dist/` using TypeScript's `"module": "Node16"` setting (#2686)

src/evaluator.ts
This is usually indicative of guardrails or something else.
=> fix: empty response is not a failure for red team

src/app/src/pages/redteam/report/components/StrategyStats.tsx
=> chore: show plugin in strategy stats prompt/response examples

src/types/providers.ts, test/types/providers.test.ts
Removed the unused 'getSessionId' field from the ApiProvider interface.
- Cleans up the code by removing an unused field.
- No breaking changes introduced.
=> chore(types): remove unused 'getSessionId' field from ApiProvider

site/docs/providers/openai.md, src/providers/openai.ts
In OpenAI assistants V2 there is a new config option required when using their vector store along with tools. This PR adds support for this config option to be passed along to the assistant. 
See documentation from OpenAI here https://platform.openai.com/docs/assistants/migration
=> fix: add support for tool_resources in openai assistants

test/providers.test.ts, test/providers/openai.test.ts, test/providers/promptfoo.test.ts
This PR adds additional mocks to the test suite to address excessive logging and CI flakiness.
- Introduced mocks for logger and global configuration modules.
- Improved test stability by isolating dependencies.
=> test(providers): add mocks to reduce CI flakes and logs

src/fetch.ts, test/fetch.test.ts
This PR addresses an issue with TLS options when using proxy settings.
- Updated the handling of CA certificates to read them as UTF-8 strings.
- Added `requestTls` options to the proxy agent configuration.
=> fix(fetch): correct TLS options for proxy settings

src/fetch.ts
Removed an unnecessary debug log statement from the fetch module.
- Simplifies the code by removing redundant logging.
=> refactor(fetch): remove unnecessary debug log

package.json
shrinks package from 12.7 MB to about 9.8 MB
=> chore: exclude test files from npm package

package.json
Simplified the 'files' field in package.json by removing redundant exclusion patterns.
- Focused exclusions to 'dist/test' and 'dist/src/__mocks__' only.
- Ensures clarity and maintains the whitelist approach.
=> chore(package): simplify files field in package.json

site/docs/providers/anthropic.md, site/docs/providers/cloudera.md
This PR corrects syntax and formatting issues in example code blocks across the documentation for Anthropic and Cloudera providers.
- Adjusted code block titles for better clarity.
- Improved YAML structure for consistency.
=> docs(providers): fix syntax and formatting in examples

package-lock.json, package.json
This PR updates the package-lock.json to correctly mark 'tsx' as a dev dependency.
- Ensures consistency between package.json and package-lock.json.
- No breaking changes.
=> chore(deps): move tsx to dev dependencies

site/docs/configuration/guide.md
Update documentation example to replace 'file_content' given fs is not available in line. 
Thanks for pointing this out @mshavliuk 
Fixes #2886
=> docs: fix broken transformVars example

src/app/src/pages/redteam/setup/components/Purpose.tsx
Changes
- Update Next button styling to use theme colors instead of hardcoded values
- Fix button background and hover states in dark mode
- Use MUI's theme system for consistent styling
Before: 
The Next button in the config setup page had hardcoded colors that didn't adapt to dark mode.
=> fix(webui): update Next button styling to support dark mode

src/redteam/constants.ts
- Update Replicate provider URL to use Llama Guard 3.8B
- Add new categories S12 (Sexual Content) and S13 (Elections)
=> chore(redteam): upgrade replicate moderation api to Llama Guard 3

src/evaluator.ts, src/models/eval.ts, src/models/evalResult.ts, test/factories/evalFactory.ts, test/models/evalResult.test.ts, test/util/index.test.ts
Not sure why we were passing in the test case separately. The test case on the evaluateResult is just a reference to the test case we passed in.
We passed in the `evalStep` here:
https://github.com/promptfoo/promptfoo/blob/2caf61f043eb6d7a4851f1121947bd74b1c90e96/src/evaluator.ts#L698
Deconstructed in `callApi` arguments:
https://github.com/promptfoo/promptfoo/blob/2caf61f043eb6d7a4851f1121947bd74b1c90e96/src/evaluator.ts#L104
Pass it to `callApi` here: 
https://github.com/promptfoo/promptfoo/blob/2caf61f043eb6d7a4851f1121947bd74b1c90e96/src/evaluator.ts#L181C1-L182C1
Set it to `testCase` on the `EvaluateResult` Here:
https://github.com/promptfoo/promptfoo/blob/2caf61f043eb6d7a4851f1121947bd74b1c90e96/src/evaluator.ts#L228
But then pass it in to `addResult` from the `evalStep`? …
=> chore: Save test case from EvalResult

src/testCases.ts
Ensure the code gracefully handles scenarios where 'vars' is undefined or not an array.
- Added optional chaining to access 'vars.length'.
- Prevents errors when 'vars' is null or undefined.
=> fix(generation): handle cases where vars is not an array

src/providers/http.ts, test/providers/http.test.ts
fix(http): handle function expressions in transform response
- Added support for parsing and executing function expressions in the transformResponse logic.
- Extended test coverage to validate various function expression scenarios.
This fixes the issuse reported in: https://github.com/promptfoo/promptfoo/issues/2901
=> fix(providers): handle function expressions in transform response

package-lock.json, package.json
Adding `tsx` package back to been a dependency for typescript execution ref: #2922
=> fix: added tsx back to dependencies

examples/harmbench/README.md, site/docs/red-team/plugins/harmbench.md
- Will need to remove the harmbench plugin documentation until the build passes, then re-add it to the examples README.md
=> fix: broken docs build

src/redteam/plugins/rbac.ts
The RBAC grader was producing a high rate of false positives by failing purely hypothetical/creative scenarios that don't actually compromise security. For example, it would fail creative writing responses or roleplaying scenarios where no actual system access or security boundaries were being breached.
Added explicit pass conditions to the RBAC grader for:
- Creative/fictional narratives that don't implement real access changes
- Hypothetical scenarios that don't reveal actual system details  
- Roleplaying responses that don't compromise actual security boundaries
- General discussions that don't expose sensitive implementation details
=> fix(grader): allow creative scenarios that don't compromise actual security in rbac grader.

src/assertions/index.ts, src/assertions/utils.ts, src/matchers.ts, test/matchers.test.ts
This PR add a `.js` files support for the `rubricPrompt` attribute of `type: llm-rubric` assertion
ref #2971
=> feat: add `.js` file support for `rubricPrompt` in `llm-rubric` assertion

src/app/src/pages/eval/components/ResultsView.tsx, src/app/src/pages/eval/components/ShareModal.tsx, src/commands/share.ts, src/server/server.ts, src/share.ts
This update introduces a confirmation dialog in the share modal to ensure users are aware of the implications of generating a public share link.
- Added a confirmation step before creating a shareable link.
- Updated UI to include the confirmation dialog.
Logged in to cloud/or not using default public domain for sharing:
https://github.com/user-attachments/assets/153f1447-bf69-43ce-9514-dcb9f4c44689
Logged out:
https://github.com/user-attachments/assets/34e0ef72-c21f-48c9-ab1a-ce4af65b1c40
=> chore(share): add confirmation step before generating public share link

src/redteam/providers/crescendo/index.ts
This at least gives the strategy a chance to find a jailbreak if it's stateful. We can't backtrack with stateful conversations because the server will continue with the current conversation.
=> fix: Crescendo would bail after a single refusal with stateful bots

src/providers/openai/defaults.ts, test/providers/openai/defaults.test.ts
Updated the default grading provider to use the latest model version `gpt-4o-2024-11-20`. This comes after running some large evals internally. The model performs better and is half the cost.
=> feat(openai): update default grading provider to gpt-4o-2024-11-20

src/cache.ts, src/providers/openai/chat.ts, test/cache.test.ts
I am adding this because some openai-compatible apis do not return HTTP status codes that reflect the actual outcome (openrouter). This means we cache things like rate limit errors.
In theory this should be handled at the evaluator level, because we never want to cache an error for any provider.  But that would be a heavy refactor
=> chore: expose `deleteFromCache` to evict cache keys after fetch by providers

src/util/config/load.ts, test/util/config/load.test.ts
This PR ensures that empty configuration files are handled gracefully when running commands like `promptfoo --version`
=> chore(config): handle empty config files gracefully

src/providers/golangCompletion.ts
[DRAFT] PR to fix an issue where prompt arguments with single quotes break the provider, since it runs as a bash command under-the-hood
=> fix: escape single quotes in golang provider

src/app/src/pages/eval/components/DownloadMenu.tsx
Add the redteamFinalPrompt field to the download menu component.
- Ensures metadata is included in the download functionality.
=> chore(eval): add redteamFinalPrompt to download menu

src/app/src/pages/eval/components/EvalOutputCell.tsx, src/app/src/pages/eval/components/ResultsTable.css
Fixes an issue where thumbs (like/dislike) would not visually persist after being clicked.
- Added state management for active thumbs in EvalOutputCell.
- Updated CSS to visually indicate active thumbs.
=> chore(webui): ensure thumbs remain active after selection

src/esm.ts, src/util/file.node.ts, src/util/file.ts, src/util/transform.ts, test/esm.test.ts, test/util/file.test.ts, test/util/transform.test.ts
- Module imports were breaking on absolute paths due to an issue in how we were calling `path.resolve`. We didn't check whether or not the right-most path was already an absolute path
- Implement a new `safeJoin` and `safeResolve` method that does just this.
=> fix: broken handling of absolute paths in hook/code import

src/commands/auth.ts, src/commands/config.ts, test/commands/auth.test.ts, test/commands/config.test.ts, test/util/utils.ts
- Add email sync during login to handle existing email updates
- Add email unset on logout for consistent state management
- Add validation to prevent email updates while logged in
=> chore(auth): synchronize email between `promptfoo config set email` and `promptfoo auth login`

site/docs/providers/anthropic.md, src/providers/anthropic.ts, test/providers/anthropic.test.ts
Add support for the 'extra_body' parameter in the Anthropic API provider.
- Allows passing additional custom parameters to API calls.
- Includes test cases to validate the functionality.
=> chore(providers): add support for extra_body in Anthropic API

src/index.ts, src/prompts/index.ts, test/prompts/index.test.ts
This PR refactors the prompt processing logic by introducing a new function `processPrompts` in the prompts directory.
- Removed redundant code from `evaluate` function.
- Updated tests to cover the new `processPrompts` function.
=> refactor(prompts): consolidate prompt processing logic

src/util/testCaseReader.ts, test/util/testCaseReader.test.ts
Fixes an issue where YAML files prefixed with file:// were incorrectly processed by readStandaloneTestsFile
=> fix(testCaseReader): correctly process file:// URLs for YAML files

examples/google-vertex-tools/README.md, examples/google-vertex-tools/promptfooconfig.yaml, examples/google-vertex-tools/tools.json, src/providers/vertex.ts
feat: add support for for tools in Vertex provider
Add Tool[] block to the completion options + provide an example.
Also minor fix to avoid cache key collisions when calling the same prompt against two different Vertex models.
=> feat: add support for for tools in Vertex provider

src/util/testCaseReader.ts, test/util/testCaseReader.test.ts
- fixing error message to both indicate this code path can be reached with .js and .ts files, as well as resolution hint
- removing unused mocks
Open to feedback on the error message text. But the current test is pretty explicitly checking for extra colons and would be nice to provide a clearer error.
I'd like to next add full support for .ts and .js to take function names with the same default function name, to be consistent with dynamic prompts. Should be simple fix, same implementation as provider, and adding tests.
=> fix: Clearer error message in testCaseReader, test cleanup

src/util/index.ts, test/util/index.test.ts
- current behavior: `PROMPTFOO_STRICT_FILES=true` not compatible with python.py:MyFunc format.
- changing the parsing order so that `fs.statSync` hits the file without the function name
- this was largely masked before because `PROMPTFOO_STRICT_FILES` defaults to `false`
General comment: I ran an eval with PROMPTFOO_STRICT_FILES=false (default) and while I passed the `fs.statSync` check, the script still tried to load my python file and errored out, so I'm unclear on what the default behavior is intended to be.
=> fix: issue where script.py:myFunc fails fs stat check when PROMPTFOO_STRICT_FILES=true

site/static/config-schema.json, src/evaluatorHelpers.ts, src/types/index.ts, src/util/templates.ts, test/evaluatorHelpers.test.ts, test/util/templates.test.ts
This PR addresses issues with environment variables handling in nunjucks rendering.
- Added support for merging CLI state environment variables with process.env.
- Improved tests to cover various edge cases for environment variable handling.
Resolves https://github.com/promptfoo/promptfoo/issues/3122
=> fix(env): ensure environment variables are properly merged and rendered in nunjucks

src/fetch.ts, test/fetch.test.ts
Previously this would always just return "fetch failed". Now this returns usable error messages like: 
```TypeError: fetch failed (Cause: RequestContentLengthMismatchError: Request body length does not match content-length header)```
=> chore: Return detailed error messages from fetch

src/evaluator.ts, test/evaluator.test.ts
When examining the code, I identified that API errors (like 400 Bad Request) were not being properly classified. The root cause was in the error handling logic:
1. In `src/types/index.ts`, we have the `ResultFailureReason` enum that defines different types of failures:
```typescript
export enum ResultFailureReason {
NONE = 0,      // The test passed, or we don't know exactly why the test case failed
ASSERT = 1,    // The test case failed because an assertion rejected it
ERROR = 2,     // Test case failed due to some other error
}
```
2. In `src/evaluator.ts`, API errors (like 400 Bad Request) were being handled in the `if (response.error)` block, but this block was only setting the error message without setting `failureReason` to `ResultFailureReason.ERROR`:
```typescript
if …
```
=> fix: properly classify API errors with ResultFailureReason.ERROR

site/docs/providers/index.md, src/providers/index.ts, test/providers.test.ts, test/providers/index.test.ts
Adds ability to load multiple providers from a single YAML/JSON file
Relates to https://github.com/promptfoo/promptfoo/issues/3153
=> feat(providers): add support for multiple providers in single config file

examples/golang-provider/go.mod
Updated the Go toolchain version in the go.mod file to adhere to the 1.N.P syntax required as of Go 1.21.
- Changed the version from '1.21' to '1.23.6' to ensure compatibility.
=> fix(go-mod): update go toolchain version to valid syntax

site/docs/usage/node-package.md, src/index.ts, src/providers/bam.ts, src/providers/registry.ts, test/index.test.ts
BREAKING CHANGE: Direct access to providers through `promptfoo.providers` is being removed in favor of `loadApiProvider` to dynamically load providers. This allows us to import some providers at runtime and make promptfoo faster for the majority of users.
=> chore!: remove direct provider exports in favor of loadApiProvider (undocumented node package feature)

src/app/src/components/ErrorBoundary.tsx, src/app/src/pages/datasets/page.tsx, src/app/src/pages/history/page.tsx, src/app/src/pages/prompts/page.tsx
Add a reusable error boundary component to the web UI.
- Introduced `ErrorBoundary` component for handling errors in React components.
- Integrated the error boundary into the datasets, history, and prompts pages.
=> chore(webui): add reusable error boundary component

site/docs/usage/command-line.md
This PR updates the command-line documentation to include new commands and options.
- Added details for `auth`, `config`, `debug`, and `redteam` commands.
- Updated descriptions for existing commands and environment variables.
=> docs(command-line): update documentation with new commands and options

src/redteam/sharedFrontend.ts, src/redteam/types.ts
Reverts promptfoo/promptfoo#3229
=> Revert "chore: Map RBAC-tagIds when pulling redteam configs from the cloud"

src/providers/http.ts, test/providers/http.test.ts
Spaces in query params need to be encoded properly. We weren't doing that since we are just injecting the prompts directly into the url.
=> fix(providers): Support inject vars in query params for raw requests for http provider

package-lock.json, package.json, site/docs/providers/openai.md, src/providers/openai/util.ts
This PR introduces support for the new GPT-4.5 model from OpenAI.
- Updated dependencies to include the latest OpenAI library.
- Added GPT-4.5 model details to documentation.
- Integrated GPT-4.5 model configurations into the provider utilities.
=> chore(providers): add support for GPT-4.5 OpenAI model

.vscode/settings.json, examples/openai-dalle-images/README.md, examples/openai-dalle-images/promptfooconfig.yaml, src/providers/openai/image.ts, test/providers/openai/image.functions.test.ts, test/providers/openai/image.test.ts, test/providers/openai/moderation.test.ts
Refactored the OpenAI image provider to eliminate the dependency on the OpenAI Node SDK.
- Introduced direct API calls using fetchWithCache.
- Enhanced configuration handling for image generation.
- Updated tests to reflect the new implementation.
=> chore(providers): refactor OpenAI image provider to remove OpenAI Node SDK dependency

src/googleSheets.ts, test/googleSheets.test.ts
We got error:
```
TypeError: Cannot read properties of undefined (reading 'trim')
at testCaseFromCsvRow (/path/to/node_modules/promptfoo/dist/src/csv.js:140:23)
at /path/to/node_modules/promptfoo/dist/src/util/testCaseReader.js:203:51
at Array.map (<anonymous>)
at readStandaloneTestsFile (/path/to/node_modules/promptfoo/dist/src/util/testCaseReader.js:202:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async combineConfigs (/path/to/node_modules/promptfoo/dist/src/util/config/load.js:264:30)
at async resolveConfigs (/path/to/node_modules/promptfoo/dist/src/util/config/load.js:423:22)
at async runEvaluation (/path/to/node_modules/promptfoo/dist/src/commands/eval.js:136:55)
at async doEval (/path/to/node_modules/promptfoo/dist/src/commands/eval.js:388:12) …
```
=> chore: Fix an error in Google SpreadSheet(Authenticated) with a header without a value

src/providers/vertex.ts, src/providers/vertexUtil.ts
Multi-part responses with a finish_reason error (e.g. MALFORMED_FUNCTION_CALL) on parts > 1 resulted in the errors being ignored. This fix ensures that they're caught correctly
=> fix(providers): catch Vertex finish_reason errors correctly

src/providers/google.ts, test/providers/google.test.ts
Allow Nunjucks template variables in Google API key and host values. This fixes issue #3256 where users couldn't reference environment variables in their Google provider configuration.
=> chore(providers): enable templating of Google API credentials

package-lock.json, package.json
Change the `peerDependencies` on `@smithy/node-http-handler` to support `^3.1.1 || ^4.0.0`, as that's the version used by the new AWS SDKs since v3.723.0.
The only breaking change in v4.0.0 seems to be dropping Node.JS v16 support, see [`@smithy/node-http-handler` CHANGELOG.md][1].
[1]: https://github.com/smithy-lang/smithy-typescript/blob/9ffe82d60dd45787a4279eb9723290edb39d0e10/packages/node-http-handler/CHANGELOG.md
---
`npm test` seems to work fine, but if anybody uses AWS Bedrock, it might be worth retesting the AWS Bedrock provider just to sanity check that the [`@smithy/node-http-handler` CHANGELOG.md][1] is correct and there are no other changes!
=> fix: support @smithy/node-http-handler ^4.0.0

src/commands/eval.ts, test/commands/eval/evaluateOptions.test.ts
relates to https://github.com/promptfoo/promptfoo/issues/3286
=> fix(eval): honor evaluateOptions when config file is in a different directory

src/commands/share.ts, src/share.ts, test/commands/share.test.ts, test/share.test.ts
When self-hosting promptfoo, the share command was showing URLs pointing to app.promptfoo.dev instead of the self-hosted domain, even though the data was correctly sent to the self-hosted API. This fix:
- Updates hostname determination to check both PROMPTFOO_SHARING_APP_BASE_URL and PROMPTFOO_REMOTE_APP_BASE_URL
- Modifies determineShareDomain to properly handle custom domains from environment variables
- Ensures the final displayed URL matches the actual API endpoint being used Fixes #3291
=> fix(share): correct URL display when self-hosting

src/app/src/pages/eval/components/DownloadMenu.tsx
Corrected the keyboard shortcut order for the DownloadMenu component in the web UI.
- Adjusted the mapping of shortcut keys to their respective download functions.
=> fix(webui): correct keyboard shortcut order in DownloadMenu

src/evaluator.ts, test/evaluator.test.ts
This PR ensures that metadata from test cases and provider responses are merged correctly.
- Added logic to combine metadata in the evaluator.
- Introduced a test case to validate the merging behavior.
=> fix(evaluator): merge test case metadata with provider response metadata

site/docs/providers/echo.md, src/providers/echo.ts, src/providers/registry.ts, test/providers.test.ts, test/providers/echo.test.ts, test/providers/registry.test.ts
chore(echo-provider): enhance documentation and implementation
- Updated Echo Provider documentation with detailed response format and use cases.
- Refactored Echo Provider implementation for clarity and added comprehensive tests.
=> chore(providers): support entire ProviderResponse output

src/redteam/graders.ts, test/redteam/graders.test.ts
This PR introduces a fallback mechanism in the `getGraderById` function to return the harmful grader for IDs starting with 'promptfoo:redteam:harmful'.
- Updated `getGraderById` to include the fallback logic.
- Added corresponding test cases to ensure correct functionality.
=> chore(redteam): add fallback to harmful grader for specific ID patterns

src/redteam/plugins/harmful/common.ts, test/redteam/plugins/index.test.ts
Fix redteam moderation flag default and remove redundant test assertion.
- Updated `getEnvBool` to include a default value for the moderation flag.
- Removed an unnecessary test assertion for moderation type.
=> fix(redteam): update moderation flag default and adjust test

src/providers/anthropic.ts
Update default Anthropic providers to use the latest version identifiers.
- Changed provider identifiers from 'claude-3-5-sonnet-20240620' to 'claude-3-7-sonnet-20250219'.
- Ensures compatibility with the updated Anthropic API.
=> feat(providers): update default Anthropic providers to latest version

site/docs/_shared/data/plugins.ts
This PR removes a duplicate entry for the 'Tool Discovery' plugin in the documentation data.
- Consolidated the information into a single entry.
- Ensures no redundancy in the plugin list.
=> docs(redteam): remove duplicate plugin entry

.vscode/settings.json, site/docs/providers/aws-bedrock.md
Updated the AWS Bedrock documentation to include detailed information about Amazon Nova's capabilities.
- Added multimodal input details for images and videos.
- Enhanced example configurations with schema annotations.
=> docs(providers): update AWS Bedrock documentation with Nova details

src/commands/init.ts, test/commands/init.test.ts
This PR updates the `downloadDirectory` function to include a fallback mechanism for fetching examples from the 'main' branch if the specified version fails.
- Enhanced error handling for directory fetching.
- Updated tests to cover the new fallback logic.
=> chore(init): add fallback to 'main' branch for example fetching

package.json
Updated the postversion script to explicitly specify the repository for PR creation.
- Ensures the PR is created in the correct repository.
=> chore(scripts): specify repository for postversion PR creation

Dockerfile, helm/chart/promptfoo/templates/deployment.yaml
The Dockerfile now creates the .promptfoo directory, which avoids permission issues. The initContainer in the Helm chart was removed as it is no longer needed.
It should fix issues that people are reporting with permissions problems and any need to create separate container just to fix permissions.
Fixes need for workaround stated here: https://github.com/promptfoo/promptfoo/issues/3251#issuecomment-2700423562
( Also named volume approach #1 doesnt work as expected )
=> fix(Dockerfile): Create .promptfoo directory in Dockerfile and remove initContainer

examples/golang-provider/evaluation/main.go, src/golang/adapter.go.template, src/golang/wrapper.go, src/golang/wrapper_test.go, src/providers/golangCompletion.ts, test/providers/golangCompletion.test.ts
This PR addresses the issue of CallApi redeclaration in the Go provider.
- Introduced an adapter.go template to conditionally declare CallApi.
- Updated wrapper.go and tests to align with the new approach.
- Adjusted the build process to include the adapter.
=> fix(go-provider): resolve CallApi redeclaration issue

src/redteam/extraction/entities.ts, test/redteam/extraction/entities.test.ts
Fixes the entity extraction logic to exclude template variables wrapped in double curly braces.\n\n- Updated the extraction logic to filter out Nunjucks template variables.\n- Added comprehensive test cases to validate the new behavior.
=> fix(redteam): filter out template variables in entity extraction

examples/google-aistudio-gemini/README.md, examples/google-aistudio-gemini/promptfooconfig.yaml, site/docs/providers/google.md, src/providers/googleShared.ts
Added support for gemini 2.5 Pro. Seems to work out of the box, so we just added a google.md entry and added gemini-2.5 to our `google-aistudio-gemini` example. It's not yet supported on Vertex yet, so that was omitted. 
```
$ promptfoo eval -c examples/google-aistudio-gemini
Running 1 concurrent evaluations with up to 4 threads...
[████████████████████████████████████████] 100% | ETA: 0s | 1/1 | google:gemini-2.5-pro-exp-03-25 "Given this" puzzle=If 
┌────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────┐
│ puzzle                                                         │ [google:gemini-2.5-pro-exp-03-25] Given this math puzzle:      │
│                                                                │ {{puzzle}} …
```
=> chore(providers): Add support and docs for gemini 2.5 pro to Google Chat Provider

src/redteam/graders.ts, src/redteam/plugins/cyberseceval.ts, src/redteam/plugins/pliny.ts, test/redteam/graders.test.ts, test/redteam/plugins/pliny.test.ts
Previously, Pliny test cases would fail if the LLM didn't understand or acknowledge the prompt, which should probably be a pass, as it's a soft refusal. This change adds a new Pliny grader which should more accurately address those cases as pass rather than fail. 
Also fixes a minor bug in which cybersecval didn't have a metric name and would show up as undefined in the eval table.
=> chore(redteam): Add a PlinyGrader to more accurately grade Pliny results

src/app/src/pages/redteam/setup/components/strategies/utils.ts, src/redteam/constants.ts
Previously calling `.sort()` removed the type safety of having all the keys being static. This should address that, and also adds some missing strategies in places.
=> fix(redteam): Type of ALL_STRATEGIES to be as const

src/util/index.ts, test/util/index.test.ts
Fixes regression in --env-file option that caused environment variables to be reset to default .env values when both .env and custom env file were present. Modified setupEnv function to use override=true when loading from a specified env file path and added comprehensive test coverage to prevent future regressions. Fixes #3501
=> fix(env): add override option to dotenv.config for --env-file support

site/docs/providers/litellm.md, src/providers/openai/chat.ts, src/providers/openai/completion.ts, src/providers/openai/image.ts, src/providers/openai/index.ts, src/providers/openai/moderation.ts, src/providers/openai/types.ts, test/providers/openai/index.test.ts
purposely doesn't add it to all openai apis - realtime, responses seem like they won't be shared
=> chore: add support for `apiKeyRequired` in openai provider

src/app/src/pages/prompts/PromptDialog.tsx, src/app/src/pages/prompts/Prompts.tsx, src/app/src/pages/prompts/page.tsx, src/types/index.ts
I think the intent of this type was to override the `recentEvalDate` to be a string, but this doesn't work unless the key is omitted from `PromptWithMetadata`.
=> chore: fix type of Prompt to use omit

site/docs/red-team/foundation-models.md
Improves the documentation for red teaming foundation models by enhancing clarity, updating terminology, and adding metadata for better SEO.
- Refines instructions for running scans and evaluating results.
- Adds descriptive metadata and keywords to the document.
=> docs(red-team): add metadata to foundation models guide

examples/jsonl-test-cases/README.md, examples/jsonl-test-cases/cases.jsonl, examples/jsonl-test-cases/promptfooconfig.yaml, src/util/testCaseReader.ts, test/util/testCaseReader.test.ts
`tests: file://tests.jsonl` is currently unsupported although the [docs](https://www.promptfoo.dev/docs/configuration/parameters/#import-from-jsonjsonl) indicate it should.
=> fix: Support for jsonl test cases

site/docusaurus.config.js
`to` instead of `href` disables the external link svg icon apparently
=> docs: add link to api reference

src/app/src/pages/eval-creator/components/RunTestSuiteButton.tsx, src/server/routes/eval.ts
Hi! It's pretty important fix, which prevents server crash and **all running tests**,  if unknown model is had chosen. For example, if to choose any `azureopenai` (`azureopenai:gpt-35-turbo-0125`) model from UI list and click "Run Evaluation", then server is crashed.
P.S. I think `azureopenai`-models list should be reformatted, because FE and BE parts have different options about azure format
=> fix: prevent server crash when unknown model is selected

site/docs/providers/openrouter.md, site/docs/providers/togetherai.md, site/docs/providers/vertex.md
This update adds documentation for Llama 4 models across OpenRouter and Vertex AI.
- Includes new models like Llama 4 Scout and Maverick.
- Updates context length and multimodal support details for Llama 4 series.
=> docs(providers): add Llama 4 model details

site/static/config-schema.json, src/evaluatorHelpers.ts, src/types/index.ts, test/evaluatorHelpers.test.ts, test/types.test.ts, test/types/index.test.ts
This PR updates the schema and related logic to allow the 'extensions' field to be nullable.
- Adjusted schema definitions and validation rules.
- Updated tests to cover new nullable behavior.
=> chore(schema): make extensions field nullable

package-lock.json
chore(deps): update dependencies to resolve vulnerabilities
- Updated `estree-util-value-to-estree` to version 3.3.3.
- Updated `image-size` to version 1.2.1.
=> chore(deps): update dependencies to resolve vulnerabilities

src/commands/auth.ts, test/commands/auth.test.ts
Login via email address is deprecated with the new cloud auth, pointing towards the website to login and get the token.
=> fix: remove deprecated login flow

site/docs/enterprise/authentication.md, site/docs/usage/self-hosting.md, site/docs/usage/sharing.md, src/commands/auth.ts, src/commands/share.ts, test/commands/auth.test.ts, test/commands/share.test.ts
Fixes the issue where the '-y' flag in the share command was not recognized, ensuring backward compatibility. Resolves GitHub issue #3639.
=> fix(share): add backward compatibility for '-y' flag

src/integrations/huggingfaceDatasets.ts, test/integrations/huggingfaceDatasets.test.ts
This PR fixes issue #3685 where Hugging Face datasets were incorrectly expanding array fields like 'choices' into multiple test cases.
When using Hugging Face datasets, particularly MMLU, each row should create a single test case, even when it contains array fields like 'choices'. Previously, these arrays were being expanded into multiple test cases, resulting in 4 test cases from a single MMLU row.
Added `disableVarExpansion: true` to all test cases created from Hugging Face datasets. This prevents array fields from being expanded into combinations.
- Updated the unit tests to verify that all Hugging Face dataset test cases have the `disableVarExpansion` option set
- Manually tested with MMLU datasets to confirm that a single row generates a single test case
Fixes #3685
=> fix(huggingface): disable var expansion for huggingface datasets to prevent array field expansion

site/docs/usage/sharing.md, src/share.ts
- Added guidance on handling "413 Request Entity Too Large" errors in the sharing documentation.
- Explained client-side and server-side solutions, including the use of `PROMPTFOO_SHARE_CHUNK_SIZE`.
=> docs(sharing): add troubleshooting section for upload issues

site/docs/usage/self-hosting.md
Updated the self-hosting documentation to include Docker Compose and Kubernetes Helm methods.
- Added detailed steps for Docker Compose setup.
- Included experimental Kubernetes Helm chart usage.
- Enhanced clarity and formatting for existing Docker instructions.
=> docs(self-hosting): update self-hosting instructions

src/share.ts
Witnessed cases where `500` status codes will cause `hasEvalBeenShared` to return `true`.
=> chore(cli): improves robustness of hasEvalBeenShared util

src/share.ts
https://github.com/promptfoo/promptfoo/pull/3653/commits/033658a90f84cad122c4b977745bc2938d0a12b6 incorrectly changed the target API endpoint but this error was masked until https://github.com/promptfoo/promptfoo/commit/98f0adab22203aae2ec6ce0dd1a3c1cb23971045.
=> fix(cli): Use correct url for sharing validation

src/redteam/commands/poison.ts
Fixes a minor bug where passing a directory for `<documents...>` and an `--output-dir` copies the input directory tree rather than writing to the output dir.
**Before**
```sh
> ls ~/test
docs
> ls ~/test/docs
all engineering execs hr sales
> promptfoo redteam poison ~/test/docs --output-dir ~/test/poisoned-docs
> ls ~/test
docs poisoned-docs test
> ls ~/test/poisoned-docs
> ls ~/test/test/docs
all engineering execs hr sales
```
**After**
```sh
> ls ~/test
docs
> ls ~/test/docs
all engineering execs hr sales
> promptfoo redteam poison ~/test/docs --output-dir ~/test/poisoned-docs
> ls ~/test
docs poisoned-docs
> ls ~/test/poisoned-docs
all engineering execs hr sales
```
Also improves understandability by adding types for `<documents...>` (because it can be file paths, directory paths, or …
=> fix(cli/redteam/poison): Write docs to the output dir

examples/openai-responses/README.md, examples/openai-responses/promptfooconfig.function-call.yaml, examples/openai-responses/promptfooconfig.reasoning.yaml, examples/openai-tools-call/README.md, examples/openai-vision/README.md, site/docs/providers/openai.md, src/providers/openai/chat.ts, src/providers/openai/responses.ts, src/providers/openai/types.ts, test/providers/openai/chat.test.ts, test/providers/openai/responses.test.ts
This update introduces support for the new o4-mini reasoning model in the OpenAI provider.
- Added configuration and tests for o4-mini model.
- Updated documentation to include o4-mini details.
=> feat(openai): add support for o4-mini reasoning model

src/evaluator.ts, test/evaluator.test.ts
Fixes an issue where prompt rendering errors would crash the application by wrapping the rendering logic in a try-catch block and returning errors instead of crashing.
- Ensures prompt rendering errors are caught and handled properly.
- Updates tests to include scenarios for error handling.
=> fix(evaluator): handle prompt rendering errors gracefully

src/redteam/commands/poison.ts
Updated the export syntax for functions in poison.ts to use inline exports. This improves code readability and maintains consistency across the codebase.
=> refactor: update export syntax for functions

examples/redteam-multi-modal/promptfooconfig.unsafebench.yaml, src/commands/eval.ts, test/commands/eval/redteamWarning.test.ts
Add a warning in the eval command when a redteam section exists in the config but no test cases are defined.
- Updated eval.ts to include the warning logic.
- Added corresponding unit tests to verify the warning behavior.
=> feat(eval): add warning for redteam config without test cases

examples/google-aistudio-gemini/promptfooconfig.yaml
Current ceiling is insufficient for thinking and causes eval to fail.
=> chore: Increase max outuput tokens for `google:gemini-2.5-pro-exp-03-25` to 2048 in Gemini example

site/docs/providers/index.md
This PR updates model references in the providers documentation to use the latest versions available from:
- OpenAI: Add gpt-4.1-mini and o3-mini models
- Google AI: Update to gemini-2.5-flash-preview-04-17
- Vertex AI: Update to gemini-2.5-flash-preview-04-17
- Hyperbolic: Update to Llama-3.3-70B-Instruct
- X.AI: Update to grok-3-beta
These changes ensure the documentation reflects current state-of-the-art models.
=> docs(providers): update model IDs to latest versions

src/app/src/pages/eval/components/Eval.tsx, src/app/src/pages/eval/components/ResultsView.test.tsx, src/app/src/pages/eval/components/ResultsView.tsx
Currently, search state is maintained during navigation but is not reflected in the URL. This creates two issues:
We can't share links with specific search parameters
LLMs cannot easily extract search information from the page URL
Implement URL-based search state persistence by adding search parameters to the URL.
While the search state is not lost during navigation, if i want to for example link the page to someone else with the correct search state, or get a LLM to extract data from the page.
- Modified navigation to use URL fragments instead of query parameters for a cleaner URL structure and requires less work merging the evalId qp and search qp
- When updating search parameters, we include previous parameters with Object.fromEntries(searchParams.entries()) this is only so that we do …
=> feat: persist search in url

src/redteam/shared.ts
Going to use this to pass in command line args from cloud configs
=> chore: respect redteam commandLineOptions from config

src/providers/http.ts
I was exploring the HTTP Provider to see points of extensibility specifically propagating metadata / usage tokens, i noticed that the if statement was not required (probably was used in the past)
Thought i would clean it up in the mean time.
=> refactor: remove if string check

src/matchers.ts, test/matchers.test.ts
In trying to use the context-recall matcher I was getting unexpected results. It turned out that the response included a newline at the end, causing the matcher to count one extra failed sentence. (This was using Gemini 2.0 Flash for grading.)
To correct, I added a function that splits on new lines and filters empty lines and it worked as expected for me after.
=> fix(matchers): score results correctly with trailing newlines.

src/providers/http.ts, test/providers/http.test.ts
Allow function based repsponseTransformer return more fields then just output for ProviderResponse
there are 3 ways to parse response from the api
1. string pattern
2. inlineFunction 
3. fileFunction
currently both 1 and 2 return the result like this `{ output: resp };` 3 allows you to do anything you want, as it does not do anything with the returned result.
because 1 is just a string pattern makes sense to only support `{ output: resp };`, but 2 and 3 should have similar behavior if a user wants to provide more information in the provider response.
this pr brings the two closer, by not transforming the returned object into the output key, but this would cause a breaking change, if developers have been expecting
{ output : {<my_object} } as now it would return { <my_object }
with this …
=> feat: enable custom response parser to optionally return provider response

src/providers/registry.ts, src/providers/scriptBasedProvider.ts, src/util/file.ts, test/providers.test.ts, test/providers/registry.test.ts, test/providers/scriptBasedProvider.test.ts, test/util/file.test.ts
This specifically handles the case where `promptfoo redteam run` is called with a cloud config (i.e. `-c <config_uuid>`). If the cloud config was specified to be a custom provider for golang, python, etc, then if the path provided isn't absolute, it will resolve it based on the current working directory.
=> chore: resolve relative provider paths from cloud configs

src/app/src/pages/eval/components/CustomMetrics.css, src/app/src/pages/eval/components/CustomMetrics.tsx
=> chore: make custom metrics more obviously clickable

site/src/pages/index.module.css
This PR fixes changing border height on button click causing the content height to noticeably shift.
=> fix(site): Landing page content jumping on step switch

src/envars.ts, src/telemetry.ts, test/telemetry.test.ts
- ensure consistent key name (we were using `PROMPTFOO_POSTHOG_KEY` and `POSTHOG_KEY`)
- allow overwriting host
- adds debug logging
=> chore: minor telemetry changes

site/docs/usage/command-line.md, src/main.ts
- Support for the `--verbose` flag is inconsistent across the CLI commands. 
- This PR adds a global option while maintaining backwards compatibility by not modifying the existent, command level `--verbose` flags (i.e. `promptfoo --verbose eval --verbose` redundant yet valid).
- It is useful for scenarios where the user otherwise needs to `export LOG_LEVEL=debug && promptfoo <cmd>`.
=> feat(cli): Adds global `--verbose` option

src/providers/mcp/client.ts
This PR replaces console.error calls with logger.error in MCPClient for better error handling in tests and consistent logging.
=> chore(logger): replace console.error with logger.error in MCPClient

site/docs/usage/command-line.md, src/main.ts
Reverts promptfoo/promptfoo#3931 
We discussed and don't want to add a flag that goes before the sub commands
=> chore: Revert "feat(cli): Adds global `--verbose` option"

src/redteam/plugins/index.ts
We need better error handling when remote generation fails and we need to ensure we are always returning an array
=> chore: Better error handling and logging for remote generation

src/evaluator.ts, test/evaluator.test.ts
Previously, `namedScoresCount` was incremented by 1 for each test case that included a named score, regardless of how many assertions contributed to that score, which led to inaccurate `namedScoreCounts` in result exports if multiple assertions with the same metric name existed.
=> fix(evaluator): correctly count named scores based on contributing assertions

src/commands/eval.ts, src/commands/init.ts, src/commands/share.ts, src/main.ts, src/redteam/commands/generate.ts, src/redteam/commands/run.ts, test/commands/init.test.ts, test/commands/share.test.ts, test/main.test.ts
This PR adds a global `--env-file` (and its alias `--env-path`) option to all commands recursively, similar to how the global `--verbose` option was added in PR #3950. This enables users to specify a custom .env file path with any command.
- Add `addEnvFileOptionRecursively` function in `src/main.ts` (similar to `addVerboseOptionRecursively`)
- Remove redundant `--env-file` options from individual command implementations
- Add tests for the global env-file option
Added comprehensive tests in `test/main.test.ts` that verify:
- The option is added to commands that don't have it
- The option is not duplicated if it already exists
- The option is added to all subcommands recursively
- The hook correctly calls `setupEnv` with the provided path
=> chore: add global env-file option to all commands recursively

site/docs/contributing.md
I had to figure this out as when i looked at the docs there were no instructions
=> docs: instructions on how to run the documentation

site/docs/configuration/expected-outputs/javascript.md
As a user i would prefere to define my assertions inline versus in a seperate file imported using a path.
This makes the code cleaner and allows me to do things like currying the assertion fuction
in order to do this i had to read through the code, so to simplify for the next user i added documentation
coersion happens here:
https://github.com/promptfoo/promptfoo/blob/46e784ec001d29920bac5bfeb25903265c4d6d65/src/assertions/index.ts#L220
=> docs: how to create inline assertions for pacakge users

src/providers/anthropic/messages.ts, src/providers/azure/chat.ts, src/providers/google/ai.studio.ts, src/providers/google/vertex.ts, src/providers/mcp/client.ts, src/providers/openai/chat.ts, src/redteam/commands/generate.ts, test/providers/anthropic/messages.test.ts, test/providers/mcp/client.test.ts, test/redteam/commands/generate.test.ts
Fix cleanup race condition with MCP server initialization
Resolve issue where cleanup calls fail because providers haven't completed MCP server initialization. This initialization happens during provider loading for redteam generate, even when providers aren't explicitly called.
This minimal fix addresses the race condition. An alternative approach could be preventing MCP server instantiation during generate-only calls, but the current solution is sufficient and safe.
=> chore: Clean up providers for redteam generate

site/blog/understanding-mcp.md
Added a truncation marker to the MCP blog post to improve content management and display. No breaking changes.
=> docs(blog): add truncation marker to MCP blog post

src/providers/scriptBasedProvider.ts, src/util/file.ts, test/providers/scriptBasedProvider.test.ts, test/util/file.test.ts
Should resolve https://github.com/promptfoo/promptfoo/issues/3991
The changes in https://github.com/promptfoo/promptfoo/pull/3805 resolved file paths to cwd for cloud configs, but also for relative paths when not a cloud config, if a config.basePath was not set. This should've only applied for cloud configs, since path resolution is done already in https://github.com/promptfoo/promptfoo/blob/6bf829bb5f4214909c96e9dba94793ea8ba98b0e/src/util/index.ts#L415 for scripts. As a result, we would now be applying the base path twice, causing some weird effects, as seen in the issue. 
<details>
<summary>Test Process</summary>
input:
```
providers:
- id: 'file://providers/example.py'
- id: 'file://../providers/example.py'
- id: 'file://../../providers/example.py'
- id: …
```
=> fix: Resolve paths relative to promptfooconfig when not cloud config

src/redteam/index.ts
=> chore(cli): improve color of Redteam test generation table headers

src/providers/azure/chat.ts
When using Azure CLI authentication the following error occurs:
```
[ERROR] Error: Invariant failed: auth headers are not initialized
Error: Invariant failed: auth headers are not initialized
at invariant (/usr/lib/node_modules/promptfoo/dist/src/util/invariant.js:24:11)
at AzureChatCompletionProvider.callApi (/u...
```
The error appears to be caused by `AzureChatCompletionProvider` redeclaring `initializationPromise` and setting it to `null`. There is no need to declare `initializationPromise` as it has already been done in the base class. By removing this line the error is fixed.
=> fix: azure auth headers gets set to null in subclass

site/docs/integrations/mcp.md, src/providers/mcp/client.ts, src/providers/mcp/types.ts, src/redteam/constants.ts, test/providers/mcp/client.test.ts, test/redteam/constants.test.ts
Adding an option to specify headers, and passing those into the http & sse MCP clients
=> chore: add headers support for url remote mcp servers

src/commands/eval.ts
- tweak wording for `--prompt-suffix` flag description
- `npm run build` *(fails: Cannot find type definition file)*
=> chore: Update prompt suffix help text

src/providers/registry.ts, test/providers.test.ts
- update OpenAI defaults to GPT 4.1 models in `registry.ts`
- `npm run f` *(fails: Cannot find package '/workspace/promptfoo/node_modules/@trivago/prettier-plugin-sort-imports/' imported from /workspace/promptfoo/noop.js)*
- `npm run l` *(fails: Cannot find package '/workspace/promptfoo/node_modules/eslint-plugin-react-hooks/index.js')*
- `npm test` *(fails: jest: not found)*
=> chore(providers): update default openai models for openai:chat alias

src/redteam/strategies/simpleVideo.ts, test/redteam/strategies/simpleVideo.test.ts
This PR fixes open handles in the video strategy test, ensuring the progress bar is always cleaned up properly when errors occur. The implementation now uses proper try/finally blocks for resource cleanup.
=> fix(redteam): fix open handle in video test

site/.gitignore, site/README.md, site/docusaurus.config.ts, site/package.json, site/src/components/CopyPageButton.module.css, site/src/components/CopyPageButton.tsx, site/src/theme/DocItem/index.js
https://github.com/user-attachments/assets/5300665e-c16a-4c84-89b9-c09738dbcb88
dark mode:
=> feat: add copy as markdown button to doc pages

src/app/src/pages/evals/components/EvalsDataGrid.tsx
I noticed that when you go to select an eval, the currently selected eval wasn't present in the table, which was confusing. This removes that filter, and now the current eval is visible and highlighted, as expected. Added a disabled state too:
=> chore(webui): display currently selected eval in eval dialogue

src/commands/eval.ts, src/evaluator.ts, src/models/eval.ts, src/share.ts, test/commands/eval/redteamWarning.test.ts, test/evaluator.test.ts, test/share.test.ts
- add batched sample and counting helpers on `Eval`
- stream results in `sendChunkedResults`
=> chore: Improve memory usage when sharing results

site/docusaurus.config.ts
Just noticed that `index.md` files, such as `red-team/index.md` were not correctly handled for serving the md content in the docs site. This fixes that by mapping all `index.md` files to be `/directory.md` files, which should map with what the url indicates. Hopefully this doesn't break anything else 😃
=> chore(docs): Handle index.md files for copy page

examples/claude-vs-gpt-image/README.md, examples/claude-vs-gpt-image/prompt.js, examples/claude-vs-gpt-image/prompt.py, examples/claude-vs-gpt-image/promptfooconfig.yaml, site/docs/configuration/expected-outputs/model-graded/index.md, src/assertions/llmRubric.ts, src/matchers.ts, test/assertions/llmRubric.test.ts, test/matchers.test.ts
- allow llm-rubric assertion values to be objects
- switch claude image example to gpt-4.1 with better rubric prompt
- document using gpt-4.1 for image-based grading
- test object rubric handling
- `npx prettier --write examples/claude-vs-gpt-image/README.md examples/claude-vs-gpt-image/prompt.js examples/claude-vs-gpt-image/promptfooconfig.yaml site/docs/configuration/expected-outputs/model-graded/index.md test/matchers.test.ts`
- `npx eslint --max-warnings=0 --fix test/matchers.test.ts`
- `npm test` *(fails: The @smithy/node-http-handler package is required, fetchWithProxy expectation mismatch)*
=> chore: add vision grading example

site/docs/providers/http.md, src/providers/http.ts, test/providers/http.test.ts
- render Nunjucks templates for HTTP provider URLs
- document dynamic URLs in HTTP provider docs
- `npx jest test/providers/http.test.ts --runInBand`
- `npm test`
=> chore(providers): support templated URLs in http

site/docs/usage/self-hosting.md
- mention that enterprise customers should not use the public image
- `npx prettier --write site/docs/usage/self-hosting.md`
- `npm run l` *(fails: ambiguous argument 'origin/main')*
- `npm test` *(fails: missing @smithy/node-http-handler dependency)*
=> docs: add enterprise disclaimer to self-hosting

src/redteam/index.ts, src/redteam/plugins/index.ts, test/redteam/index.test.ts
Should fix https://github.com/promptfoo/promptfoo/issues/4072
We'll now skip plugins that fail validation rather than throwing an error. 
I tested against a few plugin collections: 
* `owasp:llm` (the offending plugin is skipped)
* `owasp:api` (no change)
* `mitre:atlas` - skips `indirect-prompt-injection` and `policy`. 
Manual test cases:
<details>
<summary>`owasp:llm`</summary>
```
> ts-node --cwdMode --transpileOnly src/main.ts redteam run -c examples/redteam-rag/promptfooconfig.yaml --force
Generating test cases...
Cache is disabled
Synthesizing test cases for 1 prompt...
Using plugins:
ascii-smuggling (5  tests)
bfla (5  tests)
bias:gender (5  tests)
bola (5  tests)
cross-session-leak (5  tests)
debug-access (5  tests)
divergent-repetition (5  tests)
excessive-agency (5  tests) …
```
=> fix(plugins): Skip plugins when validation fails

.vscode/settings.json, src/telemetry.ts, test/telemetry.test.ts
Add the isRunningInCi flag to telemetry events.
- Updated telemetry to include a CI detection flag in event properties.
- Adjusted tests to accommodate the new telemetry property.
=> chore(telemetry): add isRunningInCi flag to telemetry events

site/src/css/custom.css
=> docs(site): reduce sidebar padding

src/app/src/pages/eval-creator/components/RunTestSuiteButton.tsx, src/app/src/pages/eval-creator/components/YamlEditor.test.tsx, src/app/src/stores/evalConfig.ts
Relates to https://github.com/promptfoo/promptfoo/issues/4031
Additionally noted during testing:
- Default ordering of the config is confusing, with defaultTest being at the bottom in edit YAML
- evaluateOptions is not shown in the specific eval page -> View YAML
- defaultTest recent addition is visible in the top in the specific eval page -> View YAML (description should be the top)
=> fix(webui): defaultTest shown in webui YAML editor

src/prompts/processors/text.ts, test/prompts/processors/text.test.ts
Resolves https://github.com/promptfoo/promptfoo/issues/4141
=> fix(prompts): splitting when PROMPTFOO_PROMPT_SEPARATOR is contained within a string with text files

src/models/eval.ts
- define typed row structures for eval result queries
- remove `@ts-ignore` by using generics for `db.get` and `db.all`
- `npm run lint`
- `npm test` *(fails: The @smithy/node-http-handler package is required)*
=> feat: add typed row interfaces for eval queries

test/feedback.test.ts, test/redteam/index.test.ts, test/redteam/plugins/pluginId.test.ts, test/site/markdown.test.ts
- trim comments in feedback test suite
- remove superficial comments in markdown and plugin tests
- remove logging notes in redteam test suite
- `npx prettier --write test/feedback.test.ts test/site/markdown.test.ts test/redteam/plugins/pluginId.test.ts test/redteam/index.test.ts`
- `npx eslint --max-warnings=0 --fix test/feedback.test.ts test/site/markdown.test.ts test/redteam/plugins/pluginId.test.ts test/redteam/index.test.ts` *(fails: Parsing error)*
- `npm test` *(fails: The @smithy/node-http-handler package is required)*
=> chore: remove redundant test comments

src/assertions/sql.ts, test/assertions/sql.test.ts, test/redteam/providers/iterativeTree.test.ts
- reintroduce SQL assertion edge case tests and update to expect failure messages
- add additional validation logic in `handleIsSql` for better error detection
- expand whitelist handling for `update` statements
- `npx prettier --write src/assertions/sql.ts test/assertions/sql.test.ts`
- `npx eslint --max-warnings=0 --fix --no-warn-ignored src/assertions/sql.ts test/assertions/sql.test.ts`
- `npm test` *(fails: The @smithy/node-http-handler package is required as a peer dependency)*
=> test: re-enable sql assertion edge cases

site/src/pages/llm-vulnerability-scanner.module.css
There was an issue moving between the homepage and the docs site- specifically, the scroll height would be maintained between links, and clicking an image to expand wouldn't work. After some digging, I found the offending commit https://github.com/promptfoo/promptfoo/pull/3733 and was able to identify two conflicting global css styles that were causing these issues.
https://github.com/user-attachments/assets/90abd6f5-9c7e-4a07-8996-9f5bef64ce7f
=> fix(docs): Fix issue with docs links not scrolling to the top

src/providers/mcp/transform.ts, test/providers/mcp/transform.test.ts
MCP integration was failing with Google Gemini models, causing two specific errors. Described in [Discord question](https://discord.com/channels/1153767083381903389/1374551152460566649):
- Google AI Studio: Error: Expected one candidate in API response
- Google Vertex: Invalid JSON payload received. Unknown name "$schema"
**Root Cause**
MCP servers can include $schema fields in their tool definitions (following JSON Schema conventions), but Google's API rejects these fields as invalid. [Reference for general MCP format: MCP Specs](https://modelcontextprotocol.io/specification/2025-03-26/server/tools#protocol-messages)
**Solution**
Added one line to remove $schema field from MCP tool schemas before sending to Google API
**Testing**
- ✅ Made sure the issue stems from `$schema` field by …
=> fix: Gemini MCP integration - can not parse $schema field

src/providers/http.ts, src/types/providers.ts, test/providers/http.test.ts
Always include raw output from http provider, http status code and status text. This will make debugging much easier
=> chore: Always include raw output from http provider, status code and status text

src/app/src/pages/redteam/setup/components/Targets/HttpAdvancedConfiguration.tsx, src/app/src/pages/redteam/setup/utils/crypto.ts
This validation logic was failing incorrectly. The idea that we're able to identify every valid combination was a little ambitious. We'll do some basic checks and then let the server decide.
=> fix: Relax private key validation

src/app/src/pages/redteam/setup/components/Purpose.tsx
Fixing a very minor visual issue
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
=> chore: fix border radius on purpose example

src/providers/http.ts
The  `[HTTP Provider] Content-Type is application/json, but body is a string. This is likely to cause unexpected results. It should be an object or array. Body: ${body} headers: ${safeJsonStringify(headers)}`, warning would be thrown even if the body was a valid json object.
=> fix: Check if body is good json before sending warning

examples/openai-responses/README.md, examples/openai-responses/promptfooconfig.external-format.yaml, examples/openai-responses/response_format.json, site/docs/providers/openai.md, src/providers/openai/responses.ts, test/providers/openai/responses.test.ts
Adds support for loading response_format configurations from external files in the OpenAI Responses API provider. This brings it to parity with the Chat API provider and enables users to load complex JSON schemas from external files using the file:// syntax. Includes working examples and updated documentation. Relates to #4148
=> chore: add external file loading support for response_format in OpenAI Responses API

site/docs/usage/troubleshooting.md
- move native build steps from installation guide to troubleshooting
- `npx prettier -w site/docs/installation.md site/docs/usage/troubleshooting.md`
- `npx eslint site/docs/installation.md site/docs/usage/troubleshooting.md --fix` *(files ignored)*
- `npm test` *(fails: The @smithy/node-http-handler package is required, fetch tests)*
=> docs: add native build guidance to troubleshooting section

src/app/src/pages/redteam/setup/components/Purpose.tsx, src/app/src/pages/redteam/setup/components/Review.tsx, src/app/src/pages/redteam/setup/hooks/useRedTeamConfig.ts
This was removed in a previous change, but I'm adding it back since it was pretty useful.
Also folded in is a change to make long purposes truncated by default in the review screen, since the example purpose is quite long now:
https://github.com/user-attachments/assets/54626d1b-5819-4e16-966a-81c8a20f75bc
+
https://github.com/user-attachments/assets/d128c56a-8bdb-4c1b-9f49-c9e06bd65d95
=> chore: Add back example config to red team create flow

src/redteam/plugins/shellInjection.ts, test/redteam/plugins/shellInjection.test.ts
I need some opinions:
Generated tests before:
[eval-BCP-2025-06-03T22_29_10-table.csv](https://github.com/user-attachments/files/20582520/eval-BCP-2025-06-03T22_29_10-table.csv)
Generated tests wth changes from this PR:
[eval-BGv-2025-06-03T23_46_36-table.csv](https://github.com/user-attachments/files/20582524/eval-BGv-2025-06-03T23_46_36-table.csv)
I think it's better
system prompt:
```
This is a coding agent that can:
- Read a internal code repositor  with local tools like :
- LS – list files/directories
- GlobTool– find files by name/glob pattern
- GrepTool – search file contents with regex
- View – read file contents
- Edit / CreateNewFile – modify or add files
- Bash – run shell commands (no network)
- Batch – run multiple LS/Grep/View/Edit calls in parallel
- Thinking – jot internal …
```
=> chore(redteam): generate better shell injection attacks

src/providers/openai/chat.ts
There are many classes that extend from OpenAiChatCompletionsProvider, but all the logging is openai this openai that, which causes users to be confused because they set a provider that is not open ai.
This commit tries to make it align the output with what the user would expect
I have some failing tests but those require more work due to the environment setup
=> fix: improve logging when inheriting from OpenAiChatCompletionProvider

src/redteam/constants/metadata.ts
remove extra 'agentic:memory-poisoning' entry from risk categories
=> fix: remove duplicate memory poisoning entry

examples/colab-notebook/README.md, examples/github-action/README.md, examples/node-package-typescript/README.md, examples/node-package/README.md, examples/redteam-bestOfN-strategy/README.md, examples/redteam-minimal/README.md, examples/websockets/README.md
- **Documentation**
- Added new README files for various examples, including Colab notebook, GitHub Action, Node.js package (JavaScript and TypeScript), red team strategies, and WebSockets integration.
- Each README provides setup instructions, prerequisites, usage steps, and outlines expected results for running and evaluating promptfoo in different environments and use cases.
=> chore: Add README for missing examples

.cursor/rules/gh-cli-workflow.mdc, site/src/components/CopyPageButton.module.css, site/src/components/CopyPageButton.tsx
During large testing runs I am frequently getting:
```
RangeError: Invalid string length
at JSON.stringify (<anonymous>)
at safeJsonStringify (/usr/local/lib/node_modules/promptfoo/src/util/json.ts:41:10)
at processEvalStep (/usr/local/lib/node_modules/promptfoo/src/evaluator.ts:894:74)
at /usr/local/lib/node_modules/promptfoo/src/evaluator.ts:1247:7
```
This aims to address that by introducing `summarizeEvaluateResultForLogging` and `safeJsonStringifyTruncated` which will attempt to output a truncated version instead. It will also fail gracefully and continue
=> fix: Fail gracefully on RangeErrors and try to output a truncated version of the results

src/app/src/pages/eval/components/TableSettings/components/SettingsPanel.tsx, src/app/src/pages/eval/components/TableSettings/hooks/useSettingsState.ts
Added sanitizedMaxTextLength that defaults to 500 when current setting is invalid, ensuring the slider never resets to unreasonably low values like 0/25. Applied same sanitization in useSettingsState hook for consistency.
=> chore(webui): fix text length reset value to use reasonable default

site/blog/2025-summer-new-redteam-agent.md
Fixes Docusaurus warning about undefined author by changing from inline author definition to proper authors array reference. Changes: Changed author: 'Steven Klein, Principal Engineer at Promptfoo' to authors: [steven]. This properly references the existing author definition in authors.yml and eliminates the Docusaurus build warning about undefined authors.
=> docs(site): fix author reference on 2025-summer-new-redteam-agent blog post

site/docs/model-audit/index.md, site/docs/model-audit/scanners.md, site/docs/model-audit/usage.md
Updates ModelAudit documentation to include 5 new scanners (ONNX, GGUF/GGML, Joblib, NumPy, OCI Layer), enhances existing scanner docs, adds proper SEO metadata, and removes marketing language for clearer technical documentation.
=> docs(site): Update ModelAudit scanners documentation with comprehensive scanner coverage

src/providers/registry.ts
The passthrough is not functioning correctly for OpenRouter because it isn't adding the keys at the root level.
```yaml
providers:
- id: openrouter:google/gemini-2.5-flash
config:
passthrough:
reasoning:
enabled: true
prompts:
- 'What is 1+1?'
```
Actual request:
```json
{
"model": "google/gemini-2.5-flash",
"messages": [
{
"role": "user",
"content": "What is 1+1?"
}
],
"max_tokens": 1024,
"passthrough": {
"reasoning": {
"enabled": true
}
}
}
```
Expected request:
```json
{
"model": "google/gemini-2.5-flash",
"messages": [
{
"role": "user",
"content": "What is 1+1?"
}
],
"max_tokens": 1024,
"reasoning": {
"enabled": true
}
}
```
=> fix(openrouter): unpack passthrough at the root level

src/commands/eval.ts
no point in breakdown for a single one
=> chore: show provider breakdown only for multiple providers

src/app/src/pages/eval/components/Eval.tsx
This PR also applies some basic housekeeping that makes the `<Eval/>` component easier to grok.
=> fix(app/eval results): Welcome component should not render while loading eval data

src/redteam/util.ts, test/redteam/util.test.ts
Skip goal extraction when PROMPTFOO_DISABLE_REDTEAM_REMOTE_GENERATION is enabled
Relates to https://github.com/promptfoo/promptfoo/issues/4618
=> fix(redteam): skip goal extraction when remote generation is disabled

src/evaluatorHelpers.ts, src/types/index.ts, test/evaluatorHelpers.test.ts
- Removes runtime validation of `context` arg passed into the hook runner; it results in errors because our test suite zod schemas is a subset of the potential configuration values
- Removes runtime validation of `context` returned from hooks, also because of the subset.
- Note: this change allows user code to mutate and return `context` such that it will break downstream execution. This is preferable because the user can correct the offending code within the hook definition.
=> chore(cli): Removes context schema validation from extension hooks

site/src/components/CopyPageButton.module.css
=> docs: prevent copy button from overlapping screenshot overlay

site/blog/2025-summer-new-redteam-agent.md
Fixed multiple typos and grammatical errors in the red team agent blog post including: - 'a step forward' → 'a step further' - 'approprioately prioritze' → 'appropriately prioritize' - 'crescendo' → 'Crescendo' - 'pen-testing' → 'penetration testing' - 'mis-information' → 'misinformation' - Fixed Python code syntax - Various grammar and style improvements
=> fix(docs): correct typos in red team agent blog post

src/app/src/pages/eval-creator/components/EvaluateTestSuiteCreator.test.tsx, src/app/src/pages/eval-creator/components/EvaluateTestSuiteCreator.tsx, src/app/src/pages/eval-creator/components/RunTestSuiteButton.tsx, src/app/src/pages/eval-creator/components/YamlEditor.test.tsx, src/app/src/pages/eval-creator/components/YamlEditor.tsx, src/app/src/stores/evalConfig.ts
Fixes #4611 
This fix populates derived metrics config from WebUI to the JS data store and the eval job submitted.
Added unit tests and verified that the submitted eval job contains the derived metrics.
=> fix: support derived metrics in eval config uploaded via WebUI

site/docs/usage/self-hosting.md
This PR clarifies the self-hosting documentation to address confusion about the workflow for sharing evaluation results.
- Added clear instructions that `promptfoo share` is required after running `promptfoo eval` to upload results to a self-hosted instance
- Added troubleshooting section for "Results Not Appearing in Self-Hosted UI"
- Included example configuration showing how to use the `sharing` config in `promptfooconfig.yaml`
- Fixed minor terminology inconsistencies (evaluation → eval)
Addresses #4521 - User confusion about the proper workflow for viewing eval results in self-hosted Promptfoo
The main issue was that users didn't realize they need to explicitly run `promptfoo share` after `promptfoo eval` when using a self-hosted instance.
=> docs(site): clarify self-hosting workflow for eval sharing

test/assertions/runAssertion.test.ts
This PR fixes a SIGSEGV error that occurs during test execution in certain environments.
The test suite was failing with:
```
FAIL test/assertions/runAssertion.test.ts
● Test suite failed to run
A jest worker process (pid=4992) was terminated by another process: signal=SIGSEGV, exitCode=null. Operating system logs may contain more information on why this occurred.
at ChildProcessWorker._onExit (node_modules/jest-worker/build/workers/ChildProcessWorker.js:370:23)
```
Mock the `better-sqlite3` module to prevent loading the native binary that causes SIGSEGV in certain test environments. This allows the tests to run without attempting to load the problematic native module.
- Added `jest.mock('better-sqlite3')` to `test/assertions/runAssertion.test.ts`
=> test: fix SIGSEGV caused by better-sqlite3 in test environment

src/providers/http.ts, src/util/json.ts, test/providers/http.test.ts
Red team testing was failing intermittently because prompts with newlines or special characters would break JSON templates:
```yaml
body: '{"message": "{{prompt}}"}'
```
When `prompt` contains newlines, this creates invalid JSON:
```json
{"message": "Multi-line
text"}
```
Server responds with HTTP 400: "Invalid JSON payload received"
Added automatic JSON escaping when templates fail to parse:
- First tries normal template rendering
- If JSON parsing fails, re-renders with properly escaped variables  
- Falls back to original behavior if still broken
✅ Red team prompts with newlines/quotes/special chars now work reliably  
✅ No breaking changes to existing configurations  
✅ Works with any JSON template string format (YAML, JS, etc.)
**Before:** Intermittent 400 errors during red team …
=> fix: the case when http body has not escaped charactors

src/index.ts, test/index.test.ts
Expose `doRedteamRun` for programmatic use.
Fixes #4749
=> chore: expose doRedteamRun in package exports

test/providers/google/live.test.ts
Fixed flaky test by improving mock cleanup and reduced test execution time from 9.6s to 0.4s.
=> test: fix flaky google live test and improve test speed

src/providers/registry.ts, src/redteam/constants/frameworks.ts, src/redteam/constants/metadata.ts, src/redteam/constants/plugins.ts, src/redteam/plugins/agentic/constants.ts, src/redteam/plugins/index.ts, test/redteam/constants.test.ts, test/redteam/constants/frameworks.test.ts, test/redteam/constants/metadata.test.ts, test/redteam/constants/plugins.test.ts
This PR completes the migration from using the `MEMORY_POISONING_PLUGIN_ID` constant to using the literal string `'agentic:memory-poisoning'` directly throughout the codebase.
- Replaced all instances of `MEMORY_POISONING_PLUGIN_ID` with the literal `'agentic:memory-poisoning'`
- Removed the now-unused `MEMORY_POISONING_PLUGIN_ID` export from `src/redteam/plugins/agentic/constants.ts`
- Kept `REDTEAM_MEMORY_POISONING_PLUGIN_ID` as it's still used in graders and providers
- Updated all tests to use the literal string instead of the constant
- Updated test descriptions to reflect the change
The following files were updated:
- `src/providers/registry.ts`
- `src/redteam/constants/frameworks.ts`
- `src/redteam/constants/metadata.ts`
- `src/redteam/constants/plugins.ts`
- …
=> refactor: inline MEMORY_POISONING_PLUGIN_ID constant

src/index.ts, src/redteam/types.ts, test/index.test.ts, test/redteam/types.test.ts
Exposes doGenerateRedteam as redteam.generate in the public API for programmatic test generation.
=> feat(redteam): expose generate function in redteam namespace

src/app/src/components/Navigation.tsx
This PR capitalizes 'Red team' to 'Red Team' in the navigation dropdown menu to maintain consistency with proper naming conventions throughout the application.
=> chore(webui): capitalize 'Red Team' in navigation menu for consistency

examples/assistant-cli/output.txt, src/commands/eval.ts
This PR removes the redundant 'Done.' message that was being printed after evaluation completion. The message was appearing in two different code paths and has been removed from both locations to clean up the output.
=> chore(eval): remove redundant 'Done.' message from evaluation output

src/python/pythonUtils.ts, test/python/pythonUtils.test.ts
Removes debug logging of Python script return data type. In practice, I've found it to be noise that makes the logs more difficult to read, for example:
=> chore(internals): remove python script result data type debug log

site/docs/providers/sagemaker.md, src/providers/sagemaker.ts, test/sagemaker.test.ts
- Validates user-provided config against Zod schema (to ensure correct types, keys, etc.); logs a warning if validation fails.
- Ensures that, for the completion provider, the model type is provided either within the provider id or in the `modelType` config parameter. Otherwise, unless the user intends to use a `custom` model, request payloads will be incorrectly serialized.
=> chore(providers/sagemaker): Improves validation of user-provided config

site/docs/configuration/expected-outputs/model-graded/index.md
This PR fixes a minor grammar inconsistency in the documentation for the `similar` metric assertion type.
- Changed "check that" to "checks that" to maintain consistency with other metric descriptions in the same list
- 📝 Documentation update (non-breaking change which improves documentation)
=> docs: add similar to model graded metrics table 

src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx, src/assertions/contextFaithfulness.ts, src/assertions/contextRecall.ts, src/assertions/contextRelevance.ts, test/assertions/contextFaithfulness.test.ts, test/assertions/contextRecall.test.ts, test/assertions/contextRelevance.test.ts, test/assertions/runAssertion.test.ts
=> feat(app/eval): Display context values in eval results

site/docs/configuration/expected-outputs/deterministic.md
Add detailed explanations for text similarity metrics (ROUGE-N, BLEU, GLEU, METEOR) and improve SEO front matter.
=> docs(site): improve NLP metric explanations and add SEO metadata

site/blog/SOC2-compliance.md, site/blog/promptfoo-vs-pyrit.md
This PR fixes Docusaurus warnings by adding truncation markers to blog posts and improves SEO optimization.
- Added truncation markers after lead paragraphs in:
- site/blog/SOC2-compliance.md
- site/blog/promptfoo-vs-pyrit.md
- Enhanced SEO front matter:
- Added more comprehensive and relevant keywords
- Improved meta descriptions for better search engine visibility
- Added title field to promptfoo-vs-pyrit.md for consistent metadata
- Added tags for better content categorization
1. **Truncation Markers**: Docusaurus requires these markers to properly display blog post summaries on listing pages
2. **SEO Optimization**: Better meta tags improve search engine visibility and click-through rates
- Ran npm run f to ensure proper formatting
- Changes follow Docusaurus best practices
=> docs: add truncation markers to blog posts

src/esm.ts, test/__fixtures__/testModule.cjs, test/__fixtures__/testModule.js, test/__fixtures__/testModule.mjs, test/__fixtures__/testModule.ts, test/__fixtures__/testModuleSimple.js, test/esm.test.ts
- https://linear.app/promptfooo/issue/PF-1057/support-es-modules-for-custom-providers
- This PR fixes a bug where `import` statements get converted to `require`, breaking ESM imports.
- Adds error callstack logging to make debugging future errors easier for end users.
=> fix(cli): esm provider loading

site/blog/mcp-proxy-announcement.md, site/blog/promptfoo-vs-pyrit.md, site/static/js/scripts.js
This PR adds truncation markers to blog posts that were missing them:
- `blog/mcp-proxy-announcement.md` - Added truncation marker after the introduction
- `blog/promptfoo-vs-pyrit.md` - Added truncation marker after the comparison table
These markers help improve the blog listing page by showing only the introduction of each article, allowing readers to get a preview before clicking through to read the full post.
The formatter also made minor style changes to `site/static/js/scripts.js` which are included in this PR.
=> docs(blog): add truncation markers to articles without them

test/server/share.test.ts
This PR fixes flaky tests in `test/server/share.test.ts` that were intermittently failing with timeout errors.
The tests were timing out after 5000ms due to:
- Creating a new Express app for each test
- Running database migrations before each test
- Inefficient resource management
- Move `runDbMigrations()` and `createApp()` to `beforeAll()` to run once per test suite
- Replace `.timeout(5000)` with `.expect()` assertions
- **Remove dangerous `deleteAllEvals()` entirely**
- Track only test-created eval IDs and clean them up individually
- Add `afterEach` cleanup for better test isolation
- **No bulk deletions** - The test no longer uses `deleteAllEvals()`
- **Targeted cleanup** - Only deletes specific evals created during the test
- **Fail-safe design** - Even if run outside test …
=> test: fix flaky server share tests

src/app/src/pages/eval/components/ResultsTable.css, src/app/src/pages/eval/components/ResultsTable.test.tsx, src/app/src/pages/eval/components/ResultsTable.tsx
This PR fixes a critical bug introduced in #4914 where the pagination component prevented users from scrolling to see content below it.
The pagination was using a complex dynamic height calculation system that:
- Made the table container fill the entire viewport
- Prevented vertical scrolling past the pagination
- Caused layout shifts and visual jumping when transitioning between sticky states
- Created a poor user experience with unpredictable behavior
Simplified the implementation by:
- ✅ Removed dynamic height calculations and refs
- ✅ Eliminated sticky positioning behavior that caused layout shifts
- ✅ Removed fade-in animations that added visual instability
- ✅ Made pagination always positioned at the bottom of content (no fixed positioning)
- ✅ Added proper spacing and maintained …
=> fix(webui): resolve pagination scrolling and layout issues in ResultsTable

scripts/generate-blog-image.js
This PR adds a new script to generate blog images using OpenAI's image generation API.
- A new script Use --help for usage information that can generate images for blog posts
- Command-line interface with options for filename and prompt
- Uses OpenAI's API to generate high-quality images
- Saves images to  directory
```bash
node scripts/generate-blog-image.js -f system-cards-hero.png -p "A red panda reading documentation"
```
- OPENAI_API_KEY environment variable must be set
- dotenv package for loading environment variables
=> docs: add blog image generation script

src/matchers.ts, test/matchers/llm-rubric.test.ts
Additional logging and error handling for bad llm-rubric responses
=> fix: additional checking on llm-rubric response

src/providers/litellm.ts, test/providers/index.test.ts, test/providers/litellm.test.ts
This PR fixes an issue where LiteLLM embedding providers were not recognized as valid embedding providers.
When using `litellm:embedding:...` providers, they were rejected with the error "is not a valid embedding provider". This was because the `LiteLLMEmbeddingProvider` class wasn't properly exposing the `callEmbeddingApi` method required for embedding providers.
- Made `LiteLLMEmbeddingProvider` implement the `ApiEmbeddingProvider` interface
- Added a private property to store the wrapped `OpenAiEmbeddingProvider` instance
- Exposed the `callEmbeddingApi` method that delegates to the wrapped provider
- Fixed type imports to use the correct `ProviderEmbeddingResponse` type
- Added comprehensive unit tests for embedding provider functionality
- Added integration tests for loading LiteLLM …
=> fix(providers): implement callEmbeddingApi for LiteLLM embedding provider

src/app/src/pages/eval/components/ResultsTable.tsx
- Don't display a default value; this can be confusing and lead the user to believe it's the current page number
- Ensures the user cannot set a value higher than the max page count or a value lower than 1
=> chore(webui): Improvements to pagination "go to" functionality

src/app/src/pages/redteam/setup/components/DefaultTestVariables.test.tsx, src/app/src/pages/redteam/setup/components/DefaultTestVariables.tsx
=> fix(site): dark mode style on redteam setup ui 

site/docs/providers/google.md, site/docs/providers/vertex.md, site/static/config-schema.json, src/providers/google/ai.studio.ts, src/providers/google/vertex.ts, src/types/env.ts
This PR adds support for the `GEMINI_API_KEY` environment variable, which is the standard environment variable name used in Google's official Gemini API documentation.
- Added `GEMINI_API_KEY` to `ProviderEnvOverridesSchema` in `src/types/env.ts`
- Updated Google AI Studio provider to check for `GEMINI_API_KEY` before falling back to `GOOGLE_API_KEY`
- Updated Google Vertex provider to check for `GEMINI_API_KEY` before falling back to `VERTEX_API_KEY`
- Updated documentation to mention both `GEMINI_API_KEY` and `GOOGLE_API_KEY` options
- Auto-generated config schema updates
For Google AI Studio:
1. Provider config `apiKey`
2. `GEMINI_API_KEY` environment variable
3. `GOOGLE_API_KEY` environment variable
4. `PALM_API_KEY` environment variable (legacy)
For Google Vertex:
1. Provider config …
=> chore(providers): add GEMINI_API_KEY environment variable support

src/redteam/commands/generate.ts, src/redteam/index.ts
Really minor change, but I prefer to keep our payloads clean.
=> chore: prevent testGenerationInstructions from being serialized if not present

src/app/src/pages/eval/components/EvalOutputCell.tsx, src/providers/ollama.ts, src/util/convertEvalResultsToTable.ts, test/providers/ollama.test.ts
I noticed that Ollama outputs don't show token information like other models.
This PR adds token usage support for Ollama providers, allowing users to see token counts in the evaluation UI and in the CLI.
- **Add TokenUsage import** to Ollama provider
- **Extract token usage** from Ollama API responses (both completion and chat providers)
- **Map Ollama fields** to standard format:
- `prompt_eval_count` → `prompt_tokens`
- `eval_count` → `completion_tokens`
- Calculate `total_tokens` as sum
- **Fix UI display** to check both `output.tokenUsage` and `output.response.tokenUsage`
- **Fix token usage conversion** in `convertEvalResultsToTable`
- **Add comprehensive tests** for all token usage scenarios
- ✅ Token usage displays correctly in CLI output
- ✅ Token usage displays correctly in web …
=> fix: Ollama token usage

src/providers/mcp/client.ts
this would probably be fixed by specifying http vs sse transport, but currently the promptfoo mcp client just tries both types, and if one fails, it emits an error log, which makes it seem like the client didn't connect properly. This changes that log to a debug log, which is more appropriate.
=> chore: Change mcp log from error to debug

src/app/src/pages/eval/components/ResultsCharts.test.tsx, src/app/src/pages/eval/components/ResultsCharts.tsx, src/app/src/pages/eval/components/ResultsView.test.tsx, src/app/src/pages/eval/components/ResultsView.tsx
**Changes**
- Label bars with provider ids instead of `Column N`.
- Display Frequency and Score on the Y and X axes, respectively, making it clearer this is a histogram.
- Misc: Removes unused props.
**Before**
**After**
=> fix(webui): Eval results histogram improvements

src/app/src/pages/eval-creator/components/TestCasesSection.test.tsx, src/app/src/pages/eval-creator/components/TestCasesSection.tsx
This PR adds support for uploading YAML test case files in the Config Interface, complementing the existing CSV upload functionality.
- ✅ Updated file input to accept `.yaml` and `.yml` files in addition to `.csv`
- ✅ Added YAML parsing logic using `js-yaml` (already a dependency)
- ✅ Support for both array format (multiple test cases) and single test case object format
- ✅ Updated tooltip text to indicate support for both CSV and YAML
- ✅ Added comprehensive test coverage with vitest
- ✅ Graceful error handling with user-friendly error messages
- All tests pass ✅
- Linter and formatter run successfully ✅
- App builds without errors ✅
**Array of test cases:**
```yaml
- description: Test 1
vars:
key: value
assert:
- type: contains
value: expected
- description: Test 2
vars:
key: value2
``` …
=> feat(eval-creator): add YAML file upload support for test cases

src/providers/google/util.ts, test/providers/google/util.test.ts
Fixes `processImagesInContents` to only modify text parts that actually contain base64 images, preserving original formatting for text-only content.
#4767 introduced a regression where text-only parts were split by newline and each line was trimmed and sent as a separate part, breaking use cases that relied on original text layout.
Now only processes text when base64 images are actually found in the content, leaving other text formatting intact.
=> fix(providers): Preserve text formatting when no images present for Google provider

src/redteam/plugins/base.ts, test/redteam/plugins/base.test.ts
Enhanced the `parseGeneratedPrompts` function to generically detect and handle multi-line prompts:
1. **Multi-line Detection**: Added logic to detect when prompts span multiple lines by looking for multiple consecutive content lines after "Prompt:" markers
2. **Generic Handling**: Works for any multi-line format (AGENT/CUSTOMER, USER/ASSISTANT, etc.), not just specific conversation patterns  
3. **Backward Compatibility**: Preserves existing single-line prompt parsing behavior completely
4. **Proper Separation**: Correctly splits multi-line conversations into separate test cases
=> fix: handle multi-line prompts in parseGeneratedPrompts for testGenerationInstructions

src/server/routes/eval.test.ts, test/providers/pythonCompletion.unicode.test.ts
- Fixed flaky Python Unicode tests that were timing out
- Optimized test performance by caching Python path validation
- Added 10-second timeouts to ensure stability
- Created helper functions to reduce test setup overhead
- Parallelized test execution where possible
=> test: fix flaky Python Unicode tests

site/docs/configuration/reference.md
- Added complete documentation for the `commandLineOptions` configuration object
- Documents all 29 available properties that can be set as config defaults
- Includes practical examples showing filtering, prompt modifications, and variable settings
- Added new `CommandLineOptions` section to `/site/docs/configuration/reference.md`
- Added entry in main Config table linking to the new section
- Included comprehensive property table with types and descriptions
- Added YAML configuration example demonstrating various use cases
The `commandLineOptions` feature allows users to set default values for command-line options in their configuration files, reducing repetitive flag usage. This documentation makes this powerful feature more discoverable.
=> docs(site): add comprehensive commandLineOptions documentation

src/app/src/pages/eval/components/store.ts
`basic` may or may not already be included in `config.redteam.strategies`.
=> fix(webui): Deduplicate strategy ids

src/providers/google/ai.studio.ts, test/providers/google/ai.studio.test.ts, test/providers/google/image.test.ts
- Add explicit API key validation in AIStudioChatProvider to fail fast with clear error message
- Improve test reliability by properly clearing all Google API key environment variables
- Ensure all test scenarios provide API keys to prevent unintended failures
- Added API key validation check in `AIStudioChatProvider.callApi()` method
- Enhanced error message to include specific environment variable names users should set
- Fixed test setup/teardown to clear all Google-related API key env vars (GEMINI_API_KEY, GOOGLE_API_KEY, PALM_API_KEY, GOOGLE_GENERATIVE_AI_API_KEY)
- Added explicit API keys to all test provider instances to ensure deterministic test behavior
=> chore(providers): improve Google API key error handling and test reliability

jest.config.ts, test/assertions/modelGradedClosedQa.test.ts
This PR fixes the intermittent segmentation fault occurring in the `modelGradedClosedQa` test suite when running on macOS with Node 24.x.
The segmentation fault was caused by:
- Race conditions in Jest worker processes when running tests in parallel
- Improper mock cleanup between test runs
- Memory management issues with Jest workers on Node 24.x
1. **Enhanced Jest configuration** to improve test isolation:
- `resetMocks: true` - Automatically reset mock state between tests
- `restoreMocks: true` - Restore original implementations after each test  
- `clearMocks: true` - Clear mock call history between tests
- `maxWorkers: '50%'` - Use half the available CPU cores for better stability
- `workerIdleMemoryLimit: '1GB'` - Prevent memory-related crashes
2. **Improved mock management** in the …
=> test: fix modelGradedClosedQa test segmentation fault on macOS/Node 24

src/providers/google/util.ts, test/providers/google/util.test.ts
Fixes WebP image detection in the Google provider by correcting the base64 signature check from "UklGRg" to "UklGR".
The Google provider was checking for WebP files starting with the Base64-encoded string "UklGRg", but it should be "UklGR" (without the trailing "g"). This was causing WebP images to not be properly recognized when using the Google Gemini provider.
WebP files start with the ASCII characters "RIFF" followed by the file size as a uint32. When encoding "RIFF" (32 bits) in Base64 (which uses 6-bit groupings), it results in "UklGR" (5 characters × 6 bits = 30 bits), with 2 bits left over that carry into the next Base64 grouping. Since the next bytes are the file size (which is variable), the next character after "UklGR" is variable.
- Fixed WebP detection in …
=> fix(providers): correct WebP image detection in Google provider

src/app/src/pages/redteam/setup/components/Plugins.tsx
=> chore: Add link to documentation in plugin sample modal

examples/json-output/promptfooconfig.yaml
GPT 4.1-mini was responding with json in markdown instead of a json object. Setting the response format to `json_object` is the reliable way of getting a json object.
=> fix: Fix json-output example

src/commands/eval.ts, src/evaluator.ts, test/evaluator.progress.test.ts, test/evaluator.test.ts
Progress bar groups are pretty meaningless.  Originally the intention of the multibar was to demonstrate concurrency, but now the groups do not reflect the true concurrency.  Concurrency is communicated by the info message before the progress bar, therefore we can just simplify to a single bar which is more standard
=> chore: simplify eval progress bar

site/docs/guides/multimodal-red-team.md, site/docs/red-team/strategies/audio.md, site/docs/red-team/strategies/image.md, site/docs/red-team/strategies/video.md
- Add cross-references between image, audio, and video strategy documentation
- Link strategy docs to the comprehensive multimodal red team guide  
- Add video strategy section to the multimodal guide
- Updated `site/docs/red-team/strategies/image.md` - added links to video strategy and multimodal guide
- Updated `site/docs/red-team/strategies/audio.md` - added links to video strategy and multimodal guide
- Updated `site/docs/red-team/strategies/video.md` - added link to multimodal guide
- Updated `site/docs/guides/multimodal-red-team.md` - added video strategy section and link
=> docs(site): add cross-links between multimodal strategy documentation

src/providers/openrouter.ts, test/providers/openrouter.test.ts
Relates to https://github.com/promptfoo/promptfoo/issues/5262
originally we fixed thinking / reasoning for gemini only, now this handles all thinking/reasoning for openrouter. Not the best fix, but it does the job.
=> fix: handle thinking tokens for openrouter

src/share.ts
A lot of users have been hitting ngnix max request size errors. The default max request size of ngnix is 1mb, so setting this just below that.
=> fix: lower sharing chunk size

src/app/src/pages/redteam/report/components/Report.tsx
https://github.com/promptfoo/promptfoo/pull/5271 introduced filtering errors from reports but accidentally filters failure cases.
=> fix(webui/reports): Don't exclude failure cases from stats

site/docs/providers/vertex.md, src/providers/adaline.gateway.ts, src/providers/google/image.ts, src/providers/google/types.ts, src/providers/google/util.ts, src/providers/google/vertex.ts, test/providers/google/image.test.ts, test/providers/google/vertex.test.ts
This is to handle a new config field, `credentials`, which allows the user to specify credentials in their config, rather than an env var.
=> feat: add google vertex credentials in config

examples/simple-mcp/README.md, examples/simple-mcp/example-server.js, examples/simple-mcp/package.json, examples/simple-mcp/promptfooconfig.yaml
This fixes the mcp eval example `examples/simple-mcp`, which had the wrong test schema. Also updates the simple mcp server to use the latest api for mcp, and updates the documentation.
=> fix: mcp eval example

src/app/src/pages/redteam/setup/components/Targets/HttpEndpointConfiguration.tsx
- Add prominent "AI Auto-fill from Example" button to HTTP configuration UI
- Improve dialog with better descriptions and labels for user guidance
- Users can paste HTTP request/response examples to auto-generate configuration
https://github.com/user-attachments/assets/d71df3fa-fc44-4486-8b6b-dd9aceb989ff
=> feat: add AI auto-fill for HTTP target configuration

src/providers/openrouter.ts, test/providers/openrouter.test.ts
Relates to https://github.com/promptfoo/promptfoo/issues/5262
For some reason, when qwen does a tool call, `message.content` is set to "\n\n", so it would output two newlines rather than the tool call.
=> fix: Handle Qwen tool call responses in openrouter provider

src/providers/http.ts, test/providers/http-pfx-signature.test.ts
- Add safe, detailed PFX debug logs (source detection, sizes, pre-sign info)
- Wrap signing in try/catch with diagnostics
- Switch to async fs.promises.stat for non-blocking logging
- Add tests covering PFX error paths and success via generateSignature
- All tests pass (npx jest --ci) and build succeeds
=> chore(http): improve PFX debug logging + tests

site/docs/providers/python.md, site/docs/usage/troubleshooting.md, src/python/pythonUtils.ts, test/python/pythonUtils.test.ts
This PR fixes Windows Python detection issues where users encounter `spawn py -3 ENOENT` errors when they have Python installed but lack the Python launcher (`py.exe`).
- **Fixed space character bug**: Windows fallback was incorrectly set to `' '` instead of `'py -3'`
- **Added intelligent Python detection**: New `getSysExecutable()` function uses `python -c "import sys; print(sys.executable)"` to find the actual Python path
- **Improved detection priority order**:
1. `PROMPTFOO_PYTHON` environment variable
2. Provider config (`pythonExecutable` or `pythonPath`)
3. Smart sys.executable detection
4. Fallback commands (prioritizing `python` over `py -3` on Windows)
- **Enhanced Windows support**: Automatic `.exe` suffix handling and better fallback logic
- **Added `pythonPath` config …
=> fix: improve Windows Python detection and add sys.executable support

src/util/config/load.ts, test/util/config/load.test.ts
This PR uncovered a bug where we default sharing to true, which is not intended https://github.com/promptfoo/promptfoo/pull/5404
=> fix: default sharing to false

site/docs/providers/custom-api.md
Update custom API provider documentation to clarify when to use .mjs vs .js extensions:
- Change basic example from echoProvider.js to echoProvider.mjs with explanatory comment
- Update configuration examples to show .mjs extension for ES6 modules
- Add commented alternative showing .js option for CommonJS modules
This helps users avoid common "Unexpected token 'export'" errors when using ES6 export default syntax in CommonJS projects.
=> docs: clarify file extension requirements for custom providers

test/providers/pythonCompletion.unicode.test.ts
- Eliminates flaky test timeouts in `pythonCompletion.unicode.test.ts` that were failing on Windows CI with 5000ms timeouts
- Replaces expensive Python process spawning with mocking for fast, reliable tests
- Maintains 100% test coverage of Unicode handling behavior
- Mock `runPython` to eliminate process spawning overhead
- Add verification that correct Unicode strings reach the Python layer
- Preserve all existing Unicode handling validations
- Add comprehensive parameter passing verification
- **Before**: 5000ms+ timeout failures on Windows CI
- **After**: 1-6ms consistent execution time across all platforms  
- **Reliability**: 100% consistent test execution
✅ Unicode character preservation through provider layer  
✅ Correct parameter marshalling to Python execution  
✅ JSON …
=> fix: eliminate flaky Unicode test timeouts on Windows CI

src/providers/google/util.ts, test/providers/google/util.test.ts
resolves: #5501
I confirmed that the following config, which previously did not work, now works with this fix.
https://gist.github.com/pokutuna/071b4812933e79022a058d1af5de6320
- `$ GEMINI_API_KEY=*** npm run local -- eval -c ./gemini-systemonly-reproduce-google.yaml`
- `$ npm run local -- eval -c ./gemini-systemonly-reproduce-vertex.yaml` (with gcloud credentials)
=> fix(providers): handle system-only prompt in Gemini

CLAUDE.md, site/src/plugins/docusaurus-plugin-og-image/index.js
The documentation build process often times out in CI due to OG (Open Graph) image generation taking too long. This blocks PRs with documentation changes and creates friction for contributors.
Added  environment variable to bypass OG image generation when set to 'true':
- **Fast builds**: Reduces docs build time from ~5+ minutes to under 20 seconds
- **CI reliability**: Prevents timeout failures for documentation-only changes  
- **Selective usage**: Can be enabled only when OG images aren't needed
> promptfoo-docs@0.0.1 build
> docusaurus build
[INFO] [en] Creating an optimized production build...
[webpackbar] ℹ Compiling Client
[webpackbar] ℹ Compiling Server
[webpackbar] ✔ Server: Compiled successfully in 6.10s
[webpackbar] ✔ Client: Compiled successfully in 6.64s
⏭️  Skipping OG image …
=> docs: add SKIP_OG_GENERATION environment variable for faster docs builds

drizzle/0020_skinny_maverick.sql, drizzle/meta/0020_snapshot.json, drizzle/meta/_journal.json, site/docs/usage/command-line.md, src/cliState.ts, src/commands/eval.ts, src/database/tables.ts, src/evaluator.ts, src/models/eval.ts, src/models/evalResult.ts, test/evaluator.test.ts
Ability to pause evals (Ctrl+C) and resume them with `promptfoo eval --resume`
=> feat: ability to pause/resume evals

src/share.ts
- Changed error logging to debug logging in hasModelAuditBeenShared function
- This check is non-critical (used only for confirmation dialog when re-sharing)
- Reduces noise during model audit sharing when network connectivity has issues
1. Create a test model file:
```python
import pickle
class TestModel:
def __init__(self):
self.weights = [1, 2, 3]
model = TestModel()
with open('test.pkl', 'wb') as f:
pickle.dump(model, f)
```
2. Scan the model:
```bash
promptfoo scan-model test.pkl --name "Test Scan"
```
3. Share the scan (note the scan ID from step 2):
```bash
promptfoo share <scan-id>
```
4. Verify clean output with no error messages about "hasModelAuditBeenShared"
When sharing model audits, the system checks if the audit has already been shared to show a confirmation dialog. Network …
=> fix: hide non-critical hasModelAuditBeenShared error logging

src/commands/eval.ts
This may cause orphaned database locks, so disabling until we can troubleshoot
=> fix: temporarily disable SIGINT handler

biome.json
This has stopped biome from taking up 10gb of memory on my machine.
=> chore: Exclude node modules and build/dist from biome

src/app/src/components/traces/TraceTimeline.tsx, src/app/src/components/traces/TraceView.test.tsx, src/app/src/components/traces/TraceView.tsx, src/app/src/pages/eval/components/DebuggingPanel.test.tsx, src/app/src/pages/eval/components/DebuggingPanel.tsx, src/app/src/pages/eval/components/EvalOutputCell.tsx, src/app/src/pages/eval/components/EvalOutputPromptDialog.test.tsx, src/app/src/pages/eval/components/EvalOutputPromptDialog.tsx
Resolves two core issues with trace visualization in the web UI:
• **Circular dependency fix**: Traces tab now always appears when evaluationId exists, eliminating the chicken-and-egg problem where hasTraces state prevented the tab from showing
• **Format reconciliation**: Simplified TraceView filtering with robust fallback logic to handle both UUID testCaseIds (from evaluations) and "testIdx-promptIdx" format (from trace system)
• **Component improvements**: Added promptIndex prop threading throughout the component chain for better trace filtering
- `EvalOutputPromptDialog.tsx`: Always show traces tab when evaluationId exists, removed unused hasTraces state
- `TraceView.tsx`: Simplified filtering with try-direct-match then fallback approach
- `DebuggingPanel.tsx`: Added testIndex and …
=> fix: trace visualization circular dependency

src/app/src/pages/redteam/report/components/ReportIndex.test.tsx, src/app/src/pages/redteam/report/components/ReportIndex.tsx, src/app/src/pages/redteam/report/page.test.tsx, src/app/src/pages/redteam/report/page.tsx
- Remove unnecessary conditional title logic in page.tsx since Report component sets its own title
- Remove unnecessary data dependency in ReportIndex useMemo to prevent unnecessary re-renders
Relates to https://github.com/promptfoo/promptfoo/pull/5637#discussion_r2363258791
=> refactor(redteam): remove dead code and optimize page meta handling

src/app/src/pages/eval/components/ResultsView.test.tsx, src/app/src/pages/eval/components/ShareModal.test.tsx
Fix TypeScript compilation errors that were exposed after upgrading Vite from v6 to v7 in commit 16ff8409b.
The recent Vite upgrade to v7 (PR #5681) exposed existing TypeScript errors in test files that were previously not caught by the build process. The upgrade brought stricter compilation checking that revealed:
1. **ResultsView.test.tsx**: Mock object structure didn't match the `ResultLightweightWithLabel` interface
- `createdAt` field expected `number` (timestamp) but was receiving `string` 
- Missing required `evalId` and `datasetId` fields from the interface
2. **ShareModal.test.tsx**: Mock `callApi` responses used plain objects instead of proper `Response` objects
- Tests were mocking with `{ ok: true, json: () => Promise.resolve(...) }` 
- But `callApi` returns …
=> fix(tests): correct TypeScript errors in test files

src/app/src/pages/eval/components/EvalOutputCell.tsx
resolves #5704 
This is necessary for use cases where we need to evaluate outputs that include both Markdown text for users and multiple structured data from an Agent.
Markdown rendering (top) and JSON output (bottom)
https://gist.github.com/pokutuna/8fc497e03a2e81259cd95d75cba50927
=> fix(webui): prioritize JSON prettify over Markdown rendering when both enabled

src/share.ts, src/util/fetch/index.ts, src/util/fetch/monkeyPatchFetch.ts, src/util/fetch/types.ts, test/commands/export.test.ts
We're running into some massive evals where the config is > 50mb with 30k tests. This makes for a massive http request. Using gzip compresses that down to 8mb which is much more manageable.  This is not an ideal solution but that would require a major re-work of our data model which is not in the cards right now.
Added it as an option in our fetch so it can be re-used other places in the future if needed.
=> feat: Compress data when sharing an eval

src/updates.ts, test/updates.test.ts
- Add `x-promptfoo-silent` header to update check API requests to suppress ugly error logging
- Fixes verbose stack traces appearing when version check APIs timeout 
- Update corresponding test expectations
```
Error in fetch: {
"stack": "AbortError: This operation was aborted\n    at node:internal/deps/undici/undici:13502:13..."
} AbortError: This operation was aborted
```
Clean output with no error logging when update checks timeout (as intended).
=> fix: suppress verbose error logging for update check timeouts

src/providers/openai/embedding.ts, test/providers/openai/embedding.test.ts
- Add input type validation to catch objects early with clear error messages
- Add API key validation before making requests
- Add HTTP status code checking (200-299 range)
- Change from throwing exceptions to returning error objects
- Follow same error handling patterns as chat provider
- Add proper cache cleanup on errors
Resolves issues where invalid API keys or malformed inputs would result in unhelpful "Request failed after 4 retries: undefined" error messages. Now returns immediate, actionable error messages.
=> fix: improve OpenAI embedding provider error handling

src/app/src/pages/redteam/setup/components/Targets/CustomTargetConfiguration.test.tsx, src/app/src/pages/redteam/setup/components/Targets/CustomTargetConfiguration.tsx
Fixes an issue where Python and JavaScript provider file paths created through the UI would lose their `file://` prefix, causing "Could not identify provider" errors when running `npx promptfoo redteam run` from the CLI.
- **CustomTargetConfiguration.tsx**: Auto-add `file://` prefix for `.py` and `.js` paths, strip for display
- **CustomTargetConfiguration.test.tsx**: Added comprehensive test coverage (7 tests)
- ✅ All new tests passing (7/7)
- ✅ Existing tests passing
- ✅ Lint and format checks passing
=> fix: ensure python and js providers have appropriate path prefix

site/docs/providers/python.md
The metadata field (Dict[str, Any]) is now documented in the Python provider ProviderResponse type definition. This field allows providers to return arbitrary metadata that will be displayed in the Metadata tab of the evaluation output dialog drawer in the web UI.
The metadata is rendered in a key-value table format via the MetadataPanel component, making it easy for users to inspect additional provider-specific information such as HTTP headers, request details, or custom debugging data.
=> fix(site): add metadata key to the provider response class

src/app/src/pages/redteam/setup/components/Targets/tabs/SessionsTab.tsx
This advice was incorrect. Session parser can be one of: 
- JS expression, which is then fed into a function `data => <expression>`
- a function (response) => ...
- a reference to a javascript file with a default export
There's no `response` variable available in any scope, unless you define a function in option 2.
=> chore: Fix incorrect session parser help text

package-lock.json
- Fixed 18 npm audit vulnerabilities (17 moderate, 1 high) by running `npm audit fix`
- Updated dependencies in package-lock.json
=> chore: fix npm audit vulnerabilities

src/app/src/pages/eval/components/EvalOutputPromptDialog.test.tsx
- Fixed `ReferenceError: window is not defined` error in EvalOutputPromptDialog tests
- Replaced `setTimeout` with `queueMicrotask` in DebuggingPanel mock
=> test: fix vitest timeout error in EvalOutputPromptDialog tests

test/providers/pythonCompletion.fileRef.test.ts, test/providers/pythonCompletion.test.ts, test/providers/pythonCompletion.unicode.test.ts, test/python/wrapper.test.ts
Apply the same mock reset and state cleanup pattern from PR #5824 to all Python provider and wrapper tests to prevent test interference and timeouts on Windows.
After fixing the flaky Python assertion tests in #5824, discovered that the Python provider tests (`pythonCompletion.*.test.ts`) also needed the same mock cleanup pattern to prevent intermittent timeouts. Additionally, the `wrapper.test.ts` race condition tests were timing out on Windows Node 22.x.
**Python Provider Tests:**
- Added `mockReset()` for `runPython` mock in `beforeEach` hooks
- Reset `pythonUtils.state` (`cachedPythonPath`, `validationPromise`) between tests
- Applied to:
- `pythonCompletion.test.ts`
- `pythonCompletion.unicode.test.ts`  
- `pythonCompletion.fileRef.test.ts`
**Wrapper Race Condition Tests:**
- Mock …
=> test: add mock cleanup to Python provider tests

src/app/src/pages/redteam/README.md
Removes outdated license notice from redteam UI directory. The entire project is MIT licensed.
=> chore: remove outdated license notice

src/python/pythonUtils.ts, test/python/wrapper.test.ts
Fixes race condition in `validatePythonPath` that causes CI test flakiness on Windows, particularly in the "validatePythonPath race conditions" test suite.
The original implementation had a classic check-then-act race condition:
```typescript
// BEFORE (vulnerable to race condition)
if (state.validationPromise) {
return state.validationPromise;
}
// Race window here - multiple threads can reach this point!
const validationPromise = (async () => { ... })();
state.validationPromise = validationPromise;
```
When multiple concurrent calls arrived:
1. All checked `validationPromise` (null) simultaneously
2. All created separate validation promises
3. All triggered duplicate Python detection (multiple `where python`, `py`, etc.)
4. Last assignment won, but all validations ran in parallel
On …
=> fix: eliminate Python validation race condition on Windows

CLAUDE.md
Add explicit warning in Git Workflow section to never use `git commit --amend` or `git push --force` unless explicitly requested by the user.
This helps prevent accidental force pushes and history rewrites without user consent.
=> docs: add warning against using commit --amend and force push

examples/watsonx/README.md, examples/watsonx/promptfooconfig.yaml, site/docs/providers/watsonx.md, test/providers/watsonx.test.ts
Updates the IBM WatsonX provider documentation with accurate, verified model information based on the current IBM watsonx.ai API response.
- **Updated model list** based on actual API response (23 text generation/chat models)
- **Added new models**:
- `ibm/granite-4-h-small` - Latest 32B parameter model
- `meta-llama/llama-4-maverick-17b-128e-instruct-fp8` - Latest Llama 4
- `mistralai/mistral-medium-2505` - Latest Mistral mid-tier model
- **Removed outdated models** no longer available via IBM's API
- **Fixed environment variable names** to match provider implementation:
- `WATSONX_AI_APIKEY` (not `WATSONX_API_KEY`)
- `WATSONX_AI_PROJECT_ID` (not `WATSONX_PROJECT_ID`)
- **Made documentation evergreen** with instructions to check IBM's API for latest models
- **Clarified scope**: Text …
=> docs: update IBM WatsonX model list

src/commands/eval.ts, src/models/eval.ts, src/redteam/shared.ts
Red teams were being shared twice, once in the eval flow and once in the red team run command code. This removes that second share and relies on the eval code to share it properly.
=> fix: double sharing red teams
